<?php 
 use Common\ActionForms\ExplorerForm;
use Common\Utilities\Constants;
$form = $this->form;
$allstates=explode(",",Constants::COUNTY);
?>
<div class="container">    
        <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">                    
            <div class="panel panel-info" >
                    <div class="panel-heading">
                        <div class="panel-title">Explore</div>
                       
                    </div>     

                    <div style="padding-top:30px" class="panel-body" >

                        <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>
                            
                        <form id="exploreform" class="form-horizontal" role="form" method="post" action="">
                       <?php if(isset($this->error)){?>
                       <div class="alert alert-danger" role="alert"><?php echo $this->error;?></div>
                       <?php }?>
                        <?php if(isset($this->info)){?>
                       <div class="alert alert-info" role="alert"><?php echo $this->info;?></div>
                       <?php }?>
                               
                          <!-- 
                          <div class="form-group">
                            <label class="col-sm-4 control-label">Email</label>
                            <div class="col-sm-8">
                              <input type="email" class="form-control" id="inputemail" placeholder="Email id" name="email" value="<?php echo $form->getEmail();?>">
                            </div>
                          </div>
                           -->
                          <div class="form-group ">
                            <label class="col-sm-4 control-label">Current Residence</label>
                             <div class="col-sm-8" style="padding-top:10px;">
                              <input type="radio" name="state" <?php if($form->getState()=="CA"){?> checked <?php }?> value="CA" id="cal" > <span style="margin-right:10px;">California</span></input>
                              <input type="radio" name="state" value="AUS" id="aus" <?php if($form->getState()=="AUS"){?> checked <?php }?>>  <span style="margin-right:10px;">Another US State</span></input>
                              <input type="radio"  name="state" value="OUS" id="ous" <?php if($form->getState()=="OUS"){?> checked <?php }?>> Outside US</input>
                             </div>
                          </div>
                         

                          <div class="form-group ">
                            <label class="col-sm-4 control-label">CA county</label>
                             <div class="col-sm-8" style="padding-top:10px;">
                              <select name="county" id="county">
                                  <option>Select</option>
                                  
                                  <?php foreach ($allstates as $val){?>
                                  
                                 <option value="<?php echo $val;?>" <?php if($form->getCounty()==$val){?> selected="selected" <?php }?>><?php echo $val;?></option>
                                 
                                 <?php }?>
                                  
                                </select> 
                             </div>
                          </div>
                          <div class="form-group" >
                            <label class="col-sm-4 control-label">Standardized Test(s)</label>
                             <div class="col-sm-8" >
                               <label class="cbox btn btn-default" ><input type="radio" name="exam" id="act" value="act" <?php if($form->getExam()=='act'){?> checked="checked" <?php }?>> ACT</label>
                               <label class="cbox btn btn-default" ><input type="radio" name="exam" id="sat" value="sat" <?php if($form->getExam()=='sat'){?> checked="checked"  <?php }?>> SAT</label>
                                <label class="cbox btn btn-default" ><input type="radio" name="exam" id="psat" value="psat" <?php if($form->getExam()=='psat'){?> checked="checked" <?php }?> > PSAT</label>
                             </div>
                          </div>

                         
                          <!-- hidden divs -->
                          
                       
                          <div class="act box" id="act">
                            <div class="form-group ">
                              <label class="col-sm-4 control-label">ACT Composite</label>
                              <div class="col-sm-8 ">
                                <input class="slider " data-slider-max="36" data-slider-min="1" data-slider-value="<?php echo $form->getAct();?>" value="<?php echo $form->getAct();?>" type="text" name="act" id="actslider" value="34">
                              </div>
                            </div>
                            <div class="form-group ">
                              <label class="col-sm-4 control-label">Act English & Writing</label>
                              <div class="col-sm-8">
                                <input class="slider" data-slider-max="36" data-slider-min="1" data-slider-value="<?php echo $form->getActew();?>" value="<?php echo $form->getActew();?>" type="text" name="actew" id="actewslider">
                              </div>
                            </div>
                            
                          </div>
                          
                             <div class="sat box" >
                            <div class="form-group ">
                              <label class="col-sm-4 control-label">Critical Reading</label>
                              <div class="col-sm-8 ">
                                <input class="slider " data-slider-max="800" data-slider-min="200" data-slider-value="<?php echo $form->getsatread();?>" value="<?php echo $form->getsatread();?>" type="text" id="satreadslider" name="satread" data-slider-step="10">
                              </div>
                            </div>
                            <div class="form-group ">
                              <label class="col-sm-4 control-label">Math</label>
                              <div class="col-sm-8">
                                <input class="slider" data-slider-max="800" data-slider-min="200" data-slider-value="<?php echo $form->getsatmath();?>" value="<?php echo $form->getsatmath();?>" type="text" id="satmathslider" name="satmath" data-slider-step="10">
                              </div>
                            </div>
                            <div class="form-group">
                              <label class="col-sm-4 control-label">Writing</label>
                              <div class="col-sm-8">
                                <input class="slider" data-slider-max="800" data-slider-min="200" data-slider-value="<?php echo $form->getsatwrite();?>" value="<?php echo $form->getsatwrite();?>" type="text" id="satwriteslider" name="satwrite" data-slider-step="10">
                              </div>
                            </div>
                                
                          </div>
                          

                          <div class="psat box">
                            <div class="form-group ">
                              <label class="col-sm-4 control-label">Critical Reading</label>
                              <div class="col-sm-8 ">
                                <input class="slider " data-slider-max="80" data-slider-min="20" data-slider-value="<?php echo $form->getpsatread();?>" value="<?php echo $form->getpsatread();?>" type="text" id="psatreadslider"  name="psatread" data-slider-step="1">
                              </div>
                            </div>
                            <div class="form-group ">
                              <label class="col-sm-4 control-label">Math</label>
                              <div class="col-sm-8">
                                <input class="slider" data-slider-max="80" data-slider-min="20" data-slider-value="<?php echo $form->getpsatmath();?>"  value="<?php echo $form->getpsatmath();?>" type="text" id="psatmathslider" name="psatmath" data-slider-step="1">
                              </div>
                            </div>
                            <div class="form-group">
                              <label class="col-sm-4 control-label">Writing</label>
                              <div class="col-sm-8">
                                <input class="slider" data-slider-max="80" data-slider-min="20" data-slider-value="<?php echo $form->getpsatwrite();?>" value="<?php echo $form->getpsatwrite();?>" type="text" id="psatwriteslider" name="psatwrite" data-slider-step="1">
                              </div>
                            </div>
                            
                          </div>

                          <!-- /hidden divs -->

                         

                          <div class="form-group">
                            <label class="col-sm-4 control-label">Weighted GPA score</label>
                            <div class="col-sm-8">
                            <input class="slider" data-slider-max="5" data-slider-min="2" id="gpa" data-slider-value="<?php echo  $form->getGpa()?>" type="text" name="gpa" value="<?php echo  $form->getGpa()?>" data-slider-step="0.01">
                               
                             <span id="ex6SliderVal"></span>
                            </div>
                          </div>

                        <!--    <div class="form-group">
                            <label class="col-sm-4 control-label">A-G Compliance</label>
                            <div class="col-sm-8" style="padding-top:10px;">
                              
                            <input type="checkbox" name="atogCompliance" checked >
                            </div>
                          </div>
						-->
                          <div style="margin-top:10px" class="form-group">
                                    <!-- Button -->

                                    <div class="col-sm-12 controls">
                                      <button id="btn-login" type="submit" class="btn btn-primary col-sm-12">Explore</button>
                                    </div>
                                </div>
                            </form>     

                            <div id="result">
                            <?php if($form->getisResult()){?>
                            
                              <?php if(count($form->getReach())>0) {?>
                            
                            <div id="reach">
                              <h4>Reach</h4>
                              <table class="table"> 
                                <tbody>
                                
                                <?php foreach ($form->getReach() as $rec){?>
                                  <tr>
                                    <td><img src="images/logo4.jpg"></td>
                                    <td class="univ-title"><?php echo $rec; ?></td>
                                  </tr>
                                 <?php }?>
                                </tbody>
                              </table>
                            </div>
                             <hr style="border:2px solid #666;" />
                            <?php }?>
                            
                            
                             <?php if(count($form->getTarget())>0) {?>
                            <div id="target">
                              <h4>Target</h4>
                              <table class="table"> 
                                <tbody>
                                  <?php foreach ($form->getTarget() as $rec){?>
                                  <tr>
                                    <td><img src="images/logo4.jpg"></td>
                                    <td class="univ-title"><?php echo $rec; ?></td>
                                  </tr>
                                   <?php }?>
                                 
                                </tbody>
                              </table>
                            </div>
                            <hr style="border:2px solid #666;"/>
                            <?php }?>
                            
                             <?php if(count( $form->getSafety())>0) {?>
                            <div id="safe">
                              <h4>Safety</h4>
                              <table class="table"> 
                                <tbody>
                                    <?php foreach ($form->getSafety() as $rec){?>
                                  <tr>
                                    <td><img src="images/logo1.jpg"></td>
                                    <td class="univ-title"><?php echo $rec; ?></td>
                                  </tr>
                                    <?php }?> 
                                </tbody>
                              </table>
                            </div>
                           
                           <?php }?>
                          
                            
                            
                            
                            
                          
                             <div style="margin-top:10px" class="form-group">
                             
                               <form id="exploreform" class="form-horizontal" role="form" method="post" action="">
                                 <div class="col-sm-12 controls">
                                <button type="submit" name="saveresult" value="saveresult" class="btn btn-primary">
								Save Results
								</button>
								<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
								Share Results
								</button>
								</div>
								</form>
								
								</div>
                             
                            <?php }?>
                            
                            </div>
				       </div>                     
                  </div>  
        </div>
        
        
        
        <!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <form action="" method="post">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Share results via Email</h4>
      </div>
      <div class="modal-body">
       <div class="form-group">
            <label for="message-text" class="control-label">Enter the email ids:</label>
            <textarea class="form-control" id="message-text" name="shareemail"></textarea>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" name="sendmail" value="sendmail" class="btn btn-primary">Send Mail</button>
      </div>
    </div>
  </div>
  </form>
 
</div>
         
        
         <script type="text/javascript">


       // initialize all slider  
         
       $("#gpa").slider();
       $("#actslider").slider();
       $("#actewslider").slider();

       $("#satreadslider").slider();
       $("#satmathslider").slider();
       $("#satwriteslider").slider();

       $("#psatreadslider").slider();
       $("#psatmathslider").slider();
       $("#psatwriteslider").slider();
       
        /*  $("#gpa").on("slide", function(slideEvt) {
         	$("#ex6SliderVal").text(slideEvt.value);
         });
 */
       
         

         
    $(document).ready(function(){
        $(".sat").hide(), $(".act").hide(), $(".psat").hide();
        $('input[type="radio"]').click(function(){
            if($(this).attr("value")=="sat"){
                $(".sat").toggle();
                


                $(".psat").hide();
                $(".act").hide();
                $("#result").hide();
                
               /*  if(($('#sat').is(':checked'))){
                    
                $("#act").prop("disabled", true);
              	$("#psat").prop("disabled", true);
              	$('#act').attr('checked', false);
              	$('#psat').attr('checked', false);
                }else{
                	$("#act").prop("disabled", false);
                  	$("#psat").prop("disabled", false);
                    
                } */
            }
            if($(this).attr("value")=="act"){
                $(".act").toggle();
              	$(".psat").hide();
                $(".sat").hide();
                $("#result").hide();
               /*  if(($('#act').is(':checked'))){
                $("#sat").prop("disabled", true);
              	$("#psat").prop("disabled", true);
              	$('#sat').attr('checked', false);
              	$('#psat').attr('checked', false);
                }else{
                	$("#sat").prop("disabled", false);
                  	$("#psat").prop("disabled", false);
                    
                } */

                
            }
            if($(this).attr("value")=="psat"){
                
                $(".psat").toggle();
                $(".act").hide();
                $(".sat").hide();
                $("#result").hide();
                
               /*  if(($('#psat').is(':checked'))){
                $("#sat").prop("disabled", true);
              	$("#act").prop("disabled", true);
              	$('#sat').attr('checked', false);
              	$('#act').attr('checked', false);
                }else{
                	$("#sat").prop("disabled", false);
                  	$("#act").prop("disabled", false);
                    
                } */
               	
            }
        });


        if(($('#act').is(':checked'))){
        	 $(".act").toggle();
        	/*  $("#sat").prop("disabled", true);
           	$("#psat").prop("disabled", true); */
        }

       
        
        if(($('#sat').is(':checked'))){
        	 $(".sat").toggle();
        	 /* $("#psat").prop("disabled", true);
           	$("#act").prop("disabled", true); */
        }
        if(($('#psat').is(':checked'))){
        	
           $(".psat").toggle();
           /* $("#sat").prop("disabled", true);
         	$("#act").prop("disabled", true); */
		 }
       
        $('#aus').click(function(){
        	$("#county").prop("disabled", true);
        });

        $('#cal').click(function(){
        	$("#county").prop("disabled", false);
        });
        $('#ous').click(function(){
        	$("#county").prop("disabled", true);
        });

        if(($('#cal').is(':checked'))){
       	 //alert("a");
      	 $("#county").prop("disabled", false);
      }else{
   	   //alert("b");
   	   $("#county").prop("disabled", true);
      }
       
        
    });
</script>
         
 
  
  