<div class="container">    
        <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">                    
            <div class="panel panel-info" >
                    <div class="panel-heading">
                        <div class="panel-title">Forget Password</div>
                       
                    </div>     

                    <div style="padding-top:30px" class="panel-body" >

                        <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>
                            
                        <form id="loginform" class="form-horizontal" role="form" action="" method="post">
                        
                      
                                 
                             <div class="form-group">
 							 <label class="control-label" for="inputGroupSuccess1">Please Enter your email address</label>
                                    
                            <div style="margin-bottom: 25px" class="input-group">
                               <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
                              <input id="login-username" type="text" class="form-control" name="username" value="" placeholder="Email">  
                                                                  
                            </div>
                            </div>
                           
                            <div style="margin-top:10px" class="form-group">
                                    <!-- Button -->

                                    <div class="col-sm-12 controls">
                                      <button id="btn-login" type="submit" class="btn btn-primary col-sm-12">Reset Password</button>
                                    </div>
                                </div>


                                <div class="form-group">
                                    <div class="col-md-12 control text-center">
                                        <div style="border-top: 1px solid#888; padding-top:15px; font-size:85%" >
                                            Don't have an UCeasy account! 
                                        <a href="<?php $this->basePath();?>signup" >
                                            Sign up Here
                                        </a>
                                        </div>
                                    </div>
                                </div>    
                            </form>     



                        </div>                     
                    </div>  
        </div>