<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <link rel="icon" type="image/png" href="dist/img/favicon.ico">
    <title>UC and CSU Admissions Made Easy</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <meta name="description" content="UCEazy - UC and CSU Admissions Made Easy. An affordable software based solution for applying to public universities. UCEazy application is easy to use, understand and fit into a high school student's hectic lifestyle.  " />
    <meta name="keywords" content="UC admission, UC admissions, UC application, UC Essay, UC Personal Statement, Essay Review, UC admission help, UC admission advice, UC admission guidance, CSU admission, CSU admissions , CSU application, CSU admission help, CSU admission, advice, CSU admission guidance, GPA, GPA Calculator, UC GPA, CSU GPA, SAT to ACT conversion calculator, ACT to SAT conversion calculator , UC Activities and Awards, UC Resume, UC Cost of Attendance, UC Attendance Cost, CSU Cost of Attendance , CSU Attendance Cost, CSU application fee, CSU application cost, UC application fee, 
UC application cost,UC app costs, UC application costs, CSU app costs , CSU application costs, Explore, Plan, " />
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <!-- Font Awesome Icons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!--<link href="dist/font-awesome-4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />-->
    <!-- Ionicons -->
    <!--<link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />-->
    <link href="/dist/ionicons-2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="/dist/css/AdminLTE.css" rel="stylesheet" type="text/css" />
    <link href="/dist/css/skins/skin-black.css" rel="stylesheet" type="text/css" />
    <!-- Custom style -->
    <link href="/dist/css/styles.css" rel="stylesheet" type="text/css" />
    <!-- Jquery Scroll bar style -->
    <link href="/dist/css/jquery.scrollbar.css" rel="stylesheet" type="text/css" />


<script src="/dist/sweetalert.min.js"></script>
     <link rel="stylesheet" type="text/css" href="/dist/sweetalert.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="login-page">
    <div class="login-box">
      <div class="login-logo ">
        <a href="/"><img src="/dist/img/logo-uceazy-lg.png" alt="UCEazy Logo" class="img-responsive"></a>
      </div><!-- /.login-logo -->
      <div class="login-box-body">
        <p class="login-box-msg "><strong>Sign in</strong></p> <hr />
        <div class="row">
       
        <div id="simpleexperrordiv" class="alert alert-danger col-sm-12" style="display: none;">
                <div class="info-text-container-failure ">
                  	<i class="fa fa-close "></i> 
                    <span class="info-text" id="simpleexperror">
                    </span>
                 </div>
        </div>
        </div>
        
        <form action="" method="" id="signinForm" name="signinForm">
          <div class="form-group has-feedback">
            <div class="input-group">
              <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
              <input name="username" class="form-control" placeholder="Email">
            </div>
          </div>
          <div class="form-group has-feedback">
            <div class="input-group">
              <span class="input-group-addon"><i class="fa fa-lock"></i></span>
              <input type="password" class="form-control" name="password" placeholder="Password">
            </div>
            <label class="forgotPwdText">
                  <a href="/user/forgot" ><i>Forgot Password?</i></a>
            </label>
          </div>
          <div class="row">
            
            <div class="col-xs-12">
              <button type="submit" id="btn-login" class="btn btn-danger btn-block btn-flat" data-loading-text="Loading...." data-reset-text="Sign In">Sign In</button>
            </div><!-- /.col -->
          </div>
        </form>

         <div class="social-auth-links text-center">
          <p>- OR -</p>
          <a href="#" class="btn btn-block btn-social btn-facebook btn-flat" onclick="login('facebook');"><i class="fa fa-facebook"></i> Sign in using Facebook</a>
          <a href="#" class="btn btn-block btn-social btn-google-plus btn-flat" onclick="login('google');"><i class="fa fa-google-plus"></i> Sign in using Google+</a>
        </div> <!-- /.social-auth-links -->
        
        <div class="text-center loginInfotext">
          Don't have an UCEazy account! <a href="/user/signup" class="text-center"> Sign up</a>  here.
        </div>

      </div><!-- /.login-box-body -->

      <div class="copyRight1">Copyright &copy; 2015 <a href="/">UCEazy</a>. All rights reserved.
        </div>
    </div><!-- /.login-box -->

        <!-- REQUIRED JS SCRIPTS -->

        <!-- jQuery 2.1.4 -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script>
    // Fallback to loading jQuery from a local path if the CDN is unavailable
    (window.jQuery || document.write('<script src="plugins/jQuery/jQuery-2.1.4.min.js"><\/script>'));
    </script>

    <!-- Bootstrap 3.3.2 JS -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <script>
    // Fallback to loading jQuery from a local path if the CDN is unavailable
    ($.fn.modal || document.write('<script src="dist/js/bootstrap.min.js"><\/script>'));
    </script>
    
    <!-- Bootstrap css fallback -->
    <script>
      (function($) {
          $(function() {
              if ($('body').css('color') !== 'rgb(51, 51, 51)') {
                  $('head').prepend('<link rel="stylesheet" href="dist/css/bootstrap.min.css">');
              }
          });
      })(window.jQuery);
    </script>

    <!-- Font awesome fallback -->
    <script>
        (function($){
            var $span = $('<span class="fa" style="display:none"></span>').appendTo('body');
            if ($span.css('fontFamily') !== 'FontAwesome' ) {
                // Fallback Link
                $('head').append('<link href="dist/font-awesome-4.3.0/css/font-awesome.min.css" rel="stylesheet">');
            }
            $span.remove();
        })(jQuery);
    </script>


<!-- Hello.js Starts -->

<script src="/src/hello.js" class="pre"></script>
<script src="/src/modules/google.js" class="pre"></script>
<script src="/src/modules/facebook.js"></script>
<script class="pre">
function login(network){

	// By defining response type to code, the OAuth flow that will return a refresh token to be used to refresh the access token
	// However this will require the oauth_proxy server

	hello(network).login( { response_type:'code' }, log );
}
</script>
<script class="pre">
/*
hello('facebook').logout().then(function() {
	alert('Signed out');
}, function(e) {
	alert('Signed out error: ' + e.error.message);
});

hello('google').logout().then(function() {
	alert('Signed out');
}, function(e) {
	alert('Signed out error: ' + e.error.message);
});*/

hello.init({
	google :'408966465581-8eetj3o25en183f8qjtksmg9osg2d1c7.apps.googleusercontent.com',
	facebook: '1031602316861493'
},{
	redirect_uri:'http://apps.uceazy.com/redirect.html',
	scope : 'email'
});

hello.on('auth.login', function(r) {
	
	// Get Profile
	hello( r.network ).api( '/me' ).then( function(p) {
		
		$("#email").val(p.email);
		$("#uname").val(p.name);
 		var data = {
		      "email": p.email,
		      "name" : p.name,
		      "profilepic":p.picture,
		      "network":r.network,
			  "token":""
		    };
	 	    data = $.param(data);

		    $.ajax({
		      type: "POST",
		      dataType: "json",
		      url: "/service/insertupdateSocialAuth", 
		      data: data,
		      success: function(data) {
				  if(data['signupstatus']=='1'){
					  swal({   title: "Success!",   text: "Hello "+p.name+"!!! Successfully authenticated with " +r.network, type: "success",   confirmButtonText: "Show Home" },function() { document.location.href='/user/index' });
				  }else if(data['signupstatus']=='0'){
					  swal({   title: "Success!",   text: "Hello "+p.name+"!!! You are not yet Sign Up. Please signup first", type: "success",   confirmButtonText: "Sign Up" },function() { document.location.href='/user/signup' });
   		      }
		      },
		      error: function(xhr, textStatus, errorThrown){
		    	  swal({ title: "Error!",text: 'Whoops!  It looks like there was a problem submitting your request. Please try again. If the problem persists, please contact us.',type: "error",   confirmButtonText: "Close" });
		       },
		       complete: function(xhr, textStatus){
			  		 
		  		}
		    });
		// swal({   title: "Success!",   text: "Hello "+p.name+"!!! Successfully verified your "+r.network+". Enter password and proceed to Sign up!",   type: "success",   confirmButtonText: "Close" });
		hello( r.network ).logout();

		// On chrome apps we're not able to get remote images
		// This is a workaround
		if (typeof(chrome) === 'object') {
			img_xhr(label.getElementsByTagName('img')[0], p.thumbnail);
		}
	});

	
	hello('facebook').logout();
	hello('google').logout();
});


</script>

<script>
function log(s){

	 if(s.error.code!=''){
		 swal({   title: "Error!",   text: s.network +" " + s.error.message,   type: "error",   confirmButtonText: "Close" });

		 }
	//alert("log");
	//alert(s.error.code);
	//document.body.querySelector('.response').appendChild(document.createTextNode(JSON.stringify(s, true, 2)));
}
</script>

<!-- Hello.js end -->


  <!-- Slimscroll -->
    <script src="/plugins/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <!-- FastClick -->
    <script src='/plugins/fastclick/fastclick.min.js'></script>
    <!-- AdminLTE App -->
    <script src="dist/js/app.min.js" type="text/javascript"></script>
    <!-- Optionally, you can add Slimscroll and FastClick plugins.
          Both of these plugins are recommended to enhance the
          user experience. Slimscroll is required when using the
          fixed layout. -->

    <!-- iCheck -->
    <script src="/plugins/iCheck/icheck.min.js" type="text/javascript"></script>
    <script>

    $('#signinForm').on("submit",function(e){
    	  var btn = $("#btn-login");
    	  btn.button('loading');
  	  var data = {
  		      "action": "test"
  		    };
  		    data = $("#signinForm").serialize() + "&" + $.param(data);
  		    e.preventDefault();
  		 	
  		    $.ajax({
  		      type: "POST",
  		      dataType: "json",
  		      url: "/user/signinservice", //Relative or absolute path to response.php file
  		      data: data,
  		      success: function(data) {
  		        if(data['error']!=null){
  		        	$("#simpleexperrordiv").show();
      		       $("#simpleexperror").html(data["error"]);
      		    }else{
  		        	window.location.replace("/plan/testing");
  		        }
  		      },
  		    complete: function(xhr, textStatus){
		   		  btn.button('reset');
		   		}
  		    });
       
});  

    
      $(function () {
        $('input').iCheck({
          checkboxClass: 'icheckbox_square-blue',
          radioClass: 'iradio_square-blue',
          increaseArea: '20%' // optional
        });
      });
    </script>
	
	    <!-- Google Analytics -->
   <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-68102741-1', 'auto');
  ga('send', 'pageview');

</script>
  </body>
</html>
