<?php 
use Common\ActionForms\ExplorerForm;
use Common\Utilities\Constants;
use Zend\Session\SessionManager;
use Zend\Session\Container;
$session = new Container('user');
$uid=$this->uid;

if($this->avil_data=='yes'){
	$essay_data=array();
	$data=$this->essay_data;
	foreach ($data as $row){
		$essay_data=$row;
	}unset($row);
	
}
if(!isset($this->avil_data)){
	$this->avil_data='no';
}


?>



<!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper pscontentContainer">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            <i class="fa fa-file-text-o"></i> UC Essay Review
            <!-- <small>Advice from Your UCEazy Counselor</small>-->
          </h1>
          <?php  if(isset($essay_data->status)){?><label class="status" >Status : <span id="essay_status"><?php echo ucfirst($essay_data->status);?> </span></label><?php }?>
          <label class="essay_history" ><a href="#essay_history" id="show_history"> History</a> </label>
          
          
         <ol class="breadcrumb pull-right">
            <li><a href="/user/index"><i class="fa fa-dashboard"></i> Dashboard</a></li>
          <li class="active"></i> View Essay </li>
           
          </ol>
        </section>
        <section class="content">
          <div class="row">
            <div class="col-lg-6 col-lg-offset-3 col-md-12 col-sm-12 col-xs-12 ">
              <div id="generalPanel" class="box box-default box-solid">
                <div class="box-header bg-blue ">
                  <h3 class="box-title">UC Essay Review</h3>
                </div><!-- /.box-header -->
               
                <div class="box-body">
               <?php if($this->avil_data=='no'){?>
                <div class="form-group" style="margin: 2%">
                     <p class="bg-warning">No Records Found</p>
                    </div>
                  </div>
                  <?php }?>
                 <?php if($this->avil_data=='yes'){?>
                  <div class="form-group">
                    <label for="" class="col-sm-3 control-label">Essay 1</label>
                    <div class="col-xs-9 col-sm-9 col-md-9 col-lg-9 " >
                      <textarea class="form-control cusnote" rows="10" placeholder="Enter..." name="text_box1" id="text_box1"  readonly="readonly" >
                       <?php if(isset($essay_data->user_input1)){ echo html_entity_decode(trim($essay_data->user_input1)); } ?>
                      </textarea>
                      <div id="text_box1_count"></div>
                    </div>
                  </div>
                  <div class="clearfix"></div>
                  <div class="form-group" style="margin-top:15px;">
                    <label for="" class="col-sm-3 control-label">Essay 2</label>
                    <div class="col-xs-9 col-sm-9 col-md-9 col-lg-9 " >
                     <textarea class="form-control cusnote" rows="10" placeholder="Enter..." name="text_box2" id="text_box2" readonly="readonly" >
                     <?php if(isset($essay_data->user_input2)){ echo   html_entity_decode(trim($essay_data->user_input2)); } ?>
                     </textarea>
					<div id="text_box2_count"></div>
                    </div>
                  </div>                  
                  <div class="clearfix"></div>                  
                  
                    
                  
                  <hr />
                  
                  <div class="form-group" style="margin-top:15px;" >
                    <label for="" class="col-sm-3 control-label">Essay-1 Comment</label>
                    <div class="col-xs-9 col-sm-9 col-md-9 col-lg-9 " >
                      <textarea class="form-control" rows="10" placeholder="" readonly="readonly" id="review_cmt1">
                      <?php if(isset($essay_data->essay_comment1)){ echo   html_entity_decode(trim($essay_data->essay_comment1)); } ?>
                      </textarea>
                    </div>
                  </div>
                  <div class="clearfix"></div>
                  <div class="form-group" style="margin-top:15px;" >
                    <label for="" class="col-sm-3 control-label">Essay-2 Comment</label>
                    <div class="col-xs-9 col-sm-9 col-md-9 col-lg-9 " >
                      <textarea class="form-control" rows="8" placeholder="Enter ..." readonly="readonly" id="review_cmt2">
                      <?php if(isset($essay_data->essay_comment2)){ echo   html_entity_decode(trim($essay_data->essay_comment2)); } ?>
                      </textarea>
                    </div>
                  </div>
                                    
                  <div class="clearfix"></div>
                 
                 
                  <hr />
                  <div class="form-group" style="margin-top:15px;">
                    <label for="" class="col-sm-3 control-label">User Feedback about Essay Review</label>
                    <div class="col-xs-9 col-sm-9 col-md-9 col-lg-9 " >
                      <textarea class="form-control" rows="6" placeholder="We Would appreciate if you could give us feedback/commentary on our editing services."  id="feedback_text" <?php if(trim($essay_data->status)=='completed' ||trim($essay_data->status)=='submitted' ){?> readonly="readonly" <?php }?>>
                      <?php if(isset($essay_data->feedback)){ echo   html_entity_decode(trim($essay_data->feedback)); } ?>
                      </textarea>
                    </div>
                  </div>
                   
 

                  <div class="clearfix"></div>                  
                  <hr />
					<div id="errordiv" class="alert alert-danger col-sm-12"
						style="display: none;">
						<div class="info-text-container-failure ">
							<i class="fa fa-close "></i> <span class="info-text" id="errortext"> </span>
						</div>
					</div>

					<div id="page_error" class="alert alert-danger col-sm-12" style="display: none;">
						<div class="info-text-container-failure ">
							<i class="fa fa-close "></i> <span class="info-text" id="page_error_txt"> </span>
						</div>
					</div>
					<div id="successdiv" class="alert alert-success col-sm-12" 	style="display: none;">
						<div class="info-text-container-success ">
							<i class="glyphicon glyphicon-ok"></i> <span class="info-text" id="successdiv_text"></span>
						</div>
					</div>



					<div class="text-center">
                     <?php  if(isset($essay_data->status) && $essay_data->status=='reviewed'){?>
                    	<button type="button" id="essay-review-btn" value="" class="btn btn-danger pull-right" ><i class="glyphicon glyphicon-thumbs-up" >&nbsp;</i>Submit Feedback</button>                 
                     <?php }?>
                    </div>
 					<?php }?>
 					 <h5> Have a question? <a href="mailto:support@uceazy.com" style="color:#3c8dbc"> support@uceazy.com</a> </h5>
                </div>
               
              </div>
            </div>
          </div>
		
		<input type="hidden" id="uid" name="uid" value="<?php echo $uid;?>" >
        <input type="hidden" id="pay_row_id" name="pay_row_id" value="<?php echo $essay_data->buy_id;?>" >
        <input type="hidden" id="essay_id"  value="<?php echo $essay_data->essay_id;?>" >
          
      </section>
    </div> 
    
    <div class="modal fade" id="essay_history" tabindex="-1" role="dialog"  aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
            
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Essay Service History</h4>
                </div>
            
                <div class="modal-body">
                     
                    	
                   <table class="table table-bordered courseTable" id="essay_table">
					<thead>
						<tr>
							<th>S.No</th>
							<th>Services</th>
							<th>Submitted On</th>
							<th>Reviewed On</th>
							<th>Cost</th>	
							<th>Status</th>
							<th>Action</th>
						</tr>
					</thead>
					<tbody></tbody>
				</table>	
                    	
                    	
                    	
                    		
                    	
                   
                </div>
                
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    
                </div>
            </div>
        </div>
    </div>
    
<!-- REQUIRED JS SCRIPTS -->

    <!-- jQuery 2.1.4 -->
    <script src="/plugins/jQuery/jQuery-2.1.4.min.js"></script>
    <!-- Bootstrap 3.3.2 JS -->
    <script src="/dist/js/bootstrap.min.js" type="text/javascript"></script>
    <!-- InputMask -->
    <script src="/plugins/input-mask/jquery.inputmask.js" type="text/javascript"></script>
    <script src="/plugins/input-mask/jquery.inputmask.date.extensions.js" type="text/javascript"></script>
    <script src="/plugins/input-mask/jquery.inputmask.extensions.js" type="text/javascript"></script>

    <!-- ChartJS 1.0.1 -->
    <script src="/plugins/chartjs/Chart.min.js" type="text/javascript"></script>

    <!-- Slimscroll -->
    <script src="/plugins/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <!-- FastClick -->
    <script src='/plugins/fastclick/fastclick.min.js'></script>
    <!-- AdminLTE App -->
    <script src="/dist/js/app.min.js" type="text/javascript"></script>
    <!-- Custom Script -->
    <script src="/dist/js/custom.js" type="text/javascript"></script>

    <!-- jquery scrollbar Script -->
    <script src="/dist/js/jquery.scrollbar.min.js" type="text/javascript"></script>
	<script src="http://bootboxjs.com/bootbox.js"></script>
	<script src="/dist/js/buyService.js" type="text/javascript"></script>

<!-- Feedbacify -->
<script>

($(function() {


		
//onload trim the text bos values
		var t1=$.trim($("#text_box1").val())
		var t2=$.trim($("#text_box2").val())
		var t3=$.trim($("#review_cmt1").val())
		var t4=$.trim($("#review_cmt2").val())
			
		$("#text_box1").val(t1);
		$("#text_box2").val(t2);
		$("#review_cmt1").val(t3);
		$("#review_cmt2").val(t4); 	
    	        
}));
	
	

	

$(document).on('click', "#essay-review-btn", function(e){
	e.preventDefault();
	var self=this;
	var feedback_text=$("#feedback_text").val();
	var pay_row_id =$("#pay_row_id").val();
	var mode="feedback_submit";	
	var essay_id=$("#essay_id").val();

	if(feedback_text.length>1){		
		var btn = $(self);
		btn.button('loading'); 
		   var data = {"mode" : mode,feedback_text:feedback_text,pay_row_id:pay_row_id,essay_id:essay_id};
				data=$.param(data);
			    $.ajax({
			      type: "POST",
			      dataType: "json",
			      url: "/buyservice/updateEssayFeedback", 
			      data: data,
			      success: function(data) {
		  		    if(data['status']>0){
		  		    	$("#essay_status").html(data['essay_status']);    	  		    	
					$('#successdiv').show();
					$('#successdiv_text').html("Your information has been saved.");
					setTimeout(function(){$('#successdiv').hide();},5000);
					btn.button('reset');
					$("#feedback_text").prop("disabled", true);					
					$(btn).remove();	
					 
					
				}else{
						 $('#errordiv').show();
						 $('#errortext').html("Oops!  Looks like something went wrong.  Please try again later");
						 setTimeout(function(){$('#errordiv').hide();},5000);
						 btn.button('reset');
	 		       }
			      },
			      error: function(xhr, textStatus, errorThrown){
			          alert('Oops!  Looks like something went wrong');
			        btn.button('reset');
			         
			       },
		  		    complete: function(xhr, textStatus){
			   		 
			   		}
			    });
			    return false;
	    
	 
	}
		else{
			$('#errordiv').show();
			 $('#errortext').html("Please enter your feedback");
			 setTimeout(function(){$('#errordiv').hide();},5000);
			 
	    }

});

	



$("#essay-save-btn").click(function(e){
	e.preventDefault();
	
	$("#clicked_btn").val("save");	
	var box1_data=$("#text_box1").val();
	var box2_data=$("#text_box2").val();
	var uid=$("#uid").val();
	var pay_row_id =$("#pay_row_id").val();
	var mode=$("#data_mode").val();
	var clicked_btn=$("#clicked_btn").val();
	var essay_id=$("#essay_id").val();
	
	
	var btn = $("#essay-save-btn");
	btn.button('loading');
	var data = {"mode" : mode,box1_data:box1_data,box2_data:box2_data,uid:uid,pay_row_id:pay_row_id,clicked_btn:clicked_btn,essay_id:essay_id};
	data=$.param(data);
	$.ajax({
	      type: "POST",
	      dataType: "json",
	      url: "/buyservice/essay", 
	      data: data,
	      success: function(data) {
  		  	if(data['status']>0){
  		  	$("#essay_status").html(data['essay_status']); 	
  		  		$('#successdiv').show();	
  		  		$('#successdiv_text').html("Your information has been saved.");  		  		
				setTimeout(function(){$('#successdiv').hide();},5000);
				btn.button('reset');				
			}else{
				$('#errordiv').show();
					 $('#errortext').html("Oops!  Looks like something went wrong.  Please try again later");
					 setTimeout(function(){$('#errordiv').hide();},5000);
					 btn.button('reset');
	 		       }
	      },
	      error: function(xhr, textStatus, errorThrown){
			     alert('Oops!  Looks like something went wrong');
			     btn.button('reset');
		 },
		 complete: function(xhr, textStatus){
			}
		 });
	return false; 
	
});

	
$("#show_history").click(function(e){
	e.preventDefault();		
	get_essay_history("essay_table","essay_history");	
	
});

</script>

<style>
.status{
    float: left;
    background: transparent;
    margin-top: 0px;
    margin-bottom: 0;
    font-size: 12px;
    padding: 5px 13px;
    position: absolute;
    top: 15px;
    left: 20%;    
    border-radius: 2px;
}
.essay_history{
	float: right;
    background: transparent;
    margin-top: 0px;
    margin-bottom: 0;
    font-size: 12px;
    padding: 5px 13px;
    position: absolute;
    top: 15px;
    right: 20%;    
    border-radius: 2px;

}
</style>


<!-- Feedbackify -->  
<script type="text/javascript">
var fby = fby || [];
fby.push(['showTab', {id: '9871', position: 'right', color: '#EB0000'}]);

(function () {
   var f = document.createElement('script'); f.type = 'text/javascript'; f.async = true;
   f.src = '//cdn.feedbackify.com/f.js';
   var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(f, s);
})();
</script>  


    