
<?php
$flag ='';
$res=$this->result; 
?>

<form class="form-horizontal" id="costform">
   <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper pscontentContainer">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            <i class="fa fa-dollar"></i> Costs
            <small>Calculating How Much College Costs</small>
          </h1>
         
        </section>
        <!-- Main content -->
        <section class="content">
        <!-- Cost Form -->
          <div class="row">
          <!-- Right side content -->
            <div class="col-lg-3 col-lg-push-9 col-md-12 col-sm-12 col-xs-12 rightSideContainer">
                <div class="box box-warning ">
                    <div class="box-header with-border">
                      <h3 class="box-title"><i class="fa fa-file-video-o"></i> Hear from An Expert</h3>
                    </div>
                  <div class="box-body" >
                    <!-- <div class="embed-responsive embed-responsive-16by9">
                      <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/sqpw3NynsTE"></iframe>
                    </div>-->
                    <div id="myCarousel" class="carousel slide" data-interval="false">
                      <!-- <ol class="carousel-indicators">
                        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                        <li data-target="#myCarousel" data-slide-to="1" class=""></li>
                      </ol>-->
                      <div class="carousel-inner">
                        <div class="item active">
                          <div class="embed-responsive embed-responsive-16by9">
                            <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/ChM8RkeYuaE?showinfo=0&amp;" allowfullscreen></iframe>
                          </div>
                        </div>
                        <div class="item">
                          <div class="embed-responsive embed-responsive-16by9">
                            <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/YOjbaLpfkEw?showinfo=0&amp;" allowfullscreen></iframe>
                          </div>
                        </div>
                      </div>
                      <!-- <a class="left carousel-control" href="#myCarousel" data-slide="prev"><i class="fa fa-chevron-left"></i></a>
                      <a class="right carousel-control" href="#myCarousel" data-slide="next"><i class="fa fa-chevron-right"></i></a>-->

                      <!-- Controls buttons -->
                      <div class="videoPagnination" >
                          <input type = "button" class = "btn slide-one active" value = "1">
                          <input type = "button" class = "btn slide-two" value = "2">            
                      </div>
                    </div>
                  
                  </div><!-- /.box-body -->
                </div><!-- /.box -->           
               
                <div id="myAffix" class="box box-default visible-lg" data-spy="affix" data-offset-top="300">
                    <!--<div class="box-header with-border">
                      
                    </div>
                  <div class="box-body">
                       
				</div><!-- /.box-body -->
                </div><!-- /.box -->

                <!-- social media -->
                <div id="myAffix1" class="box box-solid visible-lg" data-spy="affix" data-offset-top="300">
                    <div class="box-header ">
                      <h3 class="box-title"><i class="fa fa-share-alt"></i> Follow Us</h3>
                      <div class=" pull-right " >
                        <div  class="fixedBtn"><a href="https://www.facebook.com/askuceazy" class="bg-facebook" title="Facebook" target="_blank"><i class="fa fa-facebook"></i></a></div>
                        <div class="fixedBtn"><a href="https://twitter.com/Uaskuceazy?lang=en" class="bg-twitter" target="_blank" title="Twitter"><i class="fa fa-twitter"></i></a></div>
                        <div class="fixedBtn"><a href="https://www.linkedin.com/company/uceazy" class="bg-linkedin" target="_blank" title="Linkedin"><i class="fa fa-linkedin"></i></a></div>
                        <!-- <div class="fixedBtn"><a href="#" class="bg-google-plus"><i class="fa fa-google-plus"></i></a></div>
                        <div class="fixedBtn"><a href="#" class="bg-instagram"><i class="fa fa-instagram"></i></a></div>
                        <div class="fixedBtn"><a href="#" class="bg-pinterest"><i class="fa fa-pinterest"></i></a></div>-->
                      </div>  
                    </div>
                </div>
            </div>
            <!-- ./Right side content -->            
            

            <div class="col-lg-9 col-lg-pull-3 col-md-12 col-sm-12 col-xs-12">
             

              <div class="row " >

                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 " style="float:left">
                    <div class="info-box bg-blue ">
                    <span class="info-box-icon"><i class="fa fa-dollar "></i></span>
                    <div class="info-box-content">
                      <span class="info-box-text" id="maincost">Total cost per year - CSU/UC</span>
                      <span class="info-box-number"><h1 id="maincostval">0</h1></span>
                      
                      
                    </div><!-- /.info-box-content -->
                  </div>
                </div>
              
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 ">
                  <div class="info-box bg-blue">
                    <span class="info-box-icon"><i class="fa fa-dollar "></i></span>
                    <div class="info-box-content">
                      <span class="info-box-text" id="commcost">Total Saving/Discount - Free Lunch or Fee waiver</span>
                      <span class="info-box-number"><h1  id="commcostval">0</h1></span>
                    </div>
                  </div>    
                  
                </div><!-- /.info-box-content -->
              </div>

              <div class="box box-default box-solid">
                <div class="box-header bg-olive-active">
                  <h3 class="box-title">Please enter your information</h3>
                </div><!-- /.box-header -->
                <!-- form start -->


                  <div class="box-body">
                  <!-- Potential Discounts -->
                    <!-- Application Costs -->
                    <div class="box box-default box-solid">
                      <div class="box-header bg-olive" data-widget="collapse" data-collapse="custom" >
                        <h3 class="box-title">Eligibility for Potential Discounts</h3>
                        <div class="box-tools pull-right">
                          <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                        </div><!-- /.box-tools -->
                      </div><!-- /.box-header -->
                      <div class="box-body">
                        <div class="form-group">
                          <label for="currentState" class="col-sm-3 control-label">Free/Reduced lunch</label>
                          <div class="col-sm-6">
                            <div class="radio" >
                                <label class="radio-inline" >
                                  <input type="radio" id="freelunchyes" name="freelunch" value="1" <?php if(isset($res['freeLunch']) && $res['freeLunch']=='1'){?> checked="checked" <?php }?>>
                                  Yes
                                </label>
                                <label class="radio-inline">
                                  <input type="radio" name="freelunch" value="0" <?php if(isset($res['freeLunch']) && $res['freeLunch']=='0'){?> checked="checked" <?php }?>>
                                  No
                                </label>
                                <label class="radio-inline">
                                  <input type="radio" name="freelunch" id="freelunchdiscloseid" value="-1" <?php if(isset($res['freeLunch']) && $res['freeLunch']=='-1'){?> checked="checked" <?php }?>>
                                  Would not like to Disclose
                                </label>
                             </div>
                          </div>
                          <div class="tooltipContent"> <a href="#" data-toggle="tooltip" class="tip-right" data-original-title="Unsure if you qualify?  For the state you selected above, a family of 2 qualifies if they make $29,471 or less a year.  A family of 3, $37,167.  A family of 4, $44,863."><i class="fa fa-info-circle "></i></a> </div>
                        </div>
                        
                        <div class="form-group">
                          <label for="currentState" class="col-sm-3 control-label">Fee Waivers</label>
                          <div class="col-sm-6">
                            <div class="radio" >
                                <label class="radio-inline" >
                                  <input type="radio" id="freewaiversyes" name="freewaivers" value="1" <?php if(isset($res['feeWaivers']) && $res['feeWaivers']=='1'){?> checked="checked" <?php }?> >
                                  Yes
                                </label>
                                <label class="radio-inline">
                                  <input type="radio" name="freewaivers" value="0" <?php if(isset($res['feeWaivers']) && $res['feeWaivers']=='0'){?> checked="checked" <?php }?> >
                                  No
                                </label>
                                <label class="radio-inline">
                                  <input type="radio" name="freewaivers" value="-1" <?php if(isset($res['feeWaivers']) && $res['feeWaivers']=='-1'){?> checked="checked" <?php }?>>
                                  Would not like to Disclose
                                </label>
                             </div>
                          </div>
                          <div class="tooltipContent"> <a href="#" data-toggle="tooltip" class="tip-right" data-original-title="If you do not qualify for free/reduced lunch, you can still qualify for a fee waiver if:  1) You are in a program that aids low-income students (e.g. Federal TRIO programs like Upward Bound), 2) Your Family receives public assistance, 3) You lives in federally subsidized public housing, foster home, or are homeless, 4) An orphan/ward of the state"><i class="fa fa-info-circle "></i>
                          </a> </div>
                        </div>

                        

                      </div><!-- /.box-body -->
                    </div><!-- /.widget box -->

                    <!-- Application Costs -->
                    <div class="box box-default box-solid collapsed-box">
                      <div class="box-header bg-olive" data-widget="collapse" data-collapse="custom" >
                        <h3 class="box-title">Application Costs</h3>
                        <div class="box-tools pull-right">
                          <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
                        </div><!-- /.box-tools -->
                      </div><!-- /.box-header -->
                      <div class="box-body">
                        <div class="form-group">
                          <label for="" class="col-sm-3 control-label"># of UC applications</label>
                          <div class="col-sm-6">
                            <input type="number" id="ucappcount" name="ucappcount" value="<?php echo isset($res['numOfUC'])?$res['numOfUC']:'0';?>" class="form-control" min="0" max="8" data-validate="yes" data-rules="type:numeric,max_length:1,min:0,max:8">
                          </div>
                          <div class="tooltipContent"> <a href="#" data-toggle="tooltip" class="tip-right" data-original-title="This is the number of UC colleges you are planning on applying to."><i class="fa fa-info-circle "></i></a> </div>
                        </div>
                        
                        <div class="form-group">
                          <label for="" class="col-sm-3 control-label"># of CSU applications</label>
                          <div class="col-sm-6">
                            <input type="number" id="csuappcount" name="csuappcount" value="<?php echo isset($res['numOfCSU'])?$res['numOfCSU']:"0";?>" class="form-control" min="0" max="8"  data-validate="yes" data-rules="type:numeric,max_length:1,min:0,max:8">  
                          </div>
                          <div class="tooltipContent"> <a href="#" data-toggle="tooltip" class="tip-right" data-original-title="This is the number of CSU colleges you are planning on applying to."><i class="fa fa-info-circle "></i>
                          </a> </div>
                        </div>
                        <hr />

                        <div class="form-group" >
                          <label for="" class="col-sm-3 control-label">Total Application Costs</label>
                          <div class="col-md-2" >
                            <div class="input-group ">
                              <div class="input-group-addon">
                                <i class="fa fa-dollar"></i>
                              </div>
                              <input type="text" name="totalappcost"  id="totalappcost" class="form-control" value="0" readonly="readonly"/>
                              
                              <input type="hidden" name="totalappcostuc"  id="totalappcostuc" class="form-control" value="0"/>
                              <input type="hidden" name="totalappcostcsu"  id="totalappcostcsu" class="form-control" value="0"/>
							  
							  <input type="hidden" name="discounttotalappcostuc"  id="discounttotalappcostuc" class="form-control" value="0"/>
                              <input type="hidden" name="discounttotalappcostcsu"  id="discounttotalappcostcsu" class="form-control" value="0"/>
                              
                            </div><!-- /.input group -->
                          </div>
                        </div>

                        
                      </div><!-- /.box-body -->
                    </div><!-- /.widget box -->

                    <!-- Standardized Testing Costs -->
                    <div class="box box-default box-solid collapsed-box">
                      <div class="box-header bg-olive" data-widget="collapse" data-collapse="custom" >
                        <h3 class="box-title">Standardized Testing Costs</h3>
                        <div class="box-tools pull-right">
                          <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
                        </div><!-- /.box-tools -->
                      </div><!-- /.box-header -->
                      <div class="box-body">
                        <div class="form-group">
                          <label for="" class="col-sm-3 control-label"># of times take SAT</label>
                          <div class="col-sm-6">
                            <input type="number" id="satcount" name="satcount" value="<?php echo isset($res['numOfSAT'])?$res['numOfSAT']:"0";?>" class="form-control" min="0" max="4" data-validate="yes" data-rules="type:numeric,max_length:1,min:0,max:4">
                          </div>
                          <div class="tooltipContent"> <a href="#" data-toggle="tooltip" class="tip-right" data-original-title="This is the number of SAT's you plan on taking."><i class="fa fa-info-circle "></i></a> </div>
                        </div>
                        
                        <div class="form-group">
                          <label for="" class="col-sm-3 control-label"># of times take ACT</label>
                          <div class="col-sm-6">
                            <input type="number" id="actcount" name="actcount" value="<?php echo isset($res['numOfACT'])?$res['numOfACT']:"0";?>" class="form-control" min="0" max="4" data-validate="yes" data-rules="type:numeric,max_length:1,min:0,max:4">
                          </div>
                          <div class="tooltipContent"> <a href="#" data-toggle="tooltip" class="tip-right" data-original-title="This is the number of ACT's you plan on taking."><i class="fa fa-info-circle "></i>
                          </a> </div>
                        </div>

                        <div class="form-group">
                          <label for="" class="col-sm-3 control-label"># of times take SAT Subject Exams</label>
                          <div class="col-sm-6">
                            <input type="number" id="satsubcount" name="satsubcount" value="<?php echo isset($res['numOfSubjectSAT'])?$res['numOfSubjectSAT']:"0";?>" class="form-control" min="0" max="10" data-validate="yes" data-rules="type:numeric,max_length:2,min:0,max:10">
                          </div>
                          <div class="tooltipContent"> <a href="#" data-toggle="tooltip" class="tip-right" data-original-title="This is the number of SAT Subject Tests you plan on taking."><i class="fa fa-info-circle "></i>
                          </a> </div>
                        </div>

                        <div class="form-group">
                          <label for="" class="col-sm-3 control-label"># of Test Scores to Send to Colleges</label>
                          <div class="col-sm-6">
							<input type="number" id="testscorecount" name="testscorecount" value="<?php echo isset($res['sendingStdTestNum'])?$res['sendingStdTestNum']:"0";?>" class="form-control" min="0" max="4" data-validate="yes" data-rules="type:numeric,max_length:1,min:0,max:4">
                          </div>
                           <div class="tooltipContent"> <a href="#" data-toggle="tooltip" class="tip-right" data-original-title="If you apply to multiple UC's, you only need to send test scores to 1 campus and they will share it with the others UC's you are applying to.  If you apply to multiple CSU's, the SAT has a special CSUMentor code (3594) that allows you to share your SAT scores with multiple campuses.  For the CSU's and the ACT, you will send it to one campus and can share the scores with other campuses through the CSU's Score Manager."><i class="fa fa-info-circle "></i>
                          </a> </div>

                        </div>

                         <hr />

                        <div class="form-group" >
                          <label for="" class="col-sm-3 control-label">Total Testing Costs</label>
                          <div class="col-md-2" >
                            <div class="input-group ">
                              <div class="input-group-addon">
                                <i class="fa fa-dollar"></i>
                              </div>
                              <input type="text" name="totaltestingcost" value="0" id="totaltestingcost" class="form-control" readonly="readonly"/>
                              
                              <input type="hidden" name="testscorecounttmp" id="testscorecounttmp" value="0">
                              <input type="hidden" name="satsubcounttmp" id="satsubcounttmp" value="0">
                              <input type="hidden" name="actcounttmp" id="actcounttmp" value="0">
                              <input type="hidden" name="satcounttmp" id="satcounttmp" value="0">
                              
                              <input type="hidden" name="discounttestscorecounttmp" id="discounttestscorecounttmp" value="0">
                              <input type="hidden" name="discountsatsubcounttmp" id="discountsatsubcounttmp" value="0">
                              <input type="hidden" name="discountactcounttmp" id="discountactcounttmp" value="0">
                              <input type="hidden" name="discountsatcounttmp" id="discountsatcounttmp" value="0">



                              
                            </div><!-- /.input group -->
                          </div>
                        </div>

                      </div><!-- /.box-body -->
                    </div><!-- /.widget box -->

                    <!-- Attending College -->
                    <div class="box box-default box-solid collapsed-box">
                      <div class="box-header bg-olive " data-widget="collapse" data-collapse="custom" >
                          <h3 class="box-title">Costs for Attending College</h3>
                          <div class="box-tools pull-right">
                            <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
                          </div><!-- /.box-tools -->
                        </div><!-- /.box-header -->
						
                        <div class="box-body">
						            <!-- <div class="form-group">
                            <label for="currentState" class="col-sm-3 control-label">School-Based Transcript Fees</label>
                          <div class="col-sm-6">
                          <div class="input-group ">
                                <div class="input-group-addon">
                                  <i class="fa fa-dollar"></i>
                                </div>
							<input type="number" id="schooltransfee" name="schooltransfee" value="<?php echo isset($res['costOfSchoolTranscript'])?$res['costOfSchoolTranscript']:"0";?>" class="form-control" min="0" max="10" data-validate="yes" data-rules="type:numeric,max_length:2,min:0,max:10">
              </div>
                          </div>
							<div class="tooltipContent"> <a href="#" data-toggle="tooltip" class="tip-right" data-original-title="Some high schools charge for transcripts to be sent"><i class="fa fa-info-circle "></i>
                            </a> </div>
                          </div> -->
                          <div class="form-group">
                            <label for="currentState" class="col-sm-3 control-label">Where Will You Live?</label>
                            <div class="col-sm-6">
                              <select name="livewith" id="livewith" class="form-control">
                                  <option value="-1" >Select</option>
                                  <option value="1" <?php if(isset($res['residency']) && $res['residency']=='1'){?> selected="selected" <?php }?>>Resident Living with Family/Relatives</option>
                                  <option value="2" <?php if(isset($res['residency']) && $res['residency']=='2'){?> selected="selected" <?php }?>>Resident Living on Campus</option>
                                  <option value="3" <?php if(isset($res['residency']) && $res['residency']=='3'){?> selected="selected" <?php }?>>Resident Living off Campus</option>
                            
                                  <option value="4" <?php if(isset($res['residency']) && $res['residency']=='4'){?> selected="selected" <?php }?>>Non Resident Living with Family/Relatives</option>
                                  <option value="5" <?php if(isset($res['residency']) && $res['residency']=='5'){?> selected="selected" <?php }?>>Non Resident Living on Campus</option>
                                  <option value="6" <?php if(isset($res['residency']) && $res['residency']=='6'){?> selected="selected" <?php }?>>Non Resident Living off Campus</option>
                            
                            
                              </select>
                            </div>
                          <div class="tooltipContent"> <a href="#" data-toggle="tooltip" class="tip-right" data-original-title="This helps UCEazy calculate your potential housing costs."><i class="fa fa-info-circle "></i>
                          </a> </div>
                        </div>
                          <div class="form-group">
                            <label for="currentState" class="col-sm-3 control-label">Cost of Attendance</label>
                            <div class="col-sm-6">
                              <div class="radio" >
                                  <label class="radio-inline" >
                                    <input type="radio" name="coa" value="UC" class="coacustom" <?php if(isset($res['costOfUCAttendance'])&&$res['costOfUCAttendance']>0){ $flag=1;?> checked="checked" <?php }?>>
                                    UC
                                  </label>
                                  <label class="radio-inline">
                                    <input type="radio" name="coa" value="CSU" class="coacustom" <?php if(isset($res['costOfCSUAttendance'])&&$res['costOfCSUAttendance']>0){ $flag=2; ?> checked="checked" <?php }?>>
                                    CSU
                                  </label>
                               </div>

                            </div>
                            <div class="tooltipContent"> <a href="#" data-toggle="tooltip" class="tip-right" data-original-title="This amount includes Tuition, Fees, Room/Board, Books/Supplies, Transportation, and Misc Personal Expenses"><i class="fa fa-info-circle "></i></a> </div>
                          </div>


                          
                          <div class="form-group" <?php if($flag==1){?> <?php }else{?>style="display: none;" <?php }?> id="UCSHOW">
                            <label for="currentState" class="col-sm-3 control-label">Cost of Attendance - UC's</label>
                            <div class="col-sm-6">
                              <div class="input-group ">
                                <div class="input-group-addon">
                                  <i class="fa fa-dollar"></i>
                                </div>
                                <input type="text" id="coauc" name="coauc"  value="<?php echo isset($res['costOfUCAttendance'])?$res['costOfUCAttendance']:"0";?>" class="form-control" readonly="readonly"/>
                              </div>
                            </div>
                            
                          </div>
                          
                          <div class="form-group"  <?php if($flag==2){?> <?php }else{?>style="display: none;" <?php }?>  id="CSUSHOW">
                            <label for="currentState" class="col-sm-3 control-label">Cost of Attendance - CSU's</label>
                            <div class="col-sm-6">
                            <div class="input-group ">
                                <div class="input-group-addon">
                                  <i class="fa fa-dollar"></i>
                                </div>
                              <input type="text" id="coacsu" name="coacsu" value="<?php echo isset($res['costOfCSUAttendance'])?$res['costOfCSUAttendance']:"0";?>" class="form-control" readonly="readonly"/>
                              </div>
                            </div>
            
                            <input type="hidden" name="residentStayingWithRelativesUC" id="residentStayingWithRelativesUC" value="25644">
                            <input type="hidden" name="residentStayingOnCampusUC" id="residentStayingOnCampusUC" value="33167">
                            <input type="hidden" name="residentStayingOffCampusUC" id="residentStayingOffCampusUC" value="32184">
                            <input type="hidden" name="nonresidentStayingWithRelativesUC" id="nonresidentStayingWithRelativesUC" value="49644">
                            <input type="hidden" name="nonresidentStayingOnCampusUC" id="nonresidentStayingOnCampusUC" value="57167">
                            <input type="hidden" name="nonresidentStayingOffCampusUC" id="nonresidentStayingOffCampusUC" value="56184">
                            
                            
                            <input type="hidden" name="residentStayingWithRelativesCSU" id="residentStayingWithRelativesCSU" value="15735">
                            <input type="hidden" name="residentStayingOnCampusCSU" id="residentStayingOnCampusCSU" value="23029">
                            <input type="hidden" name="residentStayingOffCampusCSU" id="residentStayingOffCampusCSU" value="23407">
                            <input type="hidden" name="nonresidentStayingWithRelativesCSU" id="nonresidentStayingWithRelativesCSU" value="24735">
                            <input type="hidden" name="nonresidentStayingOnCampusCSU" id="nonresidentStayingOnCampusCSU" value="32029">
                            <input type="hidden" name="nonresidentStayingOffCampusCSU" id="nonresidentStayingOffCampusCSU" value="32407">
                            
                            <input type="hidden" name="discountcoacsu" id="discountcoacsu" value="0">
                            <input type="hidden" name="discountcoauc" id="discountcoauc" value="0">
                            
                          </div>

                        </div><!-- /.box-body -->
                      </div><!-- /.widget box -->
                    
                    <!-- Other Cost -->
                    </div>
                  <div class="box-footer">
					<div id="page_error" class="alert alert-danger col-sm-12" style="display:none" >
						<div class="info-text-container-failure ">
							<i class="fa fa-close "></i> 
							<span class="info-text" id=""> Please enter a valid input</span>
						</div>
					</div>
					
				<div class="alert alert-success" id="success" role="alert" style="display: none;">
                      <h4 id=""><i class="icon fa fa-check "></i>
                      <span class="info-text" id="successtext">
                    </span>
                      </h4>
                 </div>
                 
                 <div class="alert alert-error" id="error" role="alert" style="display: none;">
                      <h4 id=""><i class="icon fa fa-check "></i>
                      <span class="info-text" id="errortext">
                    </span>
                      </h4>
                 </div>
                 
                  </div><!-- /.box-footer -->
               
              </div><!-- /.box -->
                
            </div>
            

            
          </div><!-- /.row -->

          <div class="clearfix"></div>
          <!-- My Notes for devices -->
          <div class="rightSideContainer">
            <div id="myAffix" class="box box-default hidden-lg" >
                    <div class="box-header with-border">
                      <h3 class="box-title"><i class="fa fa-pencil"></i> My Notes</h3>
                    </div>
                  <div class="box-body">
                        <textarea class="form-control cusnote" rows="3" placeholder="Coming Soon..." name="note2" id="note2" readonly="readonly"><?php if(isset($res['notes'][0])){ echo $res['notes'][0];}?></textarea>
                        <button class="btn btn-default marginTop"  id="savenote" disabled="true">Save My Notes </button>
                        <input type="hidden" name="note"  id="note" value="<?php if(isset($res['notes'][0])){ echo $res['notes'][0];}?>" />
                  </div><!-- /.box-body -->
                </div><!-- /.box -->
           </div>
        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->

      <!-- Main Footer -->
    
    </div><!-- ./wrapper -->

<span id="hide" ></span>
    <div class="modal fade" id="success" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header btn-danger">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title " id="myModalLabel">Success</h4>
	      </div>
	      <div class="modal-body" id="modalsuccessbody">
	        Your Cost information has been saved into our datastore.
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	        <!-- <button type="button" class="btn btn-primary">Save changes</button>-->
	      </div>
	    </div>
	  </div>
	</div>
      
       <div class="modal fade" id="failure" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header btn-danger">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title " id="myModalLabel">Failure</h4>
	      </div>
	      <div class="modal-body" id="modalfailbody">
	        Oops!  Looks like something went wrong.  Please try again later.
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	        <!-- <button type="button" class="btn btn-primary">Save changes</button>-->
	      </div>
	    </div>
	  </div>
	</div>
	
	</form>
    <!-- REQUIRED JS SCRIPTS -->

    <!-- jQuery 2.1.4 -->
    <script src="/plugins/jQuery/jQuery-2.1.4.min.js"></script>
    <!-- Bootstrap 3.3.2 JS -->
    <script src="/dist/js/bootstrap.min.js" type="text/javascript"></script>
    <!-- InputMask -->
    <script src="/plugins/input-mask/jquery.inputmask.js" type="text/javascript"></script>
    <script src="/plugins/input-mask/jquery.inputmask.date.extensions.js" type="text/javascript"></script>
    <script src="/plugins/input-mask/jquery.inputmask.extensions.js" type="text/javascript"></script>

    <!-- ChartJS 1.0.1 -->
    <script src="/plugins/chartjs/Chart.min.js" type="text/javascript"></script>

	  <!-- Slimscroll -->
    <script src="/plugins/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <!-- FastClick -->
    <script src='/plugins/fastclick/fastclick.min.js'></script>
    <!-- AdminLTE App -->
    <script src="/dist/js/app.min.js" type="text/javascript"></script>
    <!-- Custom Script -->
    <script src="/dist/js/custom.js" type="text/javascript"></script>

    <!-- jquery scrollbar Script -->
    <script src="/dist/js/jquery.scrollbar.min.js" type="text/javascript"></script>
    
     <!-- custom validation Script -->
	<script src="/dist/js/validation.js"></script>

<script>



var calcCOA =  function(evalue){
	$('#CSUSHOW').hide();
	$('#UCSHOW').hide();
	$('#'+evalue+'SHOW').show();
	var liveVAL=parseInt($('#livewith option:selected').val());
	var liveCOST = 0;
	if(evalue=='CSU'){
	if(liveVAL==1){
		liveCOST=$('#residentStayingWithRelativesCSU').val();
	}else if(liveVAL==2){
		liveCOST=$('#residentStayingOnCampusCSU').val();
	}else if(liveVAL==3){
		liveCOST=$('#residentStayingOffCampusCSU').val();
	}else if(liveVAL==4){
		liveCOST=$('#nonresidentStayingWithRelativesCSU').val();
	}else if(liveVAL==5){
		liveCOST=$('#nonresidentStayingOnCampusCSU').val();
	}else if(liveVAL==6){
		liveCOST=$('#nonresidentStayingOffCampusCSU').val();
	}
	}else if(evalue=='UC'){
		if(liveVAL==1){
			liveCOST=$('#residentStayingWithRelativesUC').val();
		}else if(liveVAL==2){
			liveCOST=$('#residentStayingOnCampusUC').val();
		}else if(liveVAL==3){
			liveCOST=$('#residentStayingOffCampusUC').val();
		}else if(liveVAL==4){
			liveCOST=$('#nonresidentStayingWithRelativesUC').val();
		}else if(liveVAL==5){
			liveCOST=$('#nonresidentStayingOnCampusUC').val();
		}else if(liveVAL==6){
			liveCOST=$('#nonresidentStayingOffCampusUC').val();
		}
	}

	

	
	if(evalue=='CSU'){
		if($("#freelunchyes").is(':checked') || $("#freewaiversyes").is(':checked') ){
		$('#coacsu').val(liveCOST-5472);
		$('#coauc').val('0');

		$('#discountcoacsu').val(liveCOST);
		$('#discountcoauc').val('0');

		$('#maincost').html('Total Cost Per Year - ' + evalue);
		//$('#maincostval').html((liveCOST-1500+totaltesting+totalAppCost+schooltransfee));
		}else{
		
			$('#coacsu').val(liveCOST);
			$('#coauc').val('0');
			$('#maincost').html('Total Cost Per Year - ' + evalue);
		//	$('#maincostval').html((liveCOST+totaltesting+totalAppCost+schooltransfee));
		}
	}else if (evalue=='UC'){
		if($("#freelunchyes").is(':checked') || $("#freewaiversyes").is(':checked') ){
		$('#coauc').val(liveCOST-14000);
		$('#coacsu').val('0');
		
		$('#discountcoauc').val(liveCOST);
		$('#discountcoacsu').val('0');
		
		$('#maincost').html('Total Cost Per Year - ' + evalue);
		//$('#maincostval').html((liveCOST-1500+totaltesting+totalAppCost+schooltransfee));
		}else{
			$('#coauc').val(liveCOST);
			$('#coacsu').val('0');
			$('#maincost').html('Total Cost Per Year - ' + evalue);
			//$('#maincostval').html((liveCOST+totaltesting+totalAppCost+schooltransfee));
		}
		
	}
	
}


/*var calcOtherCost=function(eventValue){
	var fval = 0;
	var val=eventValue;
	var liveVAL=$('#livewith option:selected').val();
	
	if(val=="truecsu"){
	
 		if(liveVAL==2){
 			if($("#freelunchyes").is(':checked') || $("#freewaiversyes").is(':checked') ){
 	 			fval=19302-1500;
 			}else{
 				fval=19302;
 			}
     	} else{
     		if($("#freelunchyes").is(':checked') || $("#freewaiversyes").is(':checked') ){
     			fval=12300-1500;
     		}else{
     			fval=12300;
     		}
     		
        }
	
	}else{
		fval=0;
	}


	if(fval<0){
		fval=0;
	}
	
	$('#totalothercostuc').val(fval);

	var val1= parseInt($('#totalothercostuc').val());

	//$('#commcostval').val(val1);
	$('#totalothercost').val(val1);
	
}*/

      

var calcSATCNTTmp = function(eventValue){
	var fval = 0;
	var val=eventValue;
 		if($("#freelunchyes").is(':checked')  || $("#freewaiversyes").is(':checked')){
			tempval = ((val)*54.50);
			$('#discountsatcounttmp').val(tempval);
 	 		if(val>2){
 				fval = ((val-2)*54.50);
 	 		}
 			else{
				fval=0;
 	 			}
     	} else{
     		fval = ((val)*54.50);
        }
	if(fval<0){
		fval=0;
	}
	
	$('#satcounttmp').val(fval);
}

var calcACTTmp = function(evalue){

	var fval = 0;
	var val=evalue;
 		if($("#freelunchyes").is(':checked') || $("#freewaiversyes").is(':checked') ){
			
 	 		$('#discountactcounttmp').val(((val)*54.50));
			
			if(val>2){
 				fval = ((val-2)*54.50);
 	 		}
 			else{
				fval=0;
 	 			}
     	} else{
     		fval = ((val)*54.50);
        }
	if(fval<0){
		fval=0;
	}
	
	$('#actcounttmp').val(fval);
	
}

var TestScoreSend = function(eventVal){
	var fval = 0;
	var val=eventVal;
 		if($("#freelunchyes").is(':checked') || $("#freewaiversyes").is(':checked') ){
 			fval = (val*11.50);
     	} else{
     		fval = (val*11.50);
        }
	if(fval<0){
		fval=0;
	}

	$('#discounttestscorecounttmp').val(fval);
	$('#testscorecounttmp').val(fval);
	
}

var calcForDiscount = function(){
	var val1 = parseFloat($('#discounttestscorecounttmp').val());
	var val2 = parseFloat($('#discountsatsubcounttmp').val());
	var val3 = parseFloat($('#discountactcounttmp').val());
	var val4 = parseFloat($('#discountsatcounttmp').val());
	
	
	var valuc = parseInt($('#discounttotalappcostuc').val());
	var valcsu = parseInt($('#discounttotalappcostcsu').val());


	
	var coacsuCost = parseInt($('#discountcoacsu').val());
	var coaucCost = parseInt($('#discountcoauc').val());


	//var transFee=parseInt($('#schooltransfee').val());
	
	
	//return val1+val2+val3+val4+valuc+valcsu+coacsuCost+coaucCost + transFee;
	return val1+val2+val3+val4+valuc+valcsu+coacsuCost+coaucCost;
}

var calcALL = function(){

	var val1 = parseFloat($('#testscorecounttmp').val());
	var val2 = parseFloat($('#satsubcounttmp').val());
	var val3 = parseFloat($('#actcounttmp').val());
	var val4 = parseFloat($('#satcounttmp').val());
	
	var valuc = parseInt($('#totalappcostuc').val());
	var valcsu = parseInt($('#totalappcostcsu').val());
	$('#totalappcost').val(valuc+valcsu);
	
	var coacsuCost = parseInt($('#coacsu').val());
	var coaucCost = parseInt($('#coauc').val());

	//transFee=parseInt($('#schooltransfee').val());
	
	totalTesting = val1+val2+val3+val4;
	$('#totaltestingcost').val(totalTesting);
	
	totalAppCosts = parseInt($('#totalappcost').val());
	
	totalCOA = coacsuCost+coaucCost;
	
	totalDiscountCost = calcForDiscount();
	
	
	//totalOtherCosts = parseInt($('#totalothercost').val());
	
	//total = transFee+totalTesting+totalAppCosts+totalCOA;
	total = totalTesting+totalAppCosts+totalCOA;
	if($("#freelunchyes").is(':checked') || $("#freewaiversyes").is(':checked') ){
		totalOthers = totalDiscountCost - total;
	} else {
		totalOthers = 0;
	}
	$('#maincostval').html(total);
	$('#commcostval').html(totalOthers);
		
}

var totalUCAppCount = function (eventVal){

	var fval = 0;
	var val=eventVal;
 		if($("#freelunchyes").is(':checked') || $("#freewaiversyes").is(':checked')){
			if (val > 0){
				$('#discounttotalappcostuc').val(70+(70*(val-1)));
			}else {
				$('#discounttotalappcostuc').val(0);
			}
 			fval = 70+(70*(val-1))-280;
     	} else{
     		fval = 70+(70*(val-1));
        }
	if(fval<0 || val <= 0){
		fval=0;
	}
	$('#totalappcostuc').val(fval);
	var valuc = parseInt($('#totalappcostuc').val());
	var valcsu = parseInt($('#totalappcostcsu').val());
	$('#totalappcost').val(valuc+valcsu);
}


var totalCSUAppCount = function (eventVal){
	var fval = 0;
	var val=eventVal;
	if($("#freelunchyes").is(':checked') || $("#freewaiversyes").is(':checked')){
			if (val > 0){
				$('#discounttotalappcostcsu').val(55+(55*(val-1)));
			}else {
				$('#discounttotalappcostcsu').val(0);
			}
		fval = 55+(55*(val-1))-220;
	} else{
		fval = 55+(55*(val-1));
 	}
	if(fval<0 || val <= 0)
		fval=0;
	$('#totalappcostcsu').val(fval);
	var valuc = parseInt($('#totalappcostuc').val());
	var valcsu = parseInt($('#totalappcostcsu').val());
	$('#totalappcost').val(valuc+valcsu);

}


var satSubCountTmp = function (evalue){
	var fval = 0;
	var val=evalue;
 		if($("#freelunchyes").is(':checked') || $("#freewaiversyes").is(':checked') ){
			$('#discountsatsubcounttmp').val(parseInt((((val-0)+2)/3),10)*26+(val*18));
			if(val>6){
 				fval =  parseInt((((val-6)+2)/3), 10)*26+((val-6)*18);
 	 		}else{
				fval=0;
 	 			}
     	} else{
     		fval = parseInt((((val-0)+2)/3),10)*26+(val*18);
        }
	if(fval<0){
		fval=0;
	}
	$('#satsubcounttmp').val(fval);
}



$(function() {

	enableFreeLunc();
	calcPageLoad();
	
});

var enableFreeLunc = function(){
	if($("#freelunchyes").is(':checked'))
	{
		$('input[name=freewaivers]').attr("disabled",true);
	} else if ($("#freewaiversyes").is(':checked') )
	{
		$('input[name=freelunch]').attr("disabled",true);
	}
}

var calcPageLoad = function(){

	calcCOA($('.coacustom:checked').val());
	calcSATCNTTmp($('#satcount').val());
	calcACTTmp($('#actcount').val());
	//calcOtherCost($('input[name=commcoll]:checked').val());
	satSubCountTmp($('#satsubcount').val());
	TestScoreSend($('#testscorecount').val());

	totalUCAppCount($('#ucappcount').val());
	totalCSUAppCount($('#csuappcount').val());
	calcALL();
}

$('#livewith').on('change',function(){
	calcCOA($('.coacustom:checked').val());
	//calcOtherCost($('input[name=commcoll]:checked').val());
	calcALL();
});


$('.coacustom').click(function(){
	calcCOA($(this).val());
	calcALL();
});


$('input[name=commcoll]').click(function(){
	//calcOtherCost($(this).val());
	calcALL();
});

$('#satcount').on('input',function(){
	var inp=this.value;
	calcSATCNTTmp(inp);
	//calcCOA($('.coacustom:checked').val());
	calcALL();
});

$('#actcount').on('input',function(){
	var inp=this.value;
	calcACTTmp(inp);
	calcALL();
});


$('#satsubcount').on('input',function(){
	var inp=this.value;
	satSubCountTmp(inp);
	calcALL();
});

$('#testscorecount').on('input',function(){
	var inp=this.value;
	TestScoreSend(inp);
	calcALL();
});
/*$('#schooltransfee').on('change',function(){
	calcALL();
});*/
$('#ucappcount').on('input',function(){
	var inp=this.value;
	
	totalUCAppCount(inp);
	calcALL();
});

$('#csuappcount').on('input',function(){
	var inp=this.value;
	totalCSUAppCount(inp);
	calcALL();
});


$('input[name=freelunch]').click(function(){
	if($(this).val()=='1')
	{
	$('input[name=freewaivers]').attr("disabled",true);

	calcPageLoad();
	
	}else{
		$('input[name=freewaivers]').attr("disabled",false);
		calcPageLoad();
	}
});

$('input[name=freewaivers]').click(function(){
	if($(this).val()=='1')
	{
	$('input[name=freelunch]').attr("disabled",true);

	calcPageLoad();
	
	}else{
		$('input[name=freelunch]').attr("disabled",false);
		calcPageLoad();
	}
});








function page_has_error(){
		var cnt =0;
		$('[data-haserror="yes"]').each(function() {
			cnt+=1;
		});
		if(cnt>0)
			return false;
		else
			return true;
	}

</script>
<style>	
	.has_error{background-color:#f3cb5f}
</style> 

          

<!-- Feedbacify -->
<script type="text/javascript">
var fby = fby || [];
fby.push(['showTab', {id: '9871', position: 'right', color: '#EB0000'}]);

(function () {
   var f = document.createElement('script'); f.type = 'text/javascript'; f.async = true;
   f.src = '//cdn.feedbackify.com/f.js';
   var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(f, s);
})();
</script>

<!-- Fixed container - Mynotes and social media -->


