<?php
use Common\Utilities\Constants;
$allstates=explode(",",Constants::COUNTY);

$allEthnicity = explode(",", Constants::PLAN_MYPROFILE_ETHNICITY);
$res=$this->result;
$uid=$this->uid;
?>     
 <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper pscontentContainer">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            <i class="fa fa-smile-o"></i> My Profile
            <small>About You</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="/user/index"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li><a href="/plan/index"><i class="ion ion-gear-b"></i> Plan</a></li>
            <li class="active">My Profile</li>
          </ol>
        </section>
<form id="myprofileform" name="myprofileform" >
     
        <!-- Main content -->
        <section class="content">
        <!-- Mt Profile Form -->
          <div class="row">
          <!-- Right side content -->
              <div class="col-lg-3 col-lg-push-9 col-md-12 col-sm-12 col-xs-12 rightSideContainer">
                <div class="box box-warning ">
                    <div class="box-header with-border">
                      <h3 class="box-title"><i class="fa fa-file-video-o"></i> Hear from An Expert</h3>
                    </div>
                  <div class="box-body" >
                    <!-- <div class="embed-responsive embed-responsive-16by9">
                      <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/sqpw3NynsTE"></iframe>
                    </div>-->
                    <div id="myCarousel" class="carousel slide">
                      <!-- <ol class="carousel-indicators">
                        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                        <li data-target="#myCarousel" data-slide-to="1" class=""></li>
                      </ol>-->
                      <div class="carousel-inner">
                        <div class="item active">
                          <div class="embed-responsive embed-responsive-16by9">
                            <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/23YFGiaXHmE?showinfo=0&amp;" allowfullscreen></iframe>
                          </div>
                        </div>
                        
                      </div>
                      <!-- <a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>
                      <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a>-->
                    </div>
                  
                  </div><!-- /.box-body -->
                </div><!-- /.box -->           
                <div id="myAffix" class="box box-default visible-lg" data-spy="affix" data-offset-top="300">
                    <div class="box-header with-border">
                      <h3 class="box-title"><i class="fa fa-pencil"></i> My Notes</h3>
                    </div>
                  <div class="box-body">
                        <textarea class="form-control cusnote" rows="3" placeholder="Coming Soon..."name="note1" id="note1" readonly="readonly"><?php if(isset($res['notes'][0])){ echo $res['notes'][0];}?></textarea>
                        <button class="btn btn-default marginTop" id="savenote" disabled="true">Save My Notes </button>
                  </div><!-- /.box-body -->
                </div><!-- /.box -->

                <!-- social media -->
                <div id="myAffix1" class="box box-solid visible-lg" data-spy="affix" data-offset-top="300">
                    <div class="box-header ">
                      <h3 class="box-title"><i class="fa fa-share-alt"></i> Follow Us</h3>
                      <div class=" pull-right " >
                        <div  class="fixedBtn"><a href="https://www.facebook.com/askuceazy" class="bg-facebook" target="_blank" title="Facebook"><i class="fa fa-facebook"></i></a></div>
                        <div class="fixedBtn"><a href="https://twitter.com/Uaskuceazy?lang=en" class="bg-twitter" target="_blank" title="Twitter"><i class="fa fa-twitter"></i></a></div>
                        <div class="fixedBtn"><a href="https://www.linkedin.com/company/uceazy" class="bg-linkedin" target="_blank" title="Linkedin"><i class="fa fa-linkedin"></i></a></div>

                        <!-- <div class="fixedBtn"><a href="#" class="bg-google-plus"><i class="fa fa-google-plus"></i></a></div>
                        <div class="fixedBtn"><a href="#" class="bg-instagram"><i class="fa fa-instagram"></i></a></div>
                        <div class="fixedBtn"><a href="#" class="bg-pinterest"><i class="fa fa-pinterest"></i></a></div>-->
                      </div>  
                    </div>
                </div>
            </div>
            <!-- ./Right side content -->

            <div id="adminContent" class="col-lg-9 col-lg-pull-3 col-md-12 col-sm-12 col-xs-12">
              <div class="box box-default box-solid">
                <div class="box-header bgTesting-active">
                  <h3 class="box-title">Please enter your information</h3>
                </div><!-- /.box-header -->
                <!-- form start -->
                <div class="box-body">
                <!-- About you -->
                  <div class="box box-default box-solid">
                    <div class="box-header bgTesting" data-widget="collapse" data-collapse="custom">
                      <h3 class="box-title">About you</h3>
                      <div class="box-tools pull-right">
                        <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                      </div><!-- /.box-tools -->
                    </div><!-- /.box-header -->
                  
                    <div class="box-body  ">
                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">First Name <span class="mandatory">*</span></label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" id="fname" name="fname" value="<?php echo isset($res['firstName'])? $res['firstName']:"";?>" maxlength="100" data-validate="yes" data-rules="type:alp_num_spl_char,max_length:100" /> 
                          </div>
                          <div class="tooltipContent"> 
                            <a href="#" data-toggle="tooltip" class="tip-right" data-original-title="Use first name as listed on your birth certificate.  Do not use a nickname."><i class="fa fa-info-circle "></i></a> 
                          </div>
                      </div>

                      <div class="form-group">  
                          <label for="californiaCounty" class="col-sm-3 control-label">Middle Name</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="mname" value="<?php echo isset($res['middleName'])? $res['middleName']:"";?>" maxlength="100" data-validate="yes" data-rules="type:alp_num_spl_char,max_length:100" /> 
                          </div>
                          <div class="clearfix"></div>
                      </div>

                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Last Name</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="lname" value="<?php echo isset($res['lastName'])? $res['lastName']:"";?>" maxlength="100" data-validate="yes" data-rules="type:alp_num_spl_char,max_length:100" /> 
                          </div>
                          <div class="clearfix"></div>
                      </div>
                      <!--
                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Suffix</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="suffix" value="<?php echo isset($res['suffix'])? $res['suffix']:"";?>"/> 
                          </div>
                          <div class="tooltipContent"> 
                            <a href="#" data-toggle="tooltip" class="tip-right" data-original-title="Jr, Sr, III"><i class="fa fa-info-circle "></i></a> 
                          </div>
                      </div>

                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Current Street Address</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="street" value="<?php echo isset($res['streetAddress'])? $res['streetAddress']:"";?>"/> 
                          </div>
                      </div>

                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Current City</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="city" value="<?php echo isset($res['city'])? $res['city']:"";?>"/> 
                          </div>
                      </div>

                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Current State</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="state" value="<?php echo isset($res['state'])? $res['state']:"";?>" /> 
                          </div>
                      </div>

                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Current Zip Code</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="zipcode" value="<?php echo isset($res['zipcode'])? $res['zipcode']:"";?>"/> 
                          </div>
                      </div>

                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Current County</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="county" value="<?php echo isset($res['county'])? $res['county']:"";?>"/> 
                          </div>
                      </div>
  
                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Primary Telephone</label>
                          <div class="col-sm-6">
                             <div class="input-group">
                              <div class="input-group-addon">
                                <i class="fa fa-phone"></i>
                              </div>
                              <input type="text" class="form-control" value="<?php echo isset($res['phone'])? $res['phone']:"";?>" name="telephone"/>
                            </div>
                          </div>
                      </div>-->

                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Cell Phone</label>
                          <div class="col-sm-6">
                            <div class="input-group">
                              <div class="input-group-addon">
                                <i class="fa fa-mobile"></i>
                              </div>
                              <input type="text" class="form-control" name="cell" value="<?php echo isset($res['mobilePhone'])? $res['mobilePhone']:"";?>"  data-mask maxlength="14" data-validate="yes" data-rules="type:numeric,max_length:14"/>
                            </div><!-- /.input group -->
                          </div>
                          <div class="clearfix"></div>
                      </div>

                      <div class="form-group noMargin">
                          <label for="californiaCounty" class="col-sm-3 control-label">Email</label>
                          <div class="col-sm-6">
                            <div class="input-group">
                              <div class="input-group-addon">
                                <i class="fa fa-envelope"></i>
                              </div>
                              <input type="text" name="email" class="form-control" value="<?php echo isset($res['email'])? $res['email']:"";?>" maxlength="100" data-validate="yes" data-rules="type:email,max_length:100" />
                            </div><!-- /.input group -->
                          </div>
                      </div>
                      <!--
                      <div class="form-group">
                          <label for="birthdate" class="col-sm-3 control-label">Birthdate</label>
                          
                          <div class="col-sm-6">
                            <div class="input-group date" id='datetimepicker1'>
                              <div class="input-group-addon">
                                <i class="fa fa-calendar"></i>
                              </div>
                              <input type="text" class="form-control"  value="<?php echo isset($res['birthday'])? $res['birthday']:"";?>" name="birthdate" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask/>
                            </div>
                            
                          </div>
                      </div>

                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Legal Sex</label>
                          <div class="col-sm-6">
                              <div class="radio" >
                              <?php 
                              $gendar=isset($res['sex'])? $res['sex']:"";
                              ?>
                                <label class="radio-inline" >
                                  <input type="radio" name="gendar" <?php if($gendar=="Male"){?> checked="checked" <?php }?> value="Male" >
                                  Male
                                </label>
                                <label class="radio-inline">
                                  <input type="radio" name="gendar" value="Female" <?php if($gendar=="Female"){?> checked="checked" <?php }?> >
                                  Female
                                </label>
                                
                             </div>
                          </div>
                      </div>-->
                    </div><!-- /.box-body -->                    
                </div><!-- /widget -->

                  <!-- Ethnicity
                  <div class="box box-default box-solid collapsed-box">
                    <div class="box-header bgTesting">
                      <h3 class="box-title">Ethnicity & Race</h3>
                      <div class="box-tools pull-right">
                        <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
                      </div>
                    </div>
                  
                  <?php 
                  
                  $ethVal=isset($res['ethnicity'])?$res['ethnicity']:null;
                  
                  ?>
                  
                  
                    <div class="box-body  ">
                      <div class="form-group">
                          <label for="" class="col-sm-3 control-label">Do you consider yourself Hispanic or Latino?</label>
                          <div class="col-sm-6">
                              <div class="radio" >
                                <label class="radio-inline " >
                                  <input type="radio"  name="ethnicity" class="trigger" data-rel="chooseCategory" <?php if($ethVal=="yes"){?> checked="checked" <?php }?> value="yes" >
                                  Yes
                                </label>
                                <label class="radio-inline">
                                  <input type="radio"  name="ethnicity" value="no" class="trigger" data-rel="chooseRaceCategory" <?php if($ethVal=="no"){?> checked="checked" <?php }?>>
                                  No
                                </label>
                                <label class="radio-inline">
                                  <input type="radio"  name="ethnicity" value="decline" class="trigger" data-rel="chooseRaceCategory" <?php if($ethVal=="decline"){?> checked="checked" <?php }?>>
                                  Decline to State
                                </label>
                             </div>
                          </div>                          
                      </div>

                      <div class="form-group chooseCategory displayNone">
                          <label for="" class="col-sm-3  control-label">If yes, choose a category that closest describes your background</label>
                          <div class="col-sm-6">
                              <select class="form-control" name="ethnicityname" id="ethnicityname">
                               <?php foreach ($allEthnicity as $row){
                               
                               	$vals = explode(":", $row);
                               	?>
                                <option value="<?php echo $vals[0];?>"><?php echo $vals[1];?></option>
                                <?php }?>
                              </select>
                          </div>   

                      </div>

                    <div class="form-group displayNone" id="ethnicitynameothers">
                          <label for="" class="col-sm-3 chooseOtherCategory control-label">Others, Please Specify</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="ethnicitynameothers"/>
                          </div>   
                      </div>
                      
                      <div  class="race chooseRaceCategory displayNone">
                        <div class="form-group ">
                            <label for="" class="col-sm-3 control-label">Select Race Category</label>
                            <div class="col-sm-6">
                              
                                <select id="selectRace" name="selectRace" class="form-control">
                                  <option value="option0">Select</option>
                                  <option value="option1">White</option>
                                  <option value="option2">Black/African American</option>
                                  <option value="option3">American Indian/Alaska Native</option>
                                  <option value="option4">Asian</option>
                                  <option value="option5">Native Hawaiian/Other Pacific Islander</option>
                                  <option value="option6">Decline to State</option>
                                  <option value="option7">None of the Above</option>
                                </select>
                                
                            </div>                          
                            <div class="tooltipContent"> <a href="#" data-toggle="tooltip" class="tip-right" data-original-title="If you are more than one race, please select one category at a time. A box will pop up so that you can add as many categories as describe you."><i class="fa fa-info-circle "></i></a>
                            </div>
                        </div>
                        
                        <div class="form-group option1 displayNone">
                            <label for="" class="col-sm-3 control-label">Race - White</label>
                            <div class="col-sm-6">
                                <select class="form-control" id="racewhite">
                                  <option>Select</option>
                                  <option>European</option>
                                  <option>Middle Easterner</option>
                                  <option>North African</option>
                                  <option value="others">Other White (please specify)</option>
                                </select>
                            </div>                          
                        </div>

                        
                        <div class="form-group option2 displayNone">
                            <label for="californiaCounty" class="col-sm-3 control-label">Race - Black / African American</label>
                            <div class="col-sm-6">
                                <select class="form-control" id="raceblack">
                                  <option>Select</option>
                                  <option>African American</option>
                                  <option>Black</option>
                                  <option>Haitian</option>
                                  <option value="others">Other African/Black (please specify)</option>
                                </select>
                            </div>                          
                        </div>

                        
                        <div class="form-group option3 displayNone">
                            <label for="californiaCounty" class="col-sm-3 control-label">Race - American Indian / Alaska Native</label>
                            <div class="col-sm-6">
                                <select class="form-control" id="raceamericanindian">
                                  <option>Select</option>
                                  <option>Achomawi/Achumawi</option>
                                  <option>Cahto (e.g., Cahto Indian Tribe of the Laytonville)</option>
                                  <option>Cahuilla (e.g., Agua Caliente Band of Cahuilla Indians)</option>
                                  <option>Chemehuevi (e.g., Chemehuevi Indian Tribe of the Chemehuevi Reservation, California)</option>
                                  <option>Chumash (e.g., Santa Ynez Band of Chumash Mission)</option>
                                  <option></option>
                                  <option value="others">Other American Indian Tribes (please specify)</option>
                                  <option value="others">Other Alaska Native Tribes (please specify)</option>
                                </select>
                            </div>                          
                        </div>

                        <div class="form-group option4 displayNone">
                            <label for="californiaCounty" class="col-sm-3 control-label">Race - Asian</label>
                            <div class="col-sm-6">
                                <select class="form-control" id="raceasian">
                                  <option>Select</option>
                                  <option>Asian Indian</option>
                                  <option>Bangladeshi</option>
                                  <option>Bhutanese</option>
                                  <option>Burmese</option>
                                  <option>Cambodian</option>
                                  <option>Chinese (except Taiwanese)</option>
                                  <option>Filipino</option>
                                  <option>Hmong</option>
                                  <option>.</option>
                                  <option value="others">Other Asian (please specify)</option>
                                </select>
                            </div>                          
                        </div>

                        
                        <div class="form-group option5 displayNone">
                            <label for="californiaCounty" class="col-sm-3 control-label">Race - Native Hawaiian / Other Pacific Islander</label>
                            <div class="col-sm-6">
                                <select class="form-control" id="racenativehawaiian">
                                  <option>Select</option>
                                  <option>Carolinian</option>
                                  <option>Chuukese</option>
                                  <option>Fijian</option>
                                  <option>Guamanian or Chomorro</option>
                                  <option>I-Kiribati</option>
                                  <option>Mariana Islander</option>
                                  <option>Marshallese</option>
                                  <option>Native Hawaiian</option>
                                  <option>.</option>
                                  <option value="others">Other Pacific Islander (please specify)</option>
                                </select>
                            </div>                          
                          </div>
                          
                          <div class="form-group others displayNone">
                          <label for="" class="col-sm-3 chooseOtherCategory control-label">Others, Please Specify</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="racenameothers"/>
                          </div>                           
                          </div>
                          
                      </div>
                      
                    </div>
                </div>-->

                
                
                
                <!-- Parent/Guardian Information -->
                <div class="box box-default box-solid collapsed-box">
                  <div class="box-header bgTesting" data-widget="collapse" data-collapse="custom">
                    <h3 class="box-title">Parent/Guardian#1 Information (Optional) </h3>
                    <div class="box-tools pull-right">
                      <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
                    </div><!-- /.box-tools -->
                  </div><!-- /.box-header -->
                
                  <div class="box-body  ">
                  
                  <?php 
                  $row1=isset($res['parentGuardian'][0])?$res['parentGuardian'][0]:null;
                  if($row1!=null){
                  ?>
                  
                    <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">First Name</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="pgfname1" value="<?php echo $row1['PGFirstName'];?>" maxlength="100" data-validate="yes" data-rules="type:alp_num_spl_char,max_length:100" /> 
                          </div>
                          <div class="clearfix"></div>
                      </div>

                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Middle Name</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="pgmname1" value="<?php echo $row1['PGMiddleName'];?>" maxlength="100" data-validate="yes" data-rules="type:alp_num_spl_char,max_length:100" /> 
                          </div>
                          <div class="clearfix"></div>
                      </div>

                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Last Name</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="pglname1" value="<?php echo $row1['PGLastName'];?>" maxlength="100" data-validate="yes" data-rules="type:alp_num_spl_char,max_length:100" /> 
                          </div>
                          <div class="clearfix"></div>
                      </div>
                      <!--
                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Current Street Address</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="pgaddress1" value="<?php echo $row1['PGStreetAddress'];?>"/> 
                          </div>
                      </div>

                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Current City</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="pgcity1" value="<?php echo $row1['PGCity'];?>"/> 
                          </div>
                      </div>

                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Current State</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="pgstate1" value="<?php echo $row1['PGState'];?>"/> 
                          </div>
                      </div>

                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Current Zip Code</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="pgzip1" value="<?php echo $row1['PGZipcode'];?>"/> 
                          </div>
                      </div>

                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Current County</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="pgcounty1" value="<?php echo $row1['PGCounty'];?>"/> 
                          </div>
                      </div>

                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Home Telephone</label>
                          <div class="col-sm-6">
                             <div class="input-group">
                              <div class="input-group-addon">
                                <i class="fa fa-phone"></i>
                              </div>
                              <input type="text" class="form-control" name="pgtelephone1" value="<?php echo $row1['PGPhone'];?>" data-inputmask='"mask": "(999) 999-9999"' data-mask/>
                            </div>
                          </div>
                      </div> -->

                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Cell Phone</label>
                          <div class="col-sm-6">
                            <div class="input-group">
                              <div class="input-group-addon">
                                <i class="fa fa-mobile"></i>
                              </div>
                              <input type="text" class="form-control" name="pgcell1" value="<?php echo $row1['PGMobilePhone'];?>" data-mask maxlength="14" data-validate="yes" data-rules="type:numeric,max_length:14"/>
                            </div><!-- /.input group -->
                          </div>
                          <div class="clearfix"></div>
                      </div>

                      <div class="form-group noMargin">
                          <label for="californiaCounty" class="col-sm-3 control-label">Email</label>
                          <div class="col-sm-6">
                            <div class="input-group">
                              <div class="input-group-addon">
                                <i class="fa fa-envelope"></i>
                              </div>
                              <input type="text" class="form-control" name="pgemail1" value="<?php echo $row1['PGEmail'];?>" maxlength="100" data-validate="yes" data-rules="type:email,max_length:100"/>
                            </div><!-- /.input group -->
                          </div>
                          <div class="clearfix"></div>
                      </div>      
                      <!-- 
                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Do you allow this parent/guardian to receive emails from UCEazy?</label>
                          <div class="col-sm-6">
                            <div class="radio" >
                              <label class="radio-inline" >
                                <input type="radio" name="isemailuceazy1" value="true" <?php if($row1['PGEmailUcEazy']===true){?> checked="checked"  <?php }?>>
                                Yes
                              </label>
                              <label class="radio-inline">
                                <input type="radio" name="isemailuceazy1" value="false"  <?php if($row1['PGEmailUcEazy']===false){?> checked="checked"  <?php }?> >
                                No
                              </label>
                            </div>
                          </div>
                      </div>   

                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Do you allow this parent/guardian to receive emails from the UC/CSU's?</label>
                          <div class="col-sm-6">
                            <div class="radio" >
                              <label class="radio-inline" >
                                <input type="radio" name="isemailucsu1" value="true" <?php if($row1['PGEmailUCCSU']===true){?> checked="checked"  <?php }?>>
                                Yes
                              </label>
                              <label class="radio-inline">
                                <input type="radio" name="isemailucsu1" value="false" id="aus" <?php if($row1['PGEmailUCCSU']===false){?> checked="checked"  <?php }?>>
                                No
                              </label>
                            </div>
                          </div>
                      </div>-->  
                      
                      <?php }else{?>
                      
                    <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">First Name</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="pgfname1" maxlength="100" data-validate="yes" data-rules="type:alp_num_spl_char,max_length:100" /> 
                          </div>
                          <div class="clearfix"></div>
                      </div>

                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Middle Name</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="pgmname1" maxlength="100" data-validate="yes" data-rules="type:alp_num_spl_char,max_length:100" /> 
                          </div>
                          <div class="clearfix"></div>
                      </div>

                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Last Name</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="pglname1" maxlength="100" data-validate="yes" data-rules="type:alp_num_spl_char,max_length:100" /> 
                          </div>
                          <div class="clearfix"></div>
                      </div>
                      <!-- 
                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Current Street Address</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="pgaddress1" /> 
                          </div>
                      </div>

                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Current City</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="pgcity1" /> 
                          </div>
                      </div>

                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Current State</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="pgstate1" /> 
                          </div>
                      </div>

                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Current Zip Code</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="pgzip1" /> 
                          </div>
                      </div>

                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Current County</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="pgcounty1" /> 
                          </div>
                      </div>

                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Home Telephone</label>
                          <div class="col-sm-6">
                             <div class="input-group">
                              <div class="input-group-addon">
                                <i class="fa fa-phone"></i>
                              </div>
                              <input type="text" class="form-control" name="pgtelephone1" data-inputmask='"mask": "(999) 999-9999"' data-mask/>
                            </div>
                          </div>
                      </div>
                      -->
                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Cell Phone</label>
                          <div class="col-sm-6">
                            <div class="input-group">
                              <div class="input-group-addon">
                                <i class="fa fa-mobile"></i>
                              </div>
                              <input type="text" class="form-control" name="pgcell1" data-mask maxlength="14" data-validate="yes" data-rules="type:numeric,max_length:14"/>
                            </div><!-- /.input group -->
                          </div>
                          <div class="clearfix"></div>
                      </div>

                      <div class="form-group noMargin">
                          <label for="californiaCounty" class="col-sm-3 control-label">Email</label>
                          <div class="col-sm-6">
                            <div class="input-group">
                              <div class="input-group-addon">
                                <i class="fa fa-envelope"></i>
                              </div>
                              <input type="text" class="form-control" name="pgemail1" maxlength="100" data-validate="yes" data-rules="type:email,max_length:100" />
                            </div><!-- /.input group -->
                          </div>
                          <div class="clearfix"></div>
                      </div>      
                      <!-- 
                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Do you allow this parent/guardian to receive emails from UCEazy?</label>
                          <div class="col-sm-6">
                            <div class="radio" >
                              <label class="radio-inline" >
                                <input type="radio" name="isemailuceazy1" value="true" >
                                Yes
                              </label>
                              <label class="radio-inline">
                                <input type="radio" name="isemailuceazy1" value="false" id="aus" >
                                No
                              </label>
                            </div>
                          </div>
                      </div>   

                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Do you allow this parent/guardian to receive emails from the UC/CSU's?</label>
                          <div class="col-sm-6">
                            <div class="radio" >
                              <label class="radio-inline" >
                                <input type="radio" name="isemailucsu1" value="true" >
                                Yes
                              </label>
                              <label class="radio-inline">
                                <input type="radio" name="isemailucsu1" value="false" id="aus" >
                                No
                              </label>
                            </div>
                          </div>
                      </div>                                     
                      -->
                      <?php }?>                                   
                  </div><!-- /widget -->
                </div>

                <!-- Parent/Guardian Information -->
                <div class="box box-default box-solid collapsed-box">
                  <div class="box-header bgTesting" data-widget="collapse" data-collapse="custom">
                    <h3 class="box-title">Parent/Guardian#2 Information (Optional) </h3>
                    <div class="box-tools pull-right">
                      <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
                    </div><!-- /.box-tools -->
                  </div><!-- /.box-header -->
                
                  <div class="box-body  ">
                  
                    <?php 
                  
                  $row2=isset($res['parentGuardian'][1])?$res['parentGuardian'][1]:null;
                  
                  if($row2!=null){
                  
                  ?>
                    <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">First Name</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="pgfname2" value="<?php echo $row2['PGFirstName'];?>" maxlength="100" data-validate="yes" data-rules="type:alp_num_spl_char,max_length:100" /> 
                          </div>
                          <div class="clearfix"></div>
                      </div>

                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Middle Name</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="pgmname2" value="<?php echo $row2['PGMiddleName'];?>" maxlength="100" data-validate="yes" data-rules="type:alp_num_spl_char,max_length:100" /> 
                          </div>
                          <div class="clearfix"></div>
                      </div>

                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Last Name</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="pglname2" value="<?php echo $row2['PGLastName'];?>" maxlength="100" data-validate="yes" data-rules="type:alp_num_spl_char,max_length:100" /> 
                          </div>
                          <div class="clearfix"></div>
                      </div>
                      <!-- 
                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Current Street Address</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="pgaddress2" value="<?php echo $row2['PGStreetAddress'];?>" /> 
                          </div>
                      </div>

                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Current City</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="pgcity2" value="<?php echo $row2['PGCity'];?>"/> 
                          </div>
                      </div>

                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Current State</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="pgstate2" value="<?php echo $row2['PGState'];?>"/> 
                          </div>
                      </div>

                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Current Zip Code</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="pgzip2" value="<?php echo $row2['PGZipcode'];?>"/> 
                          </div>
                      </div>

                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Current County</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="pgcounty2" value="<?php echo $row2['PGCounty'];?>"/> 
                          </div>
                      </div>

                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Home Telephone</label>
                          <div class="col-sm-6">
                             <div class="input-group">
                              <div class="input-group-addon">
                                <i class="fa fa-phone"></i>
                              </div>
                              <input type="text" class="form-control" name="pgtelephone2" value="<?php echo $row2['PGPhone'];?>" data-inputmask='"mask": "(999) 999-9999"' data-mask/>
                            </div>
                          </div>
                      </div>
                      -->
                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Cell Phone</label>
                          <div class="col-sm-6">
                            <div class="input-group">
                              <div class="input-group-addon">
                                <i class="fa fa-mobile"></i>
                              </div>
                              <input type="text" class="form-control" name="pgcell2" value="<?php echo $row2['PGMobilePhone'];?>" data-mask maxlength="14" data-validate="yes" data-rules="type:numeric,max_length:14" />
                            </div><!-- /.input group -->
                          </div>
                          <div class="clearfix"></div>
                      </div>

                      <div class="form-group noMargin">
                          <label for="californiaCounty" class="col-sm-3 control-label">Email</label>
                          <div class="col-sm-6">
                            <div class="input-group">
                              <div class="input-group-addon">
                                <i class="fa fa-envelope"></i>
                              </div>
                              <input type="text" class="form-control" name="pgemail2" value="<?php echo $row2['PGEmail'];?>" maxlength="100" data-validate="yes" data-rules="type:email,max_length:100" />
                            </div><!-- /.input group -->
                          </div>
                          <div class="clearfix"></div>
                      </div>      
                      <!--
                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Do you allow this parent/guardian to receive emails from UCEazy?</label>
                          <div class="col-sm-6">
                            <div class="radio" >
                              <label class="radio-inline" >
                                <input type="radio" name="isemailuceazy2" value="true" <?php if($row1['PGEmailUcEazy']===true){?> checked="checked"  <?php }?>>
                                Yes
                              </label>
                              <label class="radio-inline">
                                <input type="radio" name="isemailuceazy2" value="false"  <?php if($row1['PGEmailUcEazy']===false){?> checked="checked"  <?php }?>>
                                No
                              </label>
                            </div>
                          </div>
                      </div>   

                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Do you allow this parent/guardian to receive emails from the UC/CSU's?</label>
                          <div class="col-sm-6">
                            <div class="radio" >
                              <label class="radio-inline" >
                                <input type="radio" name="isemailucsu2" value="true" <?php if($row1['PGEmailUCCSU']===true){?> checked="checked"  <?php }?>>
                                Yes
                              </label>
                              <label class="radio-inline">
                                <input type="radio" name="isemailucsu2" value="false" id="aus" <?php if($row1['PGEmailUCCSU']===false){?> checked="checked"  <?php }?> >
                                No
                              </label>
                            </div>
                          </div>
                      </div>                                     
                  </div> /widget -->
           
           <?php }else{?>
            <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">First Name</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="pgfname2" maxlength="100" data-validate="yes" data-rules="type:alp_num_spl_char,max_length:100" /> 
                          </div>
                          <div class="clearfix"></div>
                      </div>

                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Middle Name</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="pgmname2" maxlength="100" data-validate="yes" data-rules="type:alp_num_spl_char,max_length:100" /> 
                          </div>
                          <div class="clearfix"></div>
                      </div>

                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Last Name</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="pglname2" maxlength="100" data-validate="yes" data-rules="type:alp_num_spl_char,max_length:100" /> 
                          </div>
                          <div class="clearfix"></div>
                      </div>
                      <!-- 
                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Current Street Address</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="pgaddress2" /> 
                          </div>
                      </div>

                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Current City</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="pgcity2" /> 
                          </div>
                      </div>

                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Current State</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="pgstate2" /> 
                          </div>
                      </div>

                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Current Zip Code</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="pgzip2" /> 
                          </div>
                      </div>

                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Current County</label>
                          <div class="col-sm-6">
                              <input type="text" class="form-control" name="pgcounty2" /> 
                          </div>
                      </div>

                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Home Telephone</label>
                          <div class="col-sm-6">
                             <div class="input-group">
                              <div class="input-group-addon">
                                <i class="fa fa-phone"></i>
                              </div>
                              <input type="text" class="form-control" name="pgtelephone2" data-inputmask='"mask": "(999) 999-9999"' data-mask/>
                            </div>
                          </div>
                      </div>
                      -->
                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Cell Phone</label>
                          <div class="col-sm-6">
                            <div class="input-group">
                              <div class="input-group-addon">
                                <i class="fa fa-mobile"></i>
                              </div>
                              <input type="text" class="form-control" name="pgcell2" data-inputmask='"mask": "(999) 999-9999"' data-mask maxlength="14" data-validate="yes" data-rules="type:numeric,max_length:14" />
                            </div><!-- /.input group -->
                          </div>
                          <div class="clearfix"></div>
                      </div>

                      <div class="form-group noMargin">
                          <label for="californiaCounty" class="col-sm-3 control-label">Email</label>
                          <div class="col-sm-6">
                            <div class="input-group">
                              <div class="input-group-addon">
                                <i class="fa fa-envelope"></i>
                              </div>
                              <input type="text" class="form-control" name="pgemail2" maxlength="100" data-validate="yes" data-rules="type:email,max_length:100" />
                            </div><!-- /.input group -->
                          </div>
                          <div class="clearfix"></div>
                      </div>      
                      <!-- 
                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Do you allow this parent/guardian to receive emails from UCEazy?</label>
                          <div class="col-sm-6">
                            <div class="radio" >
                              <label class="radio-inline" >
                                <input type="radio" name="isemailuceazy2" value="true" >
                                Yes
                              </label>
                              <label class="radio-inline">
                                <input type="radio" name="isemailuceazy2" value="false"  >
                                No
                              </label>
                            </div>
                          </div>
                      </div>   

                      <div class="form-group">
                          <label for="californiaCounty" class="col-sm-3 control-label">Do you allow this parent/guardian to receive emails from the UC/CSU's?</label>
                          <div class="col-sm-6">
                            <div class="radio" >
                              <label class="radio-inline" >
                                <input type="radio" name="isemailucsu2" value="true" >
                                Yes
                              </label>
                              <label class="radio-inline">
                                <input type="radio" name="isemailucsu2" value="false" id="aus" >
                                No
                              </label>
                            </div>
                          </div>
                      </div>                                     
                  </div> /widget -->
           
           <?php }?>
                </div>
                
              </div>

                  <div class="box-footer ">
                  
                  <div class="alert alert-error" id="error" role="alert" style="display: none;">
                      <h4 id=""><i class="icon fa fa-check "></i>
                      <span class="info-text" id="texterror">
                    </span>
                      </h4>
                 </div>
      
                <div class="alert alert-success" id="success" role="alert" style="display: none;">
                      <h4 id=""><i class="icon fa fa-check "></i>
                      <span class="info-text" id="textsuccess">
                    </span>
                      </h4>
                 </div>
                  <div class="text-center">
                    <button type="button" class="btn btn-default bg-orange pull-left" data-toggle="modal" data-target="#recom_letter" >Letters of Recommendation</button>       
                    <input type="hidden" name="uid" value="<?php echo $uid;?>" >
                    
                      <?php if($this->planflag=="1"){?>
                    <button type="button" id="myprofile-submit" value="update" class="btn btn-danger" >Update My Information</button> 
                    <button type="button" id="myprofile-next" value="update" class="btn btn-danger pull-right" >Next: Major</button>                          
                    
                    <?php }else{?>
                    <button type="button" id="myprofile-submit" value="save" class="btn btn-danger" data-complete-text="Update My Information">Save My Information</button>  
                    <button type="button" id="myprofile-next" value="save" class="btn btn-danger pull-right" >Next: Major</button>                         
                    <?php }?>   

                                 
                  </div>
                  </div><!-- /.box-footer -->
               
              </div><!-- /.box -->
              </div>  
            </div>
              

            
          </div><!-- /.row -->
          <div class="clearfix"></div>
          <!-- My Notes for devices -->
          <div class="rightSideContainer">
            <div id="myAffix" class="box box-default hidden-lg" >
                    <div class="box-header with-border">
                      <h3 class="box-title"><i class="fa fa-pencil"></i> My Notes</h3>
                    </div>
                  <div class="box-body">
                        <textarea class="form-control" rows="3" placeholder="Coming Soon..." name="note2" id="note2" readonly="readonly"><?php if(isset($res['notes'][0])){ echo $res['notes'][0];}?></textarea>
                        <button class="btn btn-default marginTop"  id="savenote" disabled="true">Save My Notes </button>
                        <input type="hidden" name="note" id="note" value="<?php if(isset($res['notes'][0])){ echo $res['notes'][0];}?>">
                  </div><!-- /.box-body -->
                </div><!-- /.box -->
           </div>
        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->
 </form>
      <!-- Main Footer -->
      
    </div><!-- ./wrapper -->

    
      
       <div class="modal fade" id="success" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header btn-danger">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title " id="myModalLabel">Success</h4>
	      </div>
	      <div class="modal-body" id="modalsuccessbody">
	        Your Profile information has been saved.
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	        <!-- <button type="button" class="btn btn-primary">Save changes</button>-->
	      </div>
	    </div>
	  </div>
	</div>
      
       <div class="modal fade" id="failure" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header btn-danger">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title " id="myModalLabel">Failure</h4>
	      </div>
	      <div class="modal-body" id="modalfailbody">
	        Oops!  Looks like something went wrong.  Please try again later.
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	        <!-- <button type="button" class="btn btn-primary">Save changes</button>-->
	      </div>
	    </div>
	  </div>
	</div>
	
	<div class="modal fade" id="recom_letter" tabindex="-1" role="dialog" aria-labelledby="LettersofRecommendation">
	  <div class="modal-dialog" role="document">
		<div class="box box-default box-solid">
		  <div class="box-header bgTesting">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			<h3 class="box-title" id="" align="center"><b>Letters of Recommendation</b></h3>
		  </div>
		  <div class="modal-body">
			<h5>*NEW THIS YEAR!!*</h5>
			<p>Starting in 2015, <b><u>SOME</u></b> students applying to UC Berkeley will be given the opportunity to submit two letters of recommendation.  Because this is still a new policy, here is the information we know right now:</p>
			<h4><b><u>INFORMATION FOR STUDENTS:</u></b></h4>
			<i><b>Who should write the letter(s)?</b></i>
			<p>One letter must be written by a teacher/instructor. The second letter can be written by anyone the student selects, ideally someone who knows them well and can speak to one or more of the characteristics below.</p>
			<i><b></b></i>
			<p></p>
			
			<i><b>How will the letters be submitted?</b></i>
			<p>All letters must be submitted electronically. No letters in the mail or by courier will be accepted. Invited applicants will identify letter writers via a link sent to them after their applications receive an initial review. PLEASE NOTE: Requests for letters of recommendation WILL NOT be found within the UC application, which opens Aug. 1. The request will be delivered to your email as a simple supplement. These requests will not occur until November of this year.</p>
			
			<i><b>Will a third letter be accepted?</b></i>
			<p>No. Only two letters will be accepted.</p>
			
			
			<i><b>Will applications without a letter still be read? Will they be at a disadvantage?</b></i>
			<p>The new policy remains committed to making sure that all freshman applications are thoroughly and thoughtfully read, with or without a letter. Students without a letter will not be at a disadvantage, but UC Berkeley does highly encourage students to use this opportunity.</p>
			
			
			<i><b>Are other UC campuses also accepting letters of recommendation?</b></i>
			<p>No campus of the University of California requires letters of recommendation when the admission application is submitted; however, UC campuses may later request additional information from applicants. If additional information is needed, applicants will be notified individually.</p>
			
			<i><b>If I'm not selected to submit letters of recommendation, can I still submit them?</b></i>
			<p>No other supplemental information will be included in the application unless it is requested.</p>

			<i><b>Will other UC campuses I applied to be able to see my letters of recommendation?</b></i>
			<p>No, these letters are submitted directly to UC Berkeley and are only used in their review process. </p>
			
			<i><b>Where can I get more information?</b></i>
			<p>Please click <a href="http://admissions.berkeley.edu/sites/default/files/docs/Tools%20for%20Students.pdf">here </a></p>
			
			<h4><b><u>INFORMATION TO TELL YOUR LETTER WRITERS:</u></b></h4>
			
			<i><b>What is the deadline?</b></i>
			<p>All letters will be due by 11:59 p.m. on January 1, 2016. After this date, it is not guaranteed that a letter can be read as a part of the application review.</p>
			
			<i><b>Is there a word limit?</b></i>
			<p>While there is not a word limit, we ask that letters be limited to one page. </p>
			
			<i><b>What should I write about?</b></i>
			<p>UC Berkeley asks that those who write letters consider the following concepts when asked to add a letter to the application process:  </p>
			<ul>
				<li>Academic performance and potential (both overall and in the context of the class) </li>
				<li>Love of learning</li>
				<li>Leadership (in school, family, or community) </li>
				<li>Persistence in the face of challenges </li>
				<li>Cross-cultural engagement </li>
				<li>Originality/Creativity </li>
				<li>Demonstrated concern for others </li>				
			</ul>
			
			<i><b>Where can I get more information?</b></i>
			<p>Please click <a href="http://admissions.berkeley.edu/sites/default/files/docs/Tools%20for%20Students.pdf" target="_blank">here </a></p>
			
		  </div>
		  <div class="modal-footer"></div>
		</div>
	  </div>
	</div>
	
	
      
    
    <!-- REQUIRED JS SCRIPTS -->

    <!-- jQuery 2.1.4 -->
    <script src="/plugins/jQuery/jQuery-2.1.4.min.js"></script>
    <!-- Datepicker -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.3/moment.min.js" type="text/javascript"></script>
    <!-- Bootstrap 3.3.2 JS -->
    <script src="/dist/js/bootstrap.min.js" type="text/javascript"></script>
    <!-- Bootstrap Datepicker JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.14.30/js/bootstrap-datetimepicker.min.js" type="text/javascript"></script>

    <!-- InputMask -->
    <script src="/plugins/input-mask/jquery.inputmask.js" type="text/javascript"></script>
    <script src="/plugins/input-mask/jquery.inputmask.date.extensions.js" type="text/javascript"></script>
    <script src="/plugins/input-mask/jquery.inputmask.extensions.js" type="text/javascript"></script>

    <!-- ChartJS 1.0.1 -->
    <script src="/plugins/chartjs/Chart.min.js" type="text/javascript"></script>
	  <!-- Slimscroll -->
    <script src="/plugins/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <!-- FastClick -->
    <script src='/plugins/fastclick/fastclick.min.js'></script>
    <!-- AdminLTE App -->
    <script src="/dist/js/app.min.js" type="text/javascript"></script>
    <!-- Custom Script -->
    <script src="/dist/js/custom.js" type="text/javascript"></script>
    <!-- jquery scrollbar Script -->
    <script src="/dist/js/jquery.scrollbar.min.js" type="text/javascript"></script>
	 <!-- custom validation Script -->
	<script src="/dist/js/validation.js"></script>
    
	
    <script type="text/javascript">

    $('.displayNone').hide();


    
$(function(){
	
	$(document).keypress(
    function(event){
     if (event.which == '13') {
        event.preventDefault();
      }


    })});
	
	


$('.cusnote').change(function(e){

	 $('#note').val($(this).val());
	
});
	

$('#savenote').click(function(e){
	e.preventDefault();
 if(page_has_error()){
	var btn = $(this)
	  	btn.button('loading');
	  	
	  var data = {
		      "action": "myprofile",
		      "mode" : "update"
		    };
	 	    data = $("#myprofileform").serialize() + "&" + $.param(data);
	 	    if($('#fname').val()==''){

	 	    	 $("#error").show();
	 			  $("#texterror").html('Please enter valid first name');
	 			  setTimeout(function(){ $('#error').hide(); }, 10000);
	 			  btn.button('reset');
	 			  return false;	
    	    }
	 	   
		    $.ajax({
		      type: "POST",
		      dataType: "json",
		      url: "/plan/myprofileJSON", 
		      data: data,
		      success: function(data) {
	  		      if(data['ecode']=='0'){


	   					$('#savenote').html('Saved');
	   		    		
						 setTimeout(function(){  $('#savenote').html('Save My Notes'); }, 10000);	

					  
				  }else{
					 $("#error").show();
  	 			  $("#texterror").html('Oops!  Looks like something went wrong.  Please try again later.');
  	 			  setTimeout(function(){ $('#error').hide(); }, 10000); 
					
   		      }
		      },
		      error: function(xhr, textStatus, errorThrown){
		          alert('Oops!  Looks like something went wrong.  Please try again later.');
		         
		       },
		       
		  		complete: function(xhr, textStatus){
		  		  btn.button('reset');
		  		}
		    });
		    return false;
	}else{
		$('#page_error').show();
		setTimeout(function(){ $('#page_error').hide();}, 10000);
		return false;
	}
      
});






$('#myprofile-next').click(function(e){
	e.preventDefault();
 if(page_has_error()){
	var btn = $(this)
	  	btn.button('loading');
	  	
	  var data = {
		      "action": "myprofile",
		      "mode" : $(this).val()
		    };
	 	    data = $("#myprofileform").serialize() + "&" + $.param(data);
	 	    if($('#fname').val()==''){

	 	    	 $("#error").show();
	 			  $("#texterror").html('Please enter valid first name');
	 			  setTimeout(function(){ $('#error').hide(); }, 10000);
	 			  btn.button('reset');
	 			  return false;	
    	    }
	 	   
		    $.ajax({
		      type: "POST",
		      dataType: "json",
		      url: "/plan/myprofileJSON", 
		      data: data,
		      success: function(data) {
	  		      if(data['ecode']=='0'){
 					window.location.href="/plan/major";
					  
				  }else{
					
					  window.location.href="/plan/major";
   		      }
		      },
		      error: function(xhr, textStatus, errorThrown){
		    	  window.location.href="/plan/major";
		         
		       },
		       
		  		complete: function(xhr, textStatus){
		  		  btn.button('reset');
		  		}
		    });
		    return false;
	}else{
		$('#page_error').show();
		setTimeout(function(){ $('#page_error').hide();}, 10000);
		return false;
	}
      
});
	
    $('#myprofile-submit').click(function(e){
		e.preventDefault();
	 if(page_has_error()){
		var btn = $(this)
   	  	btn.button('loading');
    	  	
  	  var data = {
    		      "action": "myprofile",
    		      "mode" : $(this).val()
    		    };
    	 	    data = $("#myprofileform").serialize() + "&" + $.param(data);
    	 	    if($('#fname').val()==''){
   
    	 	    	 $("#error").show();
    	 			  $("#texterror").html('Please enter valid first name');
    	 			  setTimeout(function(){ $('#error').hide(); }, 10000);
    	 			  btn.button('reset');
    	 			  return false;	
        	    }
    	 	   
    		    $.ajax({
    		      type: "POST",
    		      dataType: "json",
    		      url: "/plan/myprofileJSON", 
    		      data: data,
    		      success: function(data) {
    	  		      if(data['ecode']=='0'){

    	  		      $("#success").show();
       	 			  $("#textsuccess").html('Your profile information has been saved');
       	 			  setTimeout(function(){ $('#success').hide(); }, 10000); 
					  btn.button('reset');
					  $('#myprofile-submit').val('update');
   	  		  		  btn.button('complete');	
   	  			 	swal({   title: "Success!",   text: "Your profile information has been saved",   type: "success",   confirmButtonText: "Close" });
   	  		   				  
						
  					  
  				  }else{
  					 $("#error").show();
      	 			  $("#texterror").html('Oops!  Looks like something went wrong.  Please try again later.');
      	 			  setTimeout(function(){ $('#error').hide(); }, 10000); 
  					btn.button('reset');
       		      }
    		      },
    		      error: function(xhr, textStatus, errorThrown){
    		          alert('Oops!  Looks like something went wrong.  Please try again later.');
    		         btn.button('reset');
    		       },
    		       
   		  		complete: function(xhr, textStatus){
   		  		  
   		  		}
    		    });
    		    return false;
		}else{
			$('#page_error').show();
			setTimeout(function(){ $('#page_error').hide();}, 10000);
			return false;
		}
          
  });
  
  function page_has_error(){
	var cnt =0;
	$('[data-haserror="yes"]').each(function() {
		cnt+=1;
	});
	if(cnt>0)
		return false;
	else
		return true;
}
  
  
  
    
    $(function () {
        $('#datetimepicker1').datetimepicker();
     });
    </script>
<style>	
	.has_error{background-color:#f3cb5f}
</style>



<script>
     $('.targetDiv').hide();

     $(function(){
           $('.showSingle').click(function(){
             var index = $(this).parent().index(),
                 newTarget = $('.targetDiv').eq(index);
             $('.targetDiv').not(newTarget).fadeOut('fast');
             newTarget.delay('fast').fadeToggle('fast');
             return false;
           });
           $('.targetDiv').click(function(e){
             e.stopPropagation();
           });

       });
     $(function(){
       $(document).click(function(){
         var $el = $(".targetDiv");
         if($el.is(":visible")){
           $el.fadeOut(200);
         }
       });
     });

   </script>

<!-- Feedbacify -->
<script type="text/javascript">
var fby = fby || [];
fby.push(['showTab', {id: '9871', position: 'right', color: '#EB0000'}]);

(function () {
   var f = document.createElement('script'); f.type = 'text/javascript'; f.async = true;
   f.src = '//cdn.feedbackify.com/f.js';
   var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(f, s);
})();
</script>


<!-- Fixed container - Mynotes and social media -->
<script>
var fixmeTop = $('.myNotes').offset().top;
$(window).scroll(function() {
    var currentScroll = $(window).scrollTop() + 60;
    if (currentScroll >= fixmeTop) {
        $('.myNotes').css({
            position: 'fixed',
            top: '60px',
            right: '20'
        });
    } else {
        $('.myNotes').css({
            position: 'static'
        });
    }
});
</script>
