
      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper pscontentContainer">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Personal Statement
            <small>What Makes a Great Personal Statement</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="/user/index"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li><a href="/plan/index"><i class="ion ion-gear-b"></i> Plan</a></li>
            <li class="active">Personal Statement</li>
          </ol>
        </section>

        
        <!-- Main content -->

        <section class="pscontentContainer ">
          
            <div id="chooseLevel" class="pscontainer1">
              <div class=" col-lg-6 col-lg-offset-3">
                <h1>Select your Game level</h1>
                <div class="row" >
                  <div class="col-md-4">
                    <a href="/plan/level1" >
                      <div class="levelBox bg-blue-gradient ">
                        Part 1 <span class="levelStars starDefault"></i></span>
                      </div>
                    </a>
                  </div>
                  <div class="col-md-4">
                    <a href="/plan/level2" >
                    <div class="levelBox bg-purple-gradient">
                      Part 2 <span class="levelStars starDefault"></span>
                    </div>
                    </a>
                  </div>
                  <div class="col-md-4">
                    <a href="/plan/level3" >
                      <div class="levelBox bg-maroon-gradient">
                        Part 3 <span class="levelStars starDefault"></span>
                      </div>
                    </a>
                  </div>
                </div>
                <hr style="border-top:1px solid #ccc;" />
                 <div class="row text-center">
                  <div class="col-lg-12">
                    <?php if(isset($this->summary) && $this->summary=='true'){?>
                    
                    <button type="submit" class="btn btn-danger  pull-left" id="summary"><i class="fa fa- fa-envelope" style="padding-right:5px;"></i> Email Overall Summary</button> 
    				        <button type="submit" class="btn btn-danger text-center" id="replay-game" style="position:relative; left:-40px;">Start Over</button> 
                    
                    <?php }?>
                  
                    <a href="/plan/resumehome" class="btn btn-danger pull-right">Next: Resume</a>
                  </div>
                </div>
            </div>
            </div>
        </section>
      </div><!-- /.content-wrapper -->

      
    </div><!-- ./wrapper -->

    
    
    <div class="modal fade" id="success" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header btn-danger">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title " id="myModalLabel">Success</h4>
	      </div>
	      <div class="modal-body">
	        Your personal statement information has been sent to your email id.
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	        <!-- <button type="button" class="btn btn-primary">Save changes</button>-->
	      </div>
	    </div>
	  </div>
	</div>
      
       <div class="modal fade" id="failure" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header btn-danger">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title " id="myModalLabel">Failure</h4>
	      </div>
	      <div class="modal-body">
	        Oops!  Looks like something went wrong.  Please try again later.
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	        <!-- <button type="button" class="btn btn-primary">Save changes</button>-->
	      </div>
	    </div>
	  </div>
	</div>
      
    
    <!-- REQUIRED JS SCRIPTS -->

    <!-- jQuery 2.1.4 -->
    <script src="/plugins/jQuery/jQuery-2.1.4.min.js"></script>
    <!-- Bootstrap 3.3.2 JS -->
    <script src="/dist/js/bootstrap.min.js" type="text/javascript"></script>
    <!-- InputMask -->
    <script src="/plugins/input-mask/jquery.inputmask.js" type="text/javascript"></script>
    <script src="/plugins/input-mask/jquery.inputmask.date.extensions.js" type="text/javascript"></script>
    <script src="/plugins/input-mask/jquery.inputmask.extensions.js" type="text/javascript"></script>

    <!-- ChartJS 1.0.1 -->
    <script src="/plugins/chartjs/Chart.min.js" type="text/javascript"></script>

	  <!-- Slimscroll -->
    <script src="/plugins/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <!-- FastClick -->
    <script src='/plugins/fastclick/fastclick.min.js'></script>
    <!-- AdminLTE App -->
    <script src="/dist/js/app.min.js" type="text/javascript"></script>
    <!-- Custom Script -->
    <script src="/dist/js/custom.js" type="text/javascript"></script>

    <!-- jquery scrollbar Script -->
    <script src="/dist/js/jquery.scrollbar.min.js" type="text/javascript"></script>
    
