
<!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper pscontentContainer">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            <i class="fa fa-file-text"></i> Resume
            <small>Extracurricular Activities, Work, Awards</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="/user/index"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li><a href="/plan/index"><i class="ion ion-gear-b"></i> Plan</a></li>
            <li class="active">Resume</li>
          </ol>
        </section>
<!-- Main content -->
        <section >
          <div id="welcome" >
            <div class="pscontentArea row">
            <!-- Right side content -->
            <div class="col-lg-3 col-lg-push-9 col-md-12 col-sm-12 col-xs-12 rightSideContainer">
                <div class="box box-warning ">
                    <div class="box-header with-border">
                      <h3 class="box-title"><i class="fa fa-file-video-o"></i> Hear from An Expert</h3>
                    </div>
                  <div class="box-body" >
                    <!-- <div class="embed-responsive embed-responsive-16by9">
                      <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/sqpw3NynsTE"></iframe>
                    </div>-->
                    <div id="myCarousel" class="carousel slide">
                      <!--<ol class="carousel-indicators">
                        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                        <li data-target="#myCarousel" data-slide-to="1" class=""></li>
                      </ol>-->
                      <div class="carousel-inner">
                        <div class="item active">
                          <div class="embed-responsive embed-responsive-16by9">
                            <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/UWbU-QhKuuU?showinfo=0&amp;" allowfullscreen></iframe>
                          </div>
                        </div>
                        
                      </div>
                      <!-- <a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>
                      <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a> -->
                    </div>
                  
                  </div><!-- /.box-body -->
                </div><!-- /.box -->           
                <div id="myAffix" class="box box-default visible-lg" data-spy="affix" data-offset-top="300">
                    <div class="box-header with-border">
                      <h3 class="box-title"><i class="fa fa-pencil"></i> My Notes</h3>
                    </div>
                  <div class="box-body">
                        <textarea class="form-control" rows="3" placeholder="Coming Soon..." readonly="readonly"></textarea>
                        <button class="btn btn-default marginTop" disabled="true">Save My Notes </button>
                  </div><!-- /.box-body -->
                </div><!-- /.box -->
                <!-- social media -->
                <div id="myAffix1" class="box box-solid visible-lg" data-spy="affix" data-offset-top="300">
                    <div class="box-header ">
                      <h3 class="box-title"><i class="fa fa-share-alt"></i> Follow Us</h3>
                      <div class=" pull-right " >
                        <div  class="fixedBtn"><a href="https://www.facebook.com/askuceazy" class="bg-facebook" target="_blank" title="Facebook"><i class="fa fa-facebook"></i></a></div>
                        <div class="fixedBtn"><a href="https://twitter.com/Uaskuceazy?lang=en" class="bg-twitter" target="_blank" title="Twitter"><i class="fa fa-twitter"></i></a></div>
                        <div class="fixedBtn"><a href="https://www.linkedin.com/company/uceazy" class="bg-linkedin" target="_blank" title="Linkedin"><i class="fa fa-linkedin"></i></a></div>

						<!-- <div class="fixedBtn"><a href="#" class="bg-google-plus"><i class="fa fa-google-plus"></i></a></div>
                        <div class="fixedBtn"><a href="#" class="bg-instagram"><i class="fa fa-instagram"></i></a></div>
                        <div class="fixedBtn"><a href="#" class="bg-pinterest"><i class="fa fa-pinterest"></i></a></div>-->
                      </div>  
                    </div>
                </div>
            </div>
            <!-- ./Right side content -->

            <div class="col-lg-9 col-lg-pull-3 col-md-12 col-sm-12 col-xs-12">
              <p class="lead"><strong>Before you start the Resume section, here are a few things you should know...</strong></p>
              <ul>
                <li><strong>None</strong> of the CSU's require students to list out extracurricular activities
                <ul>
                  <li>Some campuses, however, ask you to approximate how many hours you spent in extracurricular activities (employment, community service, athletics, arts, clubs, etc.) over the last 12 months
                  </li>
                </ul>
                </li>
				
				<li><strong>All</strong> nine UC undergraduate campuses require students to fill out their "Activities and Awards" section in order to understand how students spend their time outside of school
                <ul>
				   
                  <li>Categories Include:
					  <ul>
							<li>Educational Prep Programs</li>
							<li>Volunteer & Community Service</li>
							<li>Work Experience</li>
							<li>Awards & Honors</li>
							<li>Extracurricular Activities </li>
							<li>Coursework Other Than A-G </li>
					  </ul>
                  </li>
				  <li>Students are allowed only 5 entries in each category</li>
				  <li>The word limit for describing each activity is 160 characters</li>
                </ul>
                </li>
				
				
              <p class="lead">If you're feeling ready, feel free to start working on your Resume section here <button type="submit" class="btn btn-lg btn-danger" onClick="parent.location='/plan/resume'" >Start Building Resume</button>  
              </p>
              
            </div>
    
            

          </div><!-- /.row -->

          <div class="clearfix"></div>
          <!-- My Notes for devices -->
          <div class="rightSideContainer">
            <div id="myAffix" class="box box-default hidden-lg" >
                    <div class="box-header with-border">
                      <h3 class="box-title"><i class="fa fa-pencil"></i> My Notes</h3>
                    </div>
                  <div class="box-body">
                        <textarea class="form-control" rows="3" placeholder="Coming Soon..." name="note" id="note" readonly="readonly"><?php if(isset($res['notes'][0])){ echo $res['notes'][0];}?></textarea>
                        <button class="btn btn-default marginTop"  id="savenote" disabled="true">Save My Notes </button>
                  </div><!-- /.box-body -->
                </div><!-- /.box -->
           </div>
        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->

      
       <div class="modal fade" id="success" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header btn-danger">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title " id="myModalLabel">Success</h4>
	      </div>
	      <div class="modal-body" id="modalsuccessbody">
	        Your Resume information has been saved into our database
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	        <!-- <button type="button" class="btn btn-primary">Save changes</button>-->
	      </div>
	    </div>
	  </div>
	</div>
      
       <div class="modal fade" id="failure" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header btn-danger">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title " id="myModalLabel">Failure</h4>
	      </div>
	      <div class="modal-body" id="modalfailbody">
	        Oops!  Looks like something went wrong.  Please try again later.
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	        <!-- <button type="button" class="btn btn-primary">Save changes</button>-->
	      </div>
	    </div>
	  </div>
	</div>
      
    
      <!-- Main Footer -->
     
      
    </div>

<!-- REQUIRED JS SCRIPTS -->

    <!-- jQuery 2.1.4 -->
    <script src="/plugins/jQuery/jQuery-2.1.4.min.js"></script>
    <!-- Bootstrap 3.3.2 JS -->
    <script src="/dist/js/bootstrap.min.js" type="text/javascript"></script>
    <!-- InputMask -->
    <script src="/plugins/input-mask/jquery.inputmask.js" type="text/javascript"></script>
    <script src="/plugins/input-mask/jquery.inputmask.date.extensions.js" type="text/javascript"></script>
    <script src="/plugins/input-mask/jquery.inputmask.extensions.js" type="text/javascript"></script>

    <!-- ChartJS 1.0.1 -->
    <script src="/plugins/chartjs/Chart.min.js" type="text/javascript"></script>

    <!-- Slimscroll -->
    <script src="/plugins/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <!-- FastClick -->
    <script src='/plugins/fastclick/fastclick.min.js'></script>
    <!-- AdminLTE App -->
    <script src="/dist/js/app.min.js" type="text/javascript"></script>
    <!-- Custom Script -->
    <script src="/dist/js/custom.js" type="text/javascript"></script>

    <!-- jquery scrollbar Script -->
    <script src="/dist/js/jquery.scrollbar.min.js" type="text/javascript"></script>
	<script src="/dist/js/validation.js"></script>
