<!-- Header -->
<header id="top" class="headerbg_essayReview">
    <div class="text-vertical-center bannerText1">
        <!-- <h1>UC and CSU Admissions Made Easy</h1>
        <a href="/search/eazy"><h2>Try It Now</h2></a>
  <h2><font color="white">Free for Fall 2016 Freshman Admission Applicants</font></h2>        -->
      <h1>Is the UC Essay giving you writer’s block?</h1>
      <h2 style="font-size:24px;">We can help</h2>
      <a href="/buyservice/buyEssay" class="btn btn-default1 btn-lg" style="margin-right:10px;">Sign up for Essay Review </a>
      <!-- <a href="/search/eazy" class="btn btn-default1 btn-lg" >Try Our App</a>-->
    </div>
</header>

<!-- About -->
<section id="intro" class="bluebg1 bg-contact">
    <div class="container">
        <div class="row ">
            <div class="col-lg-12 text-center ">
              <h3>How can you distinguish yourself from all the other UC Berkeley applicants (who averaged a 4.4 weighted GPA)?</h3>
              <h3>You need a great essay that highlights your persistence, passion and desire to give back. </h3>
            </div>
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
</section>

<!-- Team -->
<section id="team" class="team">
    <div class="container">
        <div class="row">
            <div class="col-lg-10 col-lg-offset-1 text-center">
                <h2>Our Essay Review Team</h2>
                <hr class="small">
                <p class="lead">Our reviewers are experts on evaluating UC essays. They helped numerous students get accepted into top UC universities.</p>
                <div class="row">
                  <div class="contentPadding essayReview">
                    <div class="col-md-4 col-xs-12" >
                      <div class="reviewTeamContainer">
                        <div style="background:#eaeaea;">
                          <img class=" img-responsive" src="../dist/img/team/stacey.jpg" alt="Stacey Ho Ching"/>
                          <p style="">Stacey Ho Ching</p>
                          <div class="clearfix"></div>  
                        </div>
                        <div class="clearfix"></div>
                        <div style="text-align:left;">
                          <ul >
                            <li>UCLA Undergraduate</li>
                            <li>Masters in Counseling from University of Maryland</li>
                            <li>Admissions Advising certificate from Berkeley</li>
                            <li>Over 10 years experience in college counseling and essay reviews.</li>
                          </ul>
                        </div>
                       </div>
                    </div>
                    <div class="col-md-4 col-xs-12" >
                      <div class="reviewTeamContainer">
                        <div style="background:#eaeaea;">
                          <img class=" img-responsive" src="../dist/img/team/shari.jpg" alt="Shari Schussel"/>
                          <p style="">Shari Schussel</p>
                          <div class="clearfix"></div>  
                        </div>
                        <div class="clearfix"></div>
                        <div style="text-align:left;">
                          <ul >
                            <li>10 years college counseling experience</li>
                            <li>Masters in Education Counseling</li>
                            <li>Passion to help students write great UC Essays</li>
                          </ul>
                        </div>
                       </div>
                    </div>
                    <div class="col-md-4 col-xs-12" >
                      <div class="reviewTeamContainer">
                        <div style="background:#eaeaea;">
                          <img class=" img-responsive" src="../dist/img/team/daniel.jpg" alt="Daniel Zweier"/>
                          <p style="">Daniel Zweier</p>
                          <div class="clearfix"></div>  
                        </div>
                        <div class="clearfix"></div>
                        <div style="text-align:left;">
                          <ul >
                            <li>UC Graduate</li>
                            <li>Professional writer / journalist / educator</li>
                            <li>Passion to help students craft well-written and insightful essays.</li>
                          </ul>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
            </div>
            <!-- /.col-lg-10 -->
        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->
</section>

<!-- How we do it? -->
<section class="bg-essayreview">
    <div class="container">
        <div class="row text-center">
            <div class="col-lg-10 col-lg-offset-1">
              <h2 >User Testimonials</h2>
              <hr class="small">
                <p>"Thank you UCEazy for your great essay service. Along with it being affordable, it is also very easy to use. The reviews themselves are detailed and constructive, giving my daughter a clear idea of what she needs to do to get her essays ready for submission." <br />– Govind (parent in Sunnyvale, CA)</p>
                 <p>"UC personal statements are so stressful because it seems like everyone has something different to say about them. Having UCEazy's team of former UC students and professional editors review my essays not only made them much stronger, but also gave me the peace of mind that I was on the right track in regards to what the UCs are looking for." <br />–Sruthi (student in Sunnyvale, CA) </p>
              
            </div>
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
</section>

<!-- What we’d like from you -->
<section class="bglightgray uceazyappsection">
    <div class="container">
        <div class="row ">
            <div class="col-lg-12 ">
              <h2 class="text-center">Our Dual Process</h2>
              <hr class="small">
                <p>Our specialized method consists of a two-step process with two reviewers who go through your personal statements and provide feedback.</p>
                <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12  essayProcessContent" >
                <p class="blue" style="padding:10px; color:white;">The first reviewer is a current or former UC student who has experience in editing, the English language, and the UC system itself. Each one wrote a personal statement and got into a University of California.</p>
                </div>
                <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12 essayProcessContent" >
                <p class="bg-green" style="padding:10px; color:white;">
                  The second step of the review builds upon the first — an experienced editor will look over the comments of the first and add more, focusing on clarity and the story that best represents you.
                  </p> 
                </div>
                <p>
                  Other services offer either a student reviewer, who may be excellent at writing but not reviewing, or a professional editor, who will give precise feedback but does not have experience with the specific UC prompts.
                </p> 
                <p>We have both, and your essay will be stronger because of it.</p>
              </div>
              
            </div>
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
</section>

<!-- Feedbackify -->  
<script type="text/javascript">
var fby = fby || [];
fby.push(['showTab', {id: '9871', position: 'right', color: '#EB0000'}]);

(function () {
   var f = document.createElement('script'); f.type = 'text/javascript'; f.async = true;
   f.src = '//cdn.feedbackify.com/f.js';
   var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(f, s);
})();
</script>     
