 <?php 
 use Zend\Session\SessionManager;
 use Zend\Session\Container;
 use Common\Utilities;
 use Common\Utilities\Languages;
 $session = new Container('user');
 $globalSession=new Container('global');
 $lang=$globalSession->lang;
 ?>

<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <link rel="icon" type="image/png" href="dist/img/favicon.ico">
    <title>UC and CSU Admissions Made Easy</title>
    
    <script src="/dist/sweetalert.min.js"></script>
     <link rel="stylesheet" type="text/css" href="/dist/sweetalert.css">
    
    <!-- Tell the browser to be responsive to screen width -->
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

    <meta name="description" content="UCEazy - UC and CSU Admissions Made Easy. An affordable software based solution for applying to public universities. UCEazy application is easy to use, understand and fit into a high school student's hectic lifestyle.  " />
    <meta name="keywords" content="UC admission, UC admissions, UC application, UC Essay, UC Personal Statement, Essay Review, UC admission help, UC admission advice, UC admission guidance, CSU admission, CSU admissions , CSU application, CSU admission help, CSU admission, advice, CSU admission guidance, GPA, GPA Calculator, UC GPA, CSU GPA, SAT to ACT conversion calculator, ACT to SAT conversion calculator , UC Activities and Awards, UC Resume, UC Cost of Attendance, UC Attendance Cost, CSU Cost of Attendance , CSU Attendance Cost, CSU application fee, CSU application cost, UC application fee, UC application cost,UC app costs, UC application costs, CSU app costs , CSU application costs, Explore, Plan, College Essay examples, College Essay, Custom Writing, Essay Writing, College Application Essay, Essay Examples, UC Application Essay, UC Essay, Creative writing, UC Essay prompt, College Essay, Format, Financial Aid, College Admission" />

    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <!-- Font Awesome Icons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!--<link href="dist/font-awesome-4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />-->
    <!-- Ionicons -->
    <!--<link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />-->
    <link href="/dist/ionicons-2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="/dist/css/AdminLTE.css" rel="stylesheet" type="text/css" />
    <link href="/dist/css/skins/skin-black.css" rel="stylesheet" type="text/css" />
    <!-- Custom style -->
    <link href="/dist/css/styles.css" rel="stylesheet" type="text/css" />
    <!-- Jquery Scroll bar style -->
    <link href="/dist/css/jquery.scrollbar.css" rel="stylesheet" type="text/css" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
   <body  id="WSuceazy" class="skin-black fixed sidebar-collapse">
    <!-- Main Header -->
    
    <div  class="main-header " >
      <!-- Main Header -->
        <nav class="navbar navbar-static-top" role="navigation" >
        <!-- Logo -->
        <a href="/" class="logo logoHome">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <!-- <span class="logo-mini"><b>A</b>LT</span>-->          
          <!-- logo for regular state and mobile devices -->
          <img src="/dist/img/logo-uceazy.png"  />
        </a>

        <!-- Header Navbar -->
          <!-- Sidebar toggle button-->
          
          <!-- Navbar Right Menu -->
          <!-- Navbar Right Menu -->
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <!-- language 
              <li class="dropdown notifications-menu">
               
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-language"></i> Language
                </a>
                <ul class="dropdown-menu">
                  <li class="header">Select Language</li>
                  <li>
                   
                    <ul class="menu">
                      <li>
                        <a href="/?lang=en">
                          <i class="fa fa-language"></i> English
                        </a>
                      </li>
                      <li>
                        <a href="/?lang=sp">
                          <i class="fa fa-language"></i> Espanol
                        </a>
                      </li>
                    </ul>
                  </li>
                </ul>
              </li>-->
              <!-- Signin -->
              <li>
                <!-- Menu toggle button -->
                
              </li>

              <?php 
              
              if(!isset($session->username)){
              ?>
              
              <li>
                <!-- Menu toggle button -->
                <a href="/user/signin" >
                  <i class="fa fa-sign-in"></i> Sign in
                </a>
              </li>
              <!-- Signup -->
              <li>
                <!-- Menu toggle button -->
                <a href="/user/signup" >
                  <i class="fa fa-pencil-square-o"></i> Sign up
                </a>
              </li>      
              <?php }else{?>
              
              <li>
                <!-- Menu toggle button -->
                <a href="/user/index" >
                  <i class="fa fa-sign-in"></i> Home
                </a>
              </li>
              <!-- Signup -->
              <li>
                <!-- Menu toggle button -->
                <a href="/user/logout" >
                  <i class="fa fa-pencil-square-o"></i>Log out
                </a>
              </li>  
              <?php }?>        
            </ul>
          </div>
          </div>
          <div class="clearfix"></div>
        </nav>
            
      <!-- Left side column. contains the logo and sidebar -->
      <aside class="main-sidebar">

        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
          <!-- Sidebar Menu -->
          <ul class="sidebar-menu">
            <li class="header">Menu</li>
            <!-- Optionally, you can add icons to the links -->
            <li ><a href="/"><i class='fa fa-home'></i> <span>Home</span></a></li>       
            <li class="treeview"><a href="/#servicesmodule"><i class="fa fa-circle-o"></i> <span>UCEazy Services</span><i class="fa fa-angle-left pull-right"></i></a>
                <ul class="treeview-menu">
                  <li><a href="/index/essayreview"><i class='fa fa-compass'></i> <span>Essay Review</span></a></li>
                </ul>
            </li>     

            <li class="treeview"><a href="/#appmodule"><i class="fa fa-circle-o"></i> <span>UCEazy Modules</span><i class="fa fa-angle-left pull-right"></i></a>
                <ul class="treeview-menu">
                  <li><a href="/#explore"><i class='fa fa-compass'></i> <span>Explore</span></a></li>
                  <li><a href="/#plan"><i class='fa fa-gear'></i> <span>Plan</span></a></li>
                </ul>
            </li>     
            
            <li><a href="/#story"><i class='fa fa-book'></i> <span>Our Story</span></a></li>
            <li><a href="/#team"><i class='fa fa-group'></i> <span>Our Team</span></a></li>
            <li><a href="/#expert"><i class='fa fa-user'></i> <span>For School Administrators</span></a></li>
            <li><a href="/#contact"><i class='fa fa-location-arrow'></i> <span>Contact Us</span></a></li>          </ul>            
        </section>
        <!-- /.sidebar -->
      </aside>