<?php 
use Zend\Session\SessionManager;
use Zend\Session\Container;
$session = new Container('user');
?>
<!DOCTYPE html>
  <head>
     <meta charset="UTF-8">
	<link rel="icon" type="image/png" href="dist/img/favicon.ico">
    <title>UC and CSU Admissions Made Easy</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

     <meta name="description" content="UCEazy - UC and CSU Admissions Made Easy. An affordable software based solution for applying to public universities. UCEazy application is easy to use, understand and fit into a high school student's hectic lifestyle.  " />
    <meta name="keywords" content="UC admission, UC admissions, UC application, UC Essay, UC Personal Statement, Essay Review, UC admission help, UC admission advice, UC admission guidance, CSU admission, CSU admissions , CSU application, CSU admission help, CSU admission, advice, CSU admission guidance, GPA, GPA Calculator, UC GPA, CSU GPA, SAT to ACT conversion calculator, ACT to SAT conversion calculator , UC Activities and Awards, UC Resume, UC Cost of Attendance, UC Attendance Cost, CSU Cost of Attendance , CSU Attendance Cost, CSU application fee, CSU application cost, UC application fee, 
UC application cost,UC app costs, UC application costs, CSU app costs , CSU application costs, Explore, Plan, " />
   <script src="/dist/sweetalert.min.js"></script>
     <link rel="stylesheet" type="text/css" href="/dist/sweetalert.css">
    <!-- Bootstrap 3.3.4 -->
    <link href="/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <!-- Jquery UI -->
    <link href="/dist/css/jquery-ui.min.css" rel="stylesheet">

    <!-- Font Awesome Icons -->
    <!--<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />-->
    <link href="/dist/font-awesome-4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- Ionicons -->
    <!--<link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />-->
    <link href="/dist/ionicons-2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="/dist/css/AdminLTE.css" rel="stylesheet" type="text/css" />
    <link href="/dist/css/skins/skin-black.css" rel="stylesheet" type="text/css" />
    <!-- Custom style -->
    <link href="/dist/css/adminstyle.css" rel="stylesheet" type="text/css" />

    <!-- Jquery Scroll bar style -->
    <link href="/dist/css/jquery.scrollbar.css" rel="stylesheet" type="text/css" />
    <script src="/dist/js/buyService.js" type="text/javascript"></script>
   
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    
   
<script> window.jQuery || document.write('<script src="/plugins/jQuery/jQuery-2.1.4.min.js"><\/script>')</script>
    
    
    
    
    
    
  </head>
  
  <body class="skin-black fixed sidebar-collapse">
    <div class="wrapper">

      <!-- Main Header -->
      <header class="main-header">
      <!-- Logo -->
        <a href="/plan/gpa" class="logo">
          <!-- mini logo for sidebar mini 50x50 pixels -->
		  <!-- <span class="logo-mini"><b>A</b>LT</span>-->          
		  <!-- logo for regular state and mobile devices -->
          <span class="logo-lg"><img src="/dist/img/logo-uceazy-sm.png"</span>
        </a>

        <!-- Header Navbar -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Sidebar toggle button-->
          
          <!-- Navbar Right Menu -->
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <li>
                <!-- Menu toggle button -->
                <a href="https://uceazyblog.wordpress.com/" target="_blank" >
                  <i class="fa fa-rss-square"></i> Blog
                </a>
              </li>
              
              

              <!-- language 
              <li class="dropdown notifications-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-language"></i> Language
                  
                </a>
                <ul class="dropdown-menu">
                  <li class="header"><i class="fa fa-language"></i> English</li>
                  <li>
                    <ul class="menu">
                      <li>
                        <a href="#">
                          <i class="fa fa-language"></i> Espanol
                        </a>
                      </li>
                    </ul>
                  </li>
                </ul>
              </li>-->
              <!-- User Account Menu -->
              <li class="dropdown user user-menu">
                <!-- Menu Toggle Button -->
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <!-- The user image in the navbar-->
                  <img src="<?php echo $session->profile_picture;?>" class="user-image" alt="User Image"/>
                  <!-- hidden-xs hides the username on small devices so only the image appears. -->
                  <span class="hidden-xs"><?php echo $session->username;?></span>
                </a>
                <ul class="dropdown-menu">
                  <!-- The user image in the menu -->
                  <li class="user-header">
                    <img src="<?php echo $session->profile_picture;?>" class="img-circle" alt="User Image" />
                    <p>
                      <?php echo $session->username;?>
                      <!-- <small>Subtitle</small>-->
                    </p>
                  </li>
                  <!-- Menu Body -->
                  <li class="user-body">
                    <div class="col-xs-12 text-center">
                      <a href="/user/changepassword">Change Password</a>
                    </div>
                    
                  </li>
                  <!-- Menu Footer-->
                  <li class="user-footer">
                    <div class="pull-left">
                      <a href="/user/preference" class="btn btn-default btn-flat">Preferences</a>
                    </div>
                    <div class="pull-right">
                      <a href="/user/logout" class="btn btn-default btn-flat">Sign out</a>
                    </div>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </nav>
      </header>
      <!-- Left side column. contains the logo and sidebar -->
      <aside class="main-sidebar">

        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
          <!-- Sidebar Menu -->
          <ul class="sidebar-menu">
            <li class="header">Menu</li>
            <!-- Optionally, you can add icons to the links -->
            <li class="active"><a href="/user/index"><i class="fa fa-dashboard"></i><span>Dashboard</span></a></li>
            <li><a href="/search/advexplorer"><i class='fa fa-compass'></i> <span>Explore</span></a></li>
            <li class="treeview active">
              <a href="/plan/index" class="plan"><i class='fa fa-gear'></i> <span>Plan</span> <i class="fa fa-angle-left pull-right"></i></a>
              <ul class="treeview-menu">
                <li><a href="/plan/myprofile"><i class="fa fa-smile-o"></i> My Profile</a></li>
                <li><a href="/plan/major"><i class="fa fa-book"></i> Major</a></li>
                <li><a href="/plan/testing"><i class="fa fa-wrench"></i> Testing </a></li>
                <li><a href="/plan/gpa"><i class="fa fa-calculator"></i> GPA</a></li>
                <li><a href="/plan/myuceazy"><i class="fa fa-user"></i> My Counselor</a></li>
                <li><a href="/plan/organisation"><i class="fa fa-calendar"></i> Organizer</a></li>
                <li><a href="/plan/costs"><i class="fa fa-dollar"></i> Costs</a></li>
                <li><a href="/plan/personal"> <i class="fa fa-puzzle-piece"></i> Personal statement</a></li>
                <li><a href="/plan/resume"><i class="fa fa-file-text"></i> Resume</a></li>
              </ul>
            </li>
          </ul><!-- /.sidebar-menu -->
        </section>
        <!-- /.sidebar -->
      </aside>
     

     
     
     <div class="modal fade" id="essay_history_modal" tabindex="-1" role="dialog"  aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
            
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Essay Service History</h4>
                </div>
					<div class="modal-body">
						<table class="table table-bordered courseTable" id="essay_his_table">
							<thead>
								<tr>
									<th>S.No</th>
									<th>Services</th>
									<th>Submitted On</th>
									<th>Reviewed On</th>
									<th>Cost</th>									
									<th>Status</th>
									<th>Action</th>
								</tr>
							</thead>
							<tbody>
							</tbody>
						</table>
					</div>
					<div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>                    
                </div>
            </div>
        </div>
    </div>
     
     
     
     
     
<style>
.two-column{	
    margin: 0;
    padding: 0;    
}

.two-column li{	
	display: inline-block;
    width: 48%;
    margin: 2px;
    padding: 0;
    vertical-align: top;   
    display: table-cell;   
   
}

</style>
     
