<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <link rel="icon" type="image/png" href="dist/img/favicon.ico">
    <title>UC and CSU Admissions Made Easy</title>
    
    <script src="/dist/sweetalert.min.js"></script>
     <link rel="stylesheet" type="text/css" href="/dist/sweetalert.css">
    
    <!-- Tell the browser to be responsive to screen width -->
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <!-- Font Awesome Icons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!--<link href="dist/font-awesome-4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />-->
    <!-- Ionicons -->
    <!--<link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />-->
    <link href="/dist/ionicons-2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="/dist/css/AdminLTE.css" rel="stylesheet" type="text/css" />
    <link href="/dist/css/skins/skin-black.css" rel="stylesheet" type="text/css" />
    <!-- Custom style -->
    <link href="/dist/css/styles.css" rel="stylesheet" type="text/css" />
    <!-- Jquery Scroll bar style -->
    <link href="/dist/css/jquery.scrollbar.css" rel="stylesheet" type="text/css" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
   <body  id="WSuceazy" class="skin-black fixed sidebar-collapse">
    <!-- Main Header -->
    
    <div  class="main-header " >
      <!-- Main Header -->
        <nav class="navbar navbar-static-top" role="navigation" >
        <!-- Logo -->
        <a href="/" class="logo logoHome">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <!-- <span class="logo-mini"><b>A</b>LT</span>-->          
          <!-- logo for regular state and mobile devices -->
          <img src="/dist/img/logo-uceazy1.png"  />
        </a>

        <!-- Header Navbar -->
          <!-- Sidebar toggle button-->
          
          <!-- Navbar Right Menu -->
          <!-- Navbar Right Menu -->
          <div class="navbar-custom-menu">
            
          </div>
          </div>
          <div class="clearfix"></div>
        </nav>
		 </div>
		 <hr class="small">
            <section id="feature" class="expert">
        <div class="container">
            <div class="row text-center" >
                
                    <img src="/dist/img/maintenance.gif" >
            <div style="position: absolute;  top: 54%;  left: 27%; "
			<strong><h3>Schedule Downtime</h3> 
				<p>We're busy pushing out some new concoctions and formulas. We'll be back soon...</p></strong>
				</div>
            </div>
                <!-- /.col-lg-10 -->
            </div>
            <!-- /.row -->
        <!-- /.container -->
    </section>
			
      <!-- Left side column. contains the logo and sidebar -->
      <aside class="main-sidebar">

        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
          <!-- Sidebar Menu -->
                     
        </section>
        <!-- /.sidebar -->
      </aside>
	  
	  
