<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <link rel="icon" type="image/png" href="dist/img/favicon.ico">
    <title>UC and CSU Admissions Made Easy</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <meta name="description" content="UCEazy - UC and CSU Admissions Made Easy. An affordable software based solution for applying to public universities. UCEazy application is easy to use, understand and fit into a high school student's hectic lifestyle.  " />
    <meta name="keywords" content="UC admission, UC admissions, UC application, UC Essay, UC Personal Statement, Essay Review, UC admission help, UC admission advice, UC admission guidance, CSU admission, CSU admissions , CSU application, CSU admission help, CSU admission, advice, CSU admission guidance, GPA, GPA Calculator, UC GPA, CSU GPA, SAT to ACT conversion calculator, ACT to SAT conversion calculator , UC Activities and Awards, UC Resume, UC Cost of Attendance, UC Attendance Cost, CSU Cost of Attendance , CSU Attendance Cost, CSU application fee, CSU application cost, UC application fee, 
UC application cost,UC app costs, UC application costs, CSU app costs , CSU application costs, Explore, Plan, " />
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <!-- Font Awesome Icons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!--<link href="dist/font-awesome-4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />-->
    <!-- Ionicons -->
    <!--<link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />-->
    <link href="/dist/ionicons-2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="/dist/css/AdminLTE.css" rel="stylesheet" type="text/css" />
    <link href="/dist/css/skins/skin-black.css" rel="stylesheet" type="text/css" />
    <!-- Custom style -->
    <link href="/dist/css/styles.css" rel="stylesheet" type="text/css" />
    <!-- Jquery Scroll bar style -->
    <link href="/dist/css/jquery.scrollbar.css" rel="stylesheet" type="text/css" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="login-page">
    <div class="container">
  
  
  
  <h2>Consolidated Channel Traffic</h2>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Incoming channel</th>
        <th>Total Visitors</th>
      </tr>
    </thead>
    <tbody>
    <?php 
    if(count($this->channeltrafic)>0){
    	foreach ($this->channeltrafic as $row) {
   ?>
    <tr>
        <td><?php echo $row['channelname'];?></td>
        <td><?php echo $row['total'];?></td>
      </tr>
   <?php  		
    	}
    }
    ?>
    </tbody>
  </table>
  
  <h2>Detailed Channel Traffic Count (Date wise)</h2>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Access Date</th>
          <th>PTA</th>
      	<th>SingTao</th>
        <th>FaceBook</th>
        <th>Youtube</th>
        <th>Fremont School</th>
        <th>Friend/Family</th><th>Total</th>
      </tr>
    </thead>
    <tbody>
    <?php 
    if(count($this->trafficdaywise)>0){
    	foreach ($this->trafficdaywise as $row) {
   ?>
    <tr>
        <td><?php echo $row['RegDate'];?></td>
        <td><?php echo $row['PTA'];?></td>
        <td><?php echo $row['SingTao'];?></td>
        <td><?php echo $row['FaceBook'];?></td>
         <td><?php echo $row['Youtube'];?></td>
        <td><?php echo $row['FremantSchool'];?></td>
        <td><?php echo $row['FriendFamily'];?></td>
         
        <td bgcolor="yellow"> <?php echo ($row['FaceBook']+$row['PTA']+$row['Youtube']+$row['FremantSchool']+$row['FriendFamily']+$row['SingTao']);?></td>
      </tr>
   <?php  		
    	}
    }
    ?>
    </tbody>
  </table>
  
  
  
  <h2>Consolidated Channel SignUp/SignIn</h2>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Register channel</th>
        <th>Total users</th>
      </tr>
    </thead>
    <tbody>
    <?php 
    if(count($this->total)>0){
    	foreach ($this->total as $row) {
   ?>
    <tr>
        <td><?php echo $row['regchannel'];?></td>
        <td><?php echo $row['total'];?></td>
      </tr>
   <?php  		
    	}
    }
    ?>
    </tbody>
  </table>
  
  
  
  <h2>Detailed SignUp Count (Date wise)</h2>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Reg Date</th>
        <th>PTA</th>
      	<th>SingTao</th>
        <th>FaceBook</th>
        <th>Youtube</th>
        <th>Fremont School</th>
        <th>Friend/Family</th>
          <th>Total</th>
      </tr>
    </thead>
    <tbody>
    <?php 
    if(count($this->signup)>0){
    	foreach ($this->signup as $row) {
   ?>
    <tr>
        <td><?php echo $row['RegDate'];?></td>
        <td><?php echo $row['PTA'];?></td>
        <td><?php echo $row['SingTao'];?></td>
        <td><?php echo $row['FaceBook'];?></td>
         <td><?php echo $row['Youtube'];?></td>
        <td><?php echo $row['FremantSchool'];?></td>
        <td><?php echo $row['FriendFamily'];?></td>
        	<td bgcolor="yellow"><?php echo ($row['FaceBook']+$row['PTA']+$row['Youtube']+$row['FremantSchool']+$row['FriendFamily']+$row['SingTao']);?></td>
      </tr>
   <?php  		
    	}
    }
    ?>
    </tbody>
  </table>
  
  <h2>Detailed SignIn Count (Date wise)</h2>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Login Date</th>
        <th>PTA</th>
      	<th>SingTao</th>
        <th>FaceBook</th>
        <th>Youtube</th>
        <th>Fremont School</th>
        <th>Friend/Family</th>
        
        <th>Total</th>
      </tr>
    </thead>
    <tbody>
    <?php 
    if(count($this->signin)>0){
    	foreach ($this->signin as $row) {
   ?>
    <tr>
        <td><?php echo $row['LastLogin'];?></td>
        <td><?php echo $row['PTA'];?></td>
        <td><?php echo $row['SingTao'];?></td>
        <td><?php echo $row['FaceBook'];?></td>
         <td><?php echo $row['Youtube'];?></td>
        <td><?php echo $row['FremantSchool'];?></td>
        <td><?php echo $row['FriendFamily'];?></td>
        <td bgcolor="yellow"><?php echo ($row['FaceBook']+$row['PTA']+$row['Youtube']+$row['FremantSchool']+$row['FriendFamily']+$row['SingTao']);?></td>
      </tr>
   <?php  		
    	}
    }
    ?>
    </tbody>
  </table>
  
  
  
  



  
  <h2>Complete User List</h2>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Email Id</th>
        <th>Registration Date</th>
        
        <th>Last Login Date</th>
        <th>Channel</th>
        
      </tr>
    </thead>
    <tbody>
    <?php 
    if(count($this->completeList)>0){
    	foreach ($this->completeList as $row) {
   ?>
    <tr>
        <td><?php echo $row['email_id'];?></td>
        <td><?php echo $row['regdate'];?></td>
        <td><?php echo $row['lastlogin'];?></td>
        <td><?php echo $row['regchannel'];?></td>
       
      </tr>
   <?php  		
    	}
    }
    ?>
    </tbody>
  </table>
  
</div>

    
    
    
    
    
    
    
    

        <!-- REQUIRED JS SCRIPTS -->

        <!-- jQuery 2.1.4 -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script>
    // Fallback to loading jQuery from a local path if the CDN is unavailable
    (window.jQuery || document.write('<script src="plugins/jQuery/jQuery-2.1.4.min.js"><\/script>'));
    </script>

    <!-- Bootstrap 3.3.2 JS -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <script>
    // Fallback to loading jQuery from a local path if the CDN is unavailable
    ($.fn.modal || document.write('<script src="dist/js/bootstrap.min.js"><\/script>'));
    </script>
    
    <!-- Bootstrap css fallback -->
    <script>
      (function($) {
          $(function() {
              if ($('body').css('color') !== 'rgb(51, 51, 51)') {
                  $('head').prepend('<link rel="stylesheet" href="dist/css/bootstrap.min.css">');
              }
          });
      })(window.jQuery);
    </script>

    <!-- Font awesome fallback -->
    <script>
        (function($){
            var $span = $('<span class="fa" style="display:none"></span>').appendTo('body');
            if ($span.css('fontFamily') !== 'FontAwesome' ) {
                // Fallback Link
                $('head').append('<link href="dist/font-awesome-4.3.0/css/font-awesome.min.css" rel="stylesheet">');
            }
            $span.remove();
        })(jQuery);
    </script>


  <!-- Slimscroll -->
    <script src="/plugins/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <!-- FastClick -->
    <script src='/plugins/fastclick/fastclick.min.js'></script>
    <!-- AdminLTE App -->
    <script src="dist/js/app.min.js" type="text/javascript"></script>
    <!-- Optionally, you can add Slimscroll and FastClick plugins.
          Both of these plugins are recommended to enhance the
          user experience. Slimscroll is required when using the
          fixed layout. -->

    

  </body>
</html>
