
    
    <!-- subbanner -->

    <section class="content-header">
          <h1>
            Frequently Asked Questions            
          </h1>
    </section>

            <!-- FAQ -->
    <section id="faq" class="faq ">
        <div class="container">
            <div class="row ">
                <div class="col-lg-12">
                <!-- general -->
                <div class="box box-solid">
                  <div class="box-header bg-navy">
                    <h3 class="box-title">General</h3>
                  </div><!-- /.box-header -->
                  <div class="box-body">
                    <div class="box-group" id="accordion">
                      <!-- we are adding the .panel class so bootstrap.js collapse plugin detects it -->
                      <div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                              Do you sell your users' data?
                            </a>
                          </h4>
                        </div>
                        <div id="collapseOne" class="panel-collapse collapse in">
                          <div class="box-body">
                            Absolutely not!  UCEazy values your privacy and does not sell or share user data.
                          </div>
                        </div>
                      </div><!-- ./accordian -->
                      <div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
                              Why do you want to know (something) about me, anyways?
                            </a>
                          </h4>
                        </div>
                        <div id="collapseTwo" class="panel-collapse collapse in">
                          <div class="box-body">
                            UCEazy collects user data for three reasons. First, to improve our algorithms and give you more accurate information.  Second, to keep track of your account status.  Lastly, we ask for information that universities require on their applications.  That way, when it comes time to apply, you don't have to retype in all of your information!
                          </div>
                        </div>
                      </div> <!-- ./accordian -->
                      <div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                              How much does your software cost?
                            </a>
                          </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse in">
                          <div class="box-body">
                           Our application is free for a limited time. Even after the end of the free period, certain parts of the application would be free. 
                          </div>
                        </div>
                      </div><!-- ./accordian -->
                      <div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                             Why are you focusing only on CSUs and UCs?
                            </a>
                          </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse in">
                          <div class="box-body">
                           We believe that the need for an affordable solution like ours is highest among students that apply to public universities. Many students that apply to private colleges/universities are able to access college admissions help from other sources - either by hiring a private college admissions counselor or from the college counselors at their private high school.
                          </div>
                        </div>
                      </div><!-- ./accordian -->
                      <div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                             Why should I trust your software for such a critical decision like the college application process?
                            </a>
                          </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse in">
                          <div class="box-body">
                            You are correct in that this is a very critical decision!  In deciding whether or not to choose UCEazy, we ask you to consider the following: <br />
                             Our college admissions experts (the brains behind our software) have more than twenty years experience in college admissions counseling.
                              <ul>
                                <li>Several high schools are already piloting our software.</li>
                                <li>Our data is pulled from trustworthy and credible sources like CSU and UC websites.</li>
                                <li>Our software is so unique that we are in the process of filing several patents to protect them.</li>
                              </ul>
                          </div>
                        </div>
                      </div><!-- ./accordian -->
                      <div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                              How secure is my information?
                            </a>
                          </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse in">
                          <div class="box-body">
                            <p>The security of your information is a very high priority for us. UCEazy automatically encrypts your confidential information in transit from your computer to ours using the Secure Sockets Layer protocol (SSL) with an encryption key length of 128 bits.</p>
                            <p>Our servers sit behind an electronic firewall and are never directly connected to the Internet, so your private information stays private.</p>

                          </div>
                        </div>
                      </div><!-- ./accordian -->
                      
                    </div>
                  </div><!-- /.box-body -->
                </div><!-- Privacy/.box -->

            <!-- Essay REview -->
                <div class="box box-solid">
                  <div class="box-header bg-navy">
                    <h3 class="box-title">UCEazy Essay Review</h3>
                  </div><!-- /.box-header -->
                  <div class="box-body">
                    <div class="box-group" id="accordion">
                      <!-- we are adding the .panel class so bootstrap.js collapse plugin detects it -->
                      <div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                             The college essay is really high-stakes.  How do I know I can trust UCEazy?
                            </a>
                          </h4>
                        </div>
                        <div id="collapseOne" class="panel-collapse collapse in">
                          <div class="box-body">
                            UCEazy was founded with the sole intention of helping students apply successfully to the UC system. We have built an editing review service that contains two tiers of edits and quality control through a team of professional editors. We have guidance counselors and admissions experts pioneering the review process, and everyone here wants you to succeed.
                          </div>
                        </div>
                      </div><!-- ./accordian -->
                      <div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
                              Who is reading my essays?
                            </a>
                          </h4>
                        </div>
                        <div id="collapseTwo" class="panel-collapse collapse in">
                          <div class="box-body">
                           We have a two-step review process that includes two reviewers who go through your personal statements and provide feedback. The first reviewer is a current or former UC student who has experience in editing, English language, and, of course, the UC system. Each one wrote a personal statement and has been through the UC system. The second reviewer is a professional editor who will read your essay, look over the comments of the first review, and add more. The second review will focus on clarity and highlighting the story that best represents you.
                          </div>
                        </div>
                      </div> <!-- ./accordian -->
                      <div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                              Why are you using current or recently graduated UC students?
                            </a>
                          </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse in">
                          <div class="box-body">
                           We believe that someone with direct experience with the UC system is an invaluable resource when it comes to applying. Not only have each of these reviewers been accepted to the UC system, they have experience with peer review, English language and the admissions process.
                          </div>
                        </div>
                      </div><!-- ./accordian -->
                      <div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                             Will my essay be treated confidentially?   
                            </a>
                          </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse in">
                          <div class="box-body">
                           Absolutely. We don’t share your name with anyone, even our reviewers, and will return all comments to you on our private, secure website.
                          </div>
                        </div>
                      </div><!-- ./accordian -->
                      <div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                             How quickly is the turn-around after my essay is submitted?
                            </a>
                          </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse in">
                          <div class="box-body">
                            Three days. If you submit your essay in the evening, the clock will start the following morning.
                          </div>
                        </div>
                      </div><!-- ./accordian -->
                      <div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                              How can I get my essay edited more quickly?
                            </a>
                          </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse in">
                          <div class="box-body">
                            <p>Currently we don’t have an option for a quicker review.</p>

                          </div>
                        </div>
                      </div><!-- ./accordian -->
                      
                    </div>
                  </div><!-- /.box-body -->
                </div><!-- Privacy/.box -->
             
                <!-- Explore -->
                <div class="box box-solid">
                  <div class="box-header bg-navy">
                    <h3 class="box-title">Explore</h3>
                  </div><!-- /.box-header -->
                  <div class="box-body">
                    <div class="box-group" id="accordion">
                      <!-- we are adding the .panel class so bootstrap.js collapse plugin detects it -->
                      <div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                              What is EXPLORE all about?
                            </a>
                          </h4>
                        </div>
                        <div id="collapseOne" class="panel-collapse collapse in">
                          <div class="box-body">
                            EXPLORE (and Advanced EXPLORE) is where students can get a fast, easy, and realistic view of their college chances based on their academic information and interests.  While getting into a college is not wholly determined by your GPA and standardized test scores, they do heavily influence your chances of being admitted.  Through EXPLORE and Advanced EXPLORE, you can get a quick idea for where you stand at this point in time.  In order to get a more complete picture, you will want to continue on with PLAN after you've finished EXPLORE to start learning what you need to do to get into your dream school! 
                          </div>
                        </div>
                      </div><!-- ./accordian -->
                      <div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
                              What is RTS?
                            </a>
                          </h4>
                        </div>
                        <div id="collapseTwo" class="panel-collapse collapse in">
                          <div class="box-body">
                            RTS stands for Reach, Target  & Safety.  A Reach school is one that you might attain with some work at improving your scores and great extra-curriculars, etc.  A Target school is a school that your scores show a fairly reasonable probability of getting in. If you like one of these, give them a shot!  A Safety school is one that you are very likely to be accepted to with your current scores.  If you want to go to one of these schools, well, you're probably all set!  If not, consider applying to one anyways as a plan B.
                          </div>
                        </div>
                      </div> <!-- ./accordian -->
                      <div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                              Why don't I see any college in my RTS?
                            </a>
                          </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse in">
                          <div class="box-body">
                            Well, there are a few possibilities. First, go back and check your entries. Did you make a mistake entering a number? Did you input your school GPA instead of the Weighted GPA? If you did everything correctly, and still have no colleges listed in your RTS wheel, please send in a feedback form with as much detail as you can regarding the issue, and we'll look into it!
                          </div>
                        </div>
                      </div><!-- ./accordian -->
                      <div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                              Which are the supported platforms for viewing the app?
                            </a>
                          </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse in">
                          <div class="box-body">
                            This web application is best viewed on desktops and tablets. App for smartphones will be coming soon!. 
                         </div>
                        </div>
                      </div><!-- ./accordian -->
                      <div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                              What are these videos in each section?
                            </a>
                          </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse in">
                          <div class="box-body">
                            The videos act as supplementary information. They may explain some aspects of the section, give some background information, or explain the relative importance of the section. We recommend that you check out a section's video as a first step if you find yourself confused about anything in that section.
                          </div>
                        </div>
                      </div><!-- ./accordian -->
                      <div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                              How can I share my result with friends and family?
                            </a>
                          </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse in">
                          <div class="box-body">
                            Use the social media share options in our application.
                          </div>
                        </div>
                      </div><!-- ./accordian -->
                      <div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                              Why are there no Targets for me?
                            </a>
                          </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse in">
                          <div class="box-body">
                            Why is this empty? There are many possibilities - you might need to change or widen some of your criteria (for example, the major you selected might be limiting your list). There may also be no target colleges that fit your criteria.
                          </div>
                        </div>
                      </div><!-- ./accordian -->
                      <div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                              Why are there no Reaches for me?
                            </a>
                          </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse in">
                          <div class="box-body">
                            Why is this empty? There are many possibilities - your grades and standardized test scores could be extremely strong. There may also be no reach colleges that fit your criteria.
                          </div>
                        </div>
                      </div><!-- ./accordian -->
                      <div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                              Why are there no Safeties for me?
                            </a>
                          </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse in">
                          <div class="box-body">
                            Why is this empty? There are many possibilities - you might need to change or widen some of your criteria (for example, being open to both UC and CSU systems). Your grades and/or standardized test scores also may be lower than the colleges you have selected. If the latter is true, community college might be a great option to look in to.
                          </div>
                        </div>
                      </div><!-- ./accordian -->
                      <div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                              Where do I include my Extracurricular activities, Elective classes, etc.?
                            </a>
                          </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse in">
                          <div class="box-body">
                            Fear not! As you work through the sections in Plan, you will encounter places to input and catalogue everything that colleges are interested in.  If you have already gone through every section in Plan, and still can't find the right place to categorize that crazy thing you did, send us a suggestion for a new category!
                          </div>
                        </div>
                      </div><!-- ./accordian -->
                      <div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                              What is the GPA needed for applying to UC for out of state students?
                            </a>
                          </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse in">
                          <div class="box-body">
                            You must earn a minimum grade point average (GPA) of 3.4 or better in the 15 college-preparatory courses (a-g courses), with no grade lower than a C.
                          </div>
                        </div>
                      </div><!-- ./accordian -->
                    </div>
                  </div><!-- /.box-body -->
                </div><!-- Explore/.box -->

		         <!-- Plan -->
                <div class="box box-solid">
                  <div class="box-header bg-navy">
                    <h3 class="box-title">Plan</h3>
                  </div><!-- /.box-header -->
                  <div class="box-body">
                    <div class="box-group" id="accordion">
                      <!-- we are adding the .panel class so bootstrap.js collapse plugin detects it -->
                       </div> <!-- ./accordian -->
                      <div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                              What is PLAN all about?
                            </a>
                          </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse in">
                          <div class="box-body">
                            PLAN is to help you prepare and be the best applicant possible for the different parts of the UC and CSU applications.  Each of the sections of PLAN was built by a college counselor in the hopes of guiding you through the process, just like a high school counselor would.
                          </div>
                        </div>
                      </div><!-- ./accordian -->
                      <div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                              Where should I start in the PLAN?
                            </a>
                          </h4>
                        </div>
                        <div id="collapseOne" class="panel-collapse collapse in">
                          <div class="box-body">
                            We recommend starting with "My Profile."  As you complete each section, UCEazy will suggest what section you should start next.  We do this to maximize the potential of how our software can support you.  At the same time, we understand that every student’s college needs are different, so please feel free to navigate through any section that is most applicable to your individual situation.
                          </div>
                        </div>
                      </div><!-- ./accordian -->
                      <div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
                              Are the Resume and Personal Statement sections required for CSU's?
                            </a>
                          </h4>
                        </div>
                        <div id="collapseTwo" class="panel-collapse collapse in">
                          <div class="box-body">
                            None of the CSU's require personal statements (yay!).  Also, none of the CSU’s require students to list out your extracurricular activities.  Some campuses, however, ask you to approximate how many hours you spent in extracurricular activities (employment, community service, athletics, arts, clubs, etc.) over the last 12 months
                          </div>
                        </div>
                      </div> <!-- ./accordian -->
                      <div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                              What if I don't know what I want to major in?
                            </a>
                          </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse in">
                          <div class="box-body">
                            If you aren't sure what you want to major in, don't worry!  It is completely normal.  Most students tend to change their major 2-3 times in college, so there's a good chance that the people around you (who seem so sure of their major right now) will likely change it.  What we would encourage you to do is to use the tool on the "Major" screen to explore and learn about new majors.  You can also view our video on how to choose a major so that you can steer clear of any impacted (i.e., exceptionally competitive) majors.
                          </div>
                        </div>
                      </div><!-- ./accordian -->
                      <div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                              What counts under "Coursework other than A-G" in the Resume section?	
                            </a>
                          </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse in">
                          <div class="box-body">
                            This includes courses that you took (in high school or elsewhere) that don't receive A-G credit but have helped shape you in some way.  For example, ROTC, Religion, courses related to culture that you took outside of school
                          </div>
                        </div>
                      </div><!-- ./accordian -->
                      <div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                              What grade should I enter if I'm currently enrolled in a course?  
                            </a>
                          </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse in">
                          <div class="box-body">
                           You will want to select the last option on the pull-down menu, which states "In Progress."  
                          </div>
                        </div>
                          </div><!-- ./accordian -->
                      <div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                             What do I do if I've signed up for a SAT/ACT but haven't taken it yet?
                            </a>
                          </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse in">
                          <div class="box-body">
                           If you've already registered for an SAT or ACT, go ahead and select it in the "Testing" section and leave the fields blank where it asks you to fill in your scores.  
                          </div>
                        </div>
                      </div><!-- ./accordian -->
                      <div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                              Why does nothing show up in my My Counselor screen?
                            </a>
                          </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse in">
                          <div class="box-body">
                           In order for the "My Counselor" screen to work most effectively, you will need to have completed the first four screens leading up to it (My Profile, Major, Testing, and GPA).  The data you give us in those four screens is vital to our My Counselor recommendations. 
                          </div>
                        </div>
                         </div><!-- ./accordian -->
                      <div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                              What's the difference between Eligible and Competitive Courses?
                            </a>
                          </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse in">
                          <div class="box-body">
                           "Eligible Courses" means that, if you've completed them, you are eligible to apply to either UC or CSU college systems because you have met their course requirements (i.e., A-G courses) at the minimum level. In order to increase your chances, “Competitive Courses” indicates what courses you can take above-and-beyond the minimum to make yourself a more compelling and competitive applicant for those college systems.
                          </div>
                        </div>
                       </div><!-- ./accordian -->
                      <div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                              What counts under "Coursework other than A-G" in the Resume section?
							  </a>
                          </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse in">
                          <div class="box-body">
                           This includes courses that you took (in high school or elsewhere) that don't receive A-G credit but have helped shape you in some way.  For example, ROTC, Religion, courses related to culture that you took outside of school.
                          </div>
                        </div>
                      </div><!-- ./accordian -->                     
                        <div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                              What goes in "My Notes"?  What's it used for?
                            </a>
                          </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse in">
                          <div class="box-body">
                           You can put anything you like in "My Notes."  They are meant for you to remind yourself of various things like signing up for the SAT or talking to your counselor.  Or even personal things like needing to pick up brownies at the grocery store.  :) "This feature is coming soon".
                        </div>
                      </div><!-- ./accordian -->
                      <div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                              What's the difference between SAT and the ACT?  Which one should I take?
                            </a>
                          </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse in">
                          <div class="box-body">
                            <p>That's a great question.  In fact, we see it so much that we decided to create a video on this.  Please check out the "College Entrance Exams: SAT or ACT" video in the Testing section of the PLAN.
                          </div>
                        </div>
                      </div><!-- ./accordian -->
                      <div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                              What should I do if I want to minor in something?
                            </a>
                          </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse in">
                          <div class="box-body">
                            <p>Your minor is one of the few things that colleges DON'T look at when deciding whether or not to admit you.  Because of that, we leave it out of our software.</p>

                          </div>
                        </div>
                      </div><!-- ./accordian -->
					  
					  <div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                              Why is my dream school not listed here?
                            </a>
                          </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse in">
                          <div class="box-body">
                            <p>The dream school list only includes UC's and CSU's.  If your dream school is any other school outside of those two categories, we don't cover it here.  UCEazy focuses only on UC and CSU admissions.</p>

                          </div>
                        </div>
                      </div><!-- ./accordian -->
					  <div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                              How do I calculate my hours/time spent in an activity?  What counts?
                            </a>
                          </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse in">
                          <div class="box-body">
                            <p>You will want to count ALL hours you spent towards an activity. For example, in addition to counting the hours spent participating in an extracurricular activity, you will also want to include the time you spent planning/setting up for/communicating about events and transportation to/from this activity.</p>

                          </div>
                        </div>
                      </div><!-- ./accordian -->
					  
					  <div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                              What is an Educational Prep Program?
                            </a>
                          </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse in">
                          <div class="box-body">
                            <p>An Educational Prep Program is any program/activity that enriched your academic experience or prepared you for college. These programs often provide resources like:  counseling, tutoring, academic enrichment, research, special study opportunities, information, etc.</p>

                          </div>
                        </div>
                      </div><!-- ./accordian -->
					  
					  <div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                              How do fee waivers work with college applications or standardized testing?
                            </a>
                          </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse in">
                          <div class="box-body">
                            <p>That's a great question.  In fact, we see it so much that we decided to create a video on this.  Please check out the "How Fee Waivers Work and How to Qualify for One" video in the Costs section of the PLAN</p>

                          </div>
                        </div>
                      </div><!-- ./accordian -->
                        
					  <div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                             What does "impacted" or "impaction" mean?
                            </a>
                          </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse in">
                          <div class="box-body">
                            <p>Impaction or an impacted major/campus is when there are more students applying to that major/campus than the college can accommodate.  As a result, an impacted major/campus is far more competitive/harder to be admitted to versus a non-impacted major/campus.  In simpler terms, the more popular a major or college is, the harder it will be for you to get admitted because everyone likes that major/campus too. </p>

                          </div>
                        </div>
					  
                    </div>
					<div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                             Do UCs and CSUs look at senior year grades for GPA calculation?
                            </a>
                          </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse in">
                          <div class="box-body">
                            <p> UCs don't. CSUs do.</p>

                          </div>
                        </div>
					</div>
					<div class="panel box-solid">
                        <div class="box-header bg-accordian">
                          <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                             Do UCs and CSUs look at senior year coursework?
                            </a>
                          </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse in">
                          <div class="box-body">
                            <p> Both do to ensure the student has met the A-G coursework requirements. </p>

                          </div>
                        </div>
					</div>
				
					
					
                  </div><!-- /.box-body -->
                </div><!-- Privacy/.box -->


                         </div>
                <!-- /.col-lg-10 -->
            </div>
            <!-- /.row -->

             
        <!-- /.container -->
    </section>

  