  <!-- Main Footer -->
      <footer class="main-footer">
        <div class="row">
          <div class="col-lg-12 col-sm-12 col-md-12 col-xs-12 copyRight1">
            <strong>Copyright &copy; <?php echo date('Y');?> <a href="#">UCEazy</a>.</strong> All rights reserved.
            <!-- social media -->
          </div>
          <div class="col-lg-4 col-sm-12 col-md-12 col-xs-12 hidden-lg">
            <div class="followUs1 text-center" >
                Follow us on: 
                  <div  class="fixedBtnAdmin"><a href="https://www.facebook.com/askuceazy" class="bg-facebook" target="_blank"><i class="fa fa-facebook"></i></a></div>
                  <div class="fixedBtnAdmin"><a href="https://twitter.com/Uaskuceazy?lang=en" class="bg-twitter" target="_blank"><i class="fa fa-twitter"></i></a></div>
                  <div class="fixedBtnAdmin"><a href="https://www.linkedin.com/company/uceazy" class="bg-linkedin" target="_blank"><i class="fa fa-linkedin"></i></a></div>
                  <div class="fixedBtnAdmin"><a href="https://instagram.com/uceazy/" class="bg-instagram" target="_blank"><i class="fa fa-instagram"></i></a></div>
              </div>  
            </div>
            <div class="clearfix"></div>
        </div>
      </footer>
      
    </div>
	
	    <!-- Google Analytics -->
   <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-68102741-1', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>