<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <link rel="icon" type="image/png" href="dist/img/favicon.ico">
    <title>UC and CSU Admissions Made Easy</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <meta name="description" content="UCEazy - UC and CSU Admissions Made Easy. An affordable software based solution for applying to public universities. UCEazy application is easy to use, understand and fit into a high school student's hectic lifestyle.  " />
    <meta name="keywords" content="UC admission, UC admissions, UC application, UC Essay, UC Personal Statement, Essay Review, UC admission help, UC admission advice, UC admission guidance, CSU admission, CSU admissions , CSU application, CSU admission help, CSU admission, advice, CSU admission guidance, GPA, GPA Calculator, UC GPA, CSU GPA, SAT to ACT conversion calculator, ACT to SAT conversion calculator , UC Activities and Awards, UC Resume, UC Cost of Attendance, UC Attendance Cost, CSU Cost of Attendance , CSU Attendance Cost, CSU application fee, CSU application cost, UC application fee, 
UC application cost,UC app costs, UC application costs, CSU app costs , CSU application costs, Explore, Plan, " />
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <!-- Font Awesome Icons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!--<link href="dist/font-awesome-4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />-->
    <!-- Ionicons -->
    <!--<link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />-->
    <link href="/dist/ionicons-2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="/dist/css/AdminLTE.css" rel="stylesheet" type="text/css" />
    <link href="/dist/css/skins/skin-black.css" rel="stylesheet" type="text/css" />
    <!-- Custom style -->
    <link href="/dist/css/styles.css" rel="stylesheet" type="text/css" />
    <!-- Jquery Scroll bar style -->
    <link href="/dist/css/jquery.scrollbar.css" rel="stylesheet" type="text/css" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="login-page1 ">
  <div class=" loginContainer container m-login-logo">
    <img src="/dist/img/logo-uceazy-lg.png" alt="UCEazy Logo" class="img-responsive">
  </div><!-- /.login-logo -->

<!-- Header -->
<header id="top" class="registerbg">
    <div class="text-vertical-center bannerText2">
        
      <h1 style="font-size:26px;">Is the UC Essay giving you writer’s block?</h1>
      <h2 style="font-size:22px;">We can help</h2>
    </div>
</header>
  <div class="container ">
      
      
      <div class="clearfix"></div>
      <div class="mlpContainer">
        <div class="row">
            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 col-lg-push-8">
              <div class="login-box-body">
                  <p class="login-box-msg " style="color:#000;">Signing Up is Quick and Easy!</p> <hr />
                  <form action="" method="post" name="signup-form" id="signup-form">
                  <div class="row">
                    <div id="signupexperrordiv" class="alert alert-danger col-sm-12" style="display: none;">
                      <div class="info-text-container-failure ">
                          <i class="fa fa-close "></i> 
                          <span class="info-text" id="signupexperror">
                          </span>
                       </div>
                    </div>
                      
                    <div id="signupsuccessdiv" class="alert alert-success col-sm-12" style="display: none;">
                      <div class="info-text-container-success ">
                        <i class="fa fa-check "></i> 
                        <span class="info-text" id="signupsuccess">
                        </span>
                     </div>
                    </div>   
                  </div>
                  <div class="form-group has-feedback">
                    <div class="input-group">
                      <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
                      <input type="email" class="form-control"  name="username" placeholder="Email">
                    </div>
                  </div>
                  <div class="form-group has-feedback">
                    <div class="input-group">
                      <span class="input-group-addon"><i class="fa fa-unlock-alt"></i></span>
                      <input type="password" class="form-control" name="password"  placeholder="Password">
                    </div>  
                  </div>
                  <div class="form-group has-feedback">
                    <div class="input-group">
                      <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                      <input type="password" class="form-control" name="repassword" placeholder="Confirm Password">
                    </div>
                    
                  </div>
                  <div class="checkbox">
                    <label>
                      <input type="checkbox" name="agecertify"> I certify that I am at least 13 years old
                    </label>
                  </div>
                  <div class="row">
                    <div class="col-xs-12" style="padding-top:15px;">
                      <button type="button" id="btn-signup" class="btn btn-danger btn-block btn-flat" data-loading-text="Loading...." data-reset-text="Sign up" style="font-size:16px;">Onward!</button>
                    </div><!-- /.col -->
                  </div>
        
                </form>
                <div class="text-center loginInfotext" >
                  Already have an UCEazy account! <a href="/user/signin" class="text-center"> Sign in</a>  here.
                </div>
              </div><!-- /.login-box-body -->
              
              
            </div>

             <div class="col-lg-8 col-md-12 col-sm-12 col-xs-12 col-lg-pull-4  mobilePaddingTop" >
              <div class="bg-teal">
              <h3>How can you distinguish yourself from all the other UC Berkeley applicants (who averaged a 4.4 weighted GPA)?</h3>
              <h3>You need a great essay that highlights your persistence, passion and desire to give back. </h3>
              </div>
              <div style="padding-top:15px;">
              <p class="lead"><strong>User Testimonials</strong></p>
                <p>"Thank you UCEazy for your great essay service. Along with it being affordable, it is also very easy to use. The reviews themselves are detailed and constructive, giving my daughter a clear idea of what she needs to do to get her essays ready for submission." <br />– Govind (parent in Sunnyvale, CA)</p>
                 <p>"UC personal statements are so stressful because it seems like everyone has something different to say about them. Having UCEazy's team of former UC students and professional editors review my essays not only made them much stronger, but also gave me the peace of mind that I was on the right track in regards to what the UCs are looking for." <br />–Sruthi (student in Sunnyvale, CA) </p>
                 </div>
            </div>
          </div>
        </div>
    </div>
    <!-- Team -->
<section id="team" class=" login-page">
    <div class="container">
        <div class="row">
            <div class="col-lg-10 col-lg-offset-1 text-center" style="margin-bottom:15px;">
                <h2>Our Essay Review Team</h2>
                <hr class="small">
                <p class="lead">Our reviewers are experts on evaluating UC essays. They helped numerous students get accepted into top UC universities.</p>
                <div class="row">
                  <div class="contentPadding essayReview">
                    <div class="col-md-4 col-xs-12" >
                      <div class="reviewTeamContainer">
                        <div style="background:#eaeaea;">
                          <img class=" img-responsive" src="../dist/img/team/stacey.jpg" alt="Stacey Ho Ching"/>
                          <p style="">Stacey Ho Ching</p>
                          <div class="clearfix"></div>  
                        </div>
                        <div class="clearfix"></div>
                        <div style="text-align:left;">
                          <ul >
                            <li>UCLA Undergraduate</li>
                            <li>Masters in Counseling from University of Maryland</li>
                            <li>Admissions Advising certificate from Berkeley</li>
                            <li>Over 10 years experience in college counseling and essay reviews.</li>
                          </ul>
                        </div>
                       </div>
                    </div>
                    <div class="col-md-4 col-xs-12" >
                      <div class="reviewTeamContainer">
                        <div style="background:#eaeaea;">
                          <img class=" img-responsive" src="../dist/img/team/shari.jpg" alt="Shari Schussel"/>
                          <p style="">Shari Schussel</p>
                          <div class="clearfix"></div>  
                        </div>
                        <div class="clearfix"></div>
                        <div style="text-align:left;">
                          <ul >
                            <li>10 years college counseling experience</li>
                            <li>Masters in Education Counseling</li>
                            <li>Passion to help students write great UC Essays</li>
                          </ul>
                        </div>
                       </div>
                    </div>
                    <div class="col-md-4 col-xs-12" >
                      <div class="reviewTeamContainer">
                        <div style="background:#eaeaea;">
                          <img class=" img-responsive" src="../dist/img/team/daniel.jpg" alt="Daniel Zweier"/>
                          <p style="">Daniel Zweier</p>
                          <div class="clearfix"></div>  
                        </div>
                        <div class="clearfix"></div>
                        <div style="text-align:left;">
                          <ul >
                            <li>UC Graduate</li>
                            <li>Professional writer / journalist / educator</li>
                            <li>Passion to help students craft well-written and insightful essays.</li>
                          </ul>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
            </div>
            <!-- /.col-lg-10 -->
        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->
</section>

<!-- What we’d like from you -->
<section class="bglightgray uceazyappsection" >
    <div class="container">
        <div class="row ">
            <div class="col-lg-12 " style="margin-bottom:15px;"> 
              <h2 class="text-center">Our Dual Process</h2>
              <hr class="small">
                <p>Our specialized method consists of a two-step process with two reviewers who go through your personal statements and provide feedback.</p>
                <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12 essayProcessContent" >
                <p class="blue" style="padding:10px; color:white;">The first reviewer is a current or former UC student who has experience in editing, the English language, and the UC system itself. Each one wrote a personal statement and got into a University of California.</p>
                </div>
                <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12 essayProcessContent" >
                <p class="bg-green" style="padding:10px; color:white;">
                  The second step of the review builds upon the first — an experienced editor will look over the comments of the first and add more, focusing on clarity and the story that best represents you.
                  </p> 
                </div>
                <p>
                  Other services offer either a student reviewer, who may be excellent at writing but not reviewing, or a professional editor, who will give precise feedback but does not have experience with the specific UC prompts.
                </p> 
                <p>We have both, and your essay will be stronger because of it.</p>
              </div>
              
            </div>
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
</section>
<div class="clearfix"></div>
      <div class="text-center compatibileText " style="padding:15px; background:#222; color:#fff;">
        <small>UCEazy is a complete online service for admissions to the University of California (UC) and California State University (CSU).

      </div>
  </div>


        <!-- jQuery 2.1.4 -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script>
    // Fallback to loading jQuery from a local path if the CDN is unavailable
    (window.jQuery || document.write('<script src="plugins/jQuery/jQuery-2.1.4.min.js"><\/script>'));
    </script>

    <!-- Bootstrap 3.3.2 JS -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <script>
    // Fallback to loading jQuery from a local path if the CDN is unavailable
    ($.fn.modal || document.write('<script src="dist/js/bootstrap.min.js"><\/script>'));
    </script>
    
    <!-- Bootstrap css fallback -->
    <script>
      (function($) {
          $(function() {
              if ($('body').css('color') !== 'rgb(51, 51, 51)') {
                  $('head').prepend('<link rel="stylesheet" href="dist/css/bootstrap.min.css">');
              }
          });
      })(window.jQuery);
    </script>

    <!-- Font awesome fallback -->
    <script>
        (function($){
            var $span = $('<span class="fa" style="display:none"></span>').appendTo('body');
            if ($span.css('fontFamily') !== 'FontAwesome' ) {
                // Fallback Link
                $('head').append('<link href="dist/font-awesome-4.3.0/css/font-awesome.min.css" rel="stylesheet">');
            }
            $span.remove();
        })(jQuery);
    </script>


  <!-- Slimscroll -->
    <script src="/plugins/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <!-- FastClick -->
    <script src='/plugins/fastclick/fastclick.min.js'></script>
    <!-- AdminLTE App -->
    <script src="/dist/js/app.min.js" type="text/javascript"></script>
    <!-- Optionally, you can add Slimscroll and FastClick plugins.
          Both of these plugins are recommended to enhance the
          user experience. Slimscroll is required when using the
          fixed layout. -->

    <!-- iCheck -->
    <script src="plugins/iCheck/icheck.min.js" type="text/javascript"></script>
    <script>


    $('#btn-signup').click(function(){
    	 var btn = $(this)
   	  btn.button('loading');
  	  var data = {
  		      "action": "test"
  		    };

  	  $("#signupexperrordiv").hide();	  
  		$("#signupsuccessdiv").hide();
		           
	 	    data = $("#signup-form").serialize() + "&" + $.param(data);
  		    $.ajax({
  		      type: "POST",
  		      dataType: "json",
  		      url: "/user/signupservice", 
  		      data: data,
  		      success: function(data) {
  		    	  if(data['error']!=null){
  		    		  $("#signupexperrordiv").show();	  
         		       $("#signupexperror").html(data["error"]);
     		        }else{
     		        	$("#signupsuccessdiv").show();
     		        	$("#signupsuccess").html(data["success"]);
     		        }
  		      },
  		    complete: function(xhr, textStatus){
		   		  btn.button('reset');
		   		}
  		    });
  		    return false;
        
});

    
      $(function () {
        $('input').iCheck({
          checkboxClass: 'icheckbox_square-blue',
          radioClass: 'iradio_square-blue',
          increaseArea: '20%' // optional
        });
      });
    </script>
	
	    <!-- Google Analytics -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-68102741-1', 'auto');
  ga('send', 'pageview');

</script>
  </body>
</html>
