<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <link rel="icon" type="image/png" href="dist/img/favicon.ico">
    <title>UC and CSU Admissions Made Easy</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <meta name="description" content="UCEazy - UC and CSU Admissions Made Easy. An affordable software based solution for applying to public universities. UCEazy application is easy to use, understand and fit into a high school student's hectic lifestyle.  " />
    <meta name="keywords" content="UC admission, UC admissions, UC application, UC Essay, UC Personal Statement, Essay Review, UC admission help, UC admission advice, UC admission guidance, CSU admission, CSU admissions , CSU application, CSU admission help, CSU admission, advice, CSU admission guidance, GPA, GPA Calculator, UC GPA, CSU GPA, SAT to ACT conversion calculator, ACT to SAT conversion calculator , UC Activities and Awards, UC Resume, UC Cost of Attendance, UC Attendance Cost, CSU Cost of Attendance , CSU Attendance Cost, CSU application fee, CSU application cost, UC application fee, 
UC application cost,UC app costs, UC application costs, CSU app costs , CSU application costs, Explore, Plan, " />
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <!-- Font Awesome Icons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!--<link href="dist/font-awesome-4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />-->
    <!-- Ionicons -->
    <!--<link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />-->
    <link href="/dist/ionicons-2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="/dist/css/AdminLTE.css" rel="stylesheet" type="text/css" />
    <link href="/dist/css/skins/skin-black.css" rel="stylesheet" type="text/css" />
    <!-- Custom style -->
    <link href="/dist/css/styles.css" rel="stylesheet" type="text/css" />
    <!-- Jquery Scroll bar style -->
    <link href="/dist/css/jquery.scrollbar.css" rel="stylesheet" type="text/css" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="login-page">
    <div class="login-box">
      <div class="login-logo ">
        <a href="/"><img src="/dist/img/logo-uceazy-lg.png" alt="UCEazy Logo" class="img-responsive"></a>
      </div><!-- /.login-logo -->
      <div class="login-box-body">
        <p class="login-box-msg "><strong>Reset Password</strong></p> <hr />
        <div class="row">
        <div id="simpleexperrordiv" class="alert alert-danger col-sm-12" style="display: none;">
                <div class="info-text-container-failure ">
                  	<i class="fa fa-close "></i> 
                    <span class="info-text" id="simpleexperror">
                    </span>
                 </div>
        </div>
        </div>
                <?php if(isset($this->error) && ! isset($this->postaction) ){?>
              <div id="alert-info" class="alert alert-info col-sm-12">
                <div class="info-text-container-info ">
                  <i class="fa fa-exclamation-triangle "></i> 
                    <span class="info-text"><?php echo $this->error;?>.
                    </span>
                 </div>
              </div>
<?php }?>
             
  <?php if(isset($this->postaction) || isset($this->success)){?>
					 <?php if(isset($this->success)){ ?>
<div id="alert-success" class="alert alert-success col-sm-12">
                <div class="info-text-container-success ">
                  <i class="fa fa-check "></i> 
                    <span class="info-text"><?php echo $this->success;?>.
                    </span>
                 </div>
              </div>
              <div class="clearfix"></div>
<?php }else{?>

<iv id="alert-success" class="alert alert-error col-sm-12">
                <div class="info-text-container-success ">
                  <i class="fa fa-check "></i> 
                    <span class="info-text"><?php echo $this->error;?>.
                    </span>
                 </div>
              </div>
              <div class="clearfix"></div>
<?php }?>
        <form action="" method="post" id="resetForm" name="resetForm">
          <div class="form-group has-feedback">
            <div class="input-group">
              <span class="input-group-addon"><i class="fa fa-lock"></i></span>
              
              <input id="login-password" class="form-control" type="password" name="password" placeholder="Password">
            </div>
          </div>
          <div class="form-group has-feedback">
            <div class="input-group">
              <span class="input-group-addon"><i class="fa fa-lock"></i></span>
             
               <input id="login-password" class="form-control" type="password"  name="repassword" placeholder="Re-enter your Password">
                  <input type="hidden" name="key" value="<?php echo $this->key;?>"/>
                   <input id="login-username" type="hidden" class="form-control" name="username" value="<?php echo $this->email;?>" placeholder="Email" readonly="readonly">                                        
                  
            </div>
           
          </div>
          
         
          <div class="row">
            
            <div class="col-xs-12">
              <button type="submit" id="btn-login" class="btn btn-danger btn-block btn-flat" data-loading-text="Loading...." data-reset-text="Sign In">Reset Password</button>
            </div><!-- /.col -->
          </div>
        </form>
<?php }?>
        <!-- <div class="social-auth-links text-center">
          <p>- OR -</p>
          <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in using Facebook</a>
          <a href="#" class="btn btn-block btn-social btn-google-plus btn-flat"><i class="fa fa-google-plus"></i> Sign in using Google+</a>
        </div> --><!-- /.social-auth-links 
        
        <div class="text-center loginInfotext">
          Don't have an UCEazy account! <a href="/user/signup" class="text-center"> Sign up</a>  here.
        </div>-->
        
        <div class="text-center loginInfotext">
          Already have an UCEazy account! <a href="/user/signin" class="text-center"> Sign in</a>  here.
        </div>

      </div><!-- /.login-box-body -->

      <div class="copyRight1">Copyright &copy; 2015 <a href="index.html">UCEazy</a>. All rights reserved.
        </div>
    </div><!-- /.login-box -->

        <!-- REQUIRED JS SCRIPTS -->

        <!-- jQuery 2.1.4 -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script>
    // Fallback to loading jQuery from a local path if the CDN is unavailable
    (window.jQuery || document.write('<script src="plugins/jQuery/jQuery-2.1.4.min.js"><\/script>'));
    </script>

    <!-- Bootstrap 3.3.2 JS -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <script>
    // Fallback to loading jQuery from a local path if the CDN is unavailable
    ($.fn.modal || document.write('<script src="dist/js/bootstrap.min.js"><\/script>'));
    </script>
    
    <!-- Bootstrap css fallback -->
    <script>
      (function($) {
          $(function() {
              if ($('body').css('color') !== 'rgb(51, 51, 51)') {
                  $('head').prepend('<link rel="stylesheet" href="dist/css/bootstrap.min.css">');
              }
          });
      })(window.jQuery);
    </script>

    <!-- Font awesome fallback -->
    <script>
        (function($){
            var $span = $('<span class="fa" style="display:none"></span>').appendTo('body');
            if ($span.css('fontFamily') !== 'FontAwesome' ) {
                // Fallback Link
                $('head').append('<link href="dist/font-awesome-4.3.0/css/font-awesome.min.css" rel="stylesheet">');
            }
            $span.remove();
        })(jQuery);
    </script>


  <!-- Slimscroll -->
    <script src="/plugins/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <!-- FastClick -->
    <script src='/plugins/fastclick/fastclick.min.js'></script>
    <!-- AdminLTE App -->
    <script src="dist/js/app.min.js" type="text/javascript"></script>
    <!-- Optionally, you can add Slimscroll and FastClick plugins.
          Both of these plugins are recommended to enhance the
          user experience. Slimscroll is required when using the
          fixed layout. -->

    <!-- iCheck -->
    <script src="/plugins/iCheck/icheck.min.js" type="text/javascript"></script>
    <script>

  
    
      $(function () {
        $('input').iCheck({
          checkboxClass: 'icheckbox_square-blue',
          radioClass: 'iradio_square-blue',
          increaseArea: '20%' // optional
        });
      });
    </script>
	
	    <!-- Google Analytics -->
   <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-68102741-1', 'auto');
  ga('send', 'pageview');

</script>
  </body>
</html>
