<?php 
use Common\ActionForms\ExplorerForm;
use Common\Utilities\Constants;
use Zend\Session\SessionManager;
use Zend\Session\Container;
$session = new Container('user');

?>



<!-- Content Wrapper. Contains page content -->
<div
	class="content-wrapper pscontentContainer">
	<!-- Content Header (Page header) -->
	<section class="content-header">
	<h1>
		<i class="fa fa-file-text-o"></i>Buy Essay Service
		<!-- <small>Advice from Your UCEazy Counselor</small>-->
	</h1>
	<!--  <ol class="breadcrumb">
            <li><a href="/user/index"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li><a href="/plan/index"><i class="ion ion-gear-b"></i> Essay Service</a></li>
            <li class="active">Essay Service</li>
          </ol>--> </section>
	<section class="content">
	<div class="row">
		<div class="col-lg-10 col-lg-offset-1 col-md-12 col-sm-12 col-xs-12 ">
			<div id="generalPanel" class="box box-default box-solid">
				<div class="box-header bg-blue ">
					<h3 class="box-title">About Essay Service</h3>
				</div>
				<div>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
						eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
						enim ad minim veniam, quis nostrud exercitation ullamco laboris
						nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
						reprehenderit in voluptate velit esse cillum dolore eu fugiat
						nulla pariatur. Excepteur sint occaecat cupidatat non</p>
				</div>
				
				<!-- /.box-header -->
				<div class="box-body">
					<div class="form-group">
						<form class="form-horizontal" id="" method="post"
							name="frmPayPal1">
							<!-- form start -->
							<div class="box-body col-lg-12 col-lg-offset-3  text-center">


								<div class="form-group ">
									<label for="californiaCounty" class="col-sm-3 control-label">Service
										Cost </label>
									<div class="col-sm-5 ">
										<label for="californiaCounty" class="col-sm-3 control-label">$1000.00
										</label>
									</div>

								</div>
							</div>
							<!-- /.widget box -->

							<div class="box-footer text-center">
								<div
									class="col-lg-10 col-lg-offset-1 col-md-12 col-sm-12 col-xs-12 ">
									<input type="image"
										src="https://www.sandbox.paypal.com/en_US/i/btn/btn_buynowCC_LG.gif"
										border="0" name="submit"
										alt="PayPal - The safer, easier way to pay online!">
								</div>
		

								


								<div id="payment_cancel" class="alert alert-danger col-sm-12"> 
									<div class="info-text-container-failure ">
										<span class="info-text" id="">
											The Payment has been cancelled! </span>
									</div>
								</div>



							</div>
							<!-- /.box-footer -->
						</form>
					</div>
					<hr />
				</div>
			</div>
		</div>
	</div>
	</section>

</div>
