<div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
           <h1>
            <i class="fa fa-lock"></i> Change Password
          </h1>
          <ol class="breadcrumb">
            <li><a href="/user/index"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li class="active">Change Password</li>
          </ol>
        </section>
        <!-- Main content -->
        
        <form name="changepassform" id="changepassform" method="post" action="">
          <section class="content">
            <div class="row">
              <div class="col-lg-10 col-lg-offset-1">
                <div class="box box-default box-solid">
                  <div class="box-body">
                    
                      <div id="errordiv" class="alert alert-danger col-sm-12" style="display: none;">
                        <div class="info-text-container-failure ">
                              <i class="fa fa-close "></i> 
                              <span class="info-text" id="error">
                              </span>
                           </div>
                        </div>
                            
                        <div id="successdiv" class="alert alert-success col-sm-12" style="display: none;">
                          <div class="info-text-container-success ">
                              <i class="fa fa-check "></i> 
                              <span class="info-text" id="success">
                              </span>
                           </div>
                        </div>   
                    

                      <div class="form-group formDataAlign">
                        <label for="currentState" class="col-sm-3 control-label">Old Password </label>
                        <div class="col-sm-6">
                          <input id="email" name="oldpassword" type="password" value="" class="form-control " placeholder="Enter old password">                            
                        </div>
                      </div>
                      <div class="clearfix"></div>
                      
                      <div class="form-group formDataAlign">
                        <label for="currentState" class="col-sm-3 control-label">New Password </label>
                        <div class="col-sm-6">
                          <input id="email" name="newpassword" type="password" value="" class="form-control " placeholder="Enter new password">                            
                        </div>
                      </div>
                      <div class="clearfix"></div>
                      
                      <div class="form-group formDataAlign">
                        <label for="currentState" class="col-sm-3 control-label">Confirm Password</label>
                        <div class="col-sm-6">
                          <input id="email" name="confirmpassword" type="password" value="" class="form-control " placeholder="Enter confirm password">                            
                        </div>
                      </div>
                      <div class="clearfix"></div>
                    
                  </div><!-- ./box body -->

                  <div class="box-footer text-center">
                    <button type="submit" id="changepass" class="btn btn-danger " >Change Password</button>                    
                  </div><!-- ./box footer -->
                  </div>
                </div><!-- ./box -->
              </div>
            </div>  
        </section>
        </form>
      <!-- Main Footer -->
      
       <!-- jQuery 2.1.4 -->
    <script src="/plugins/jQuery/jQuery-2.1.4.min.js"></script>
    <!-- Bootstrap 3.3.2 JS -->
    <script src="/dist/js/bootstrap.min.js" type="text/javascript"></script>
    <!-- ChartJS 1.0.1 -->
    <script src="/plugins/chartjs/Chart.min.js" type="text/javascript"></script>

	<!-- Slimscroll -->
    <script src="/plugins/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <!-- FastClick -->
    <script src='/plugins/fastclick/fastclick.min.js'></script>
    <!-- AdminLTE App -->
    <script src="/dist/js/app.min.js" type="text/javascript"></script>
     
     
     <script>



     $('#changepass').click(function(){
     	 var btn = $(this)
    	  btn.button('loading');
   	  var data = {
   		      "action": "test"
   		    };

   	  $("#errordiv").hide();	  
   		$("#successdiv").hide();
 		           
 	 	    data = $("#changepassform").serialize() + "&" + $.param(data);
   		    $.ajax({
   		      type: "POST",
   		      dataType: "json",
   		      url: "/user/changepassservice", 
   		      data: data,
   		      success: function(data) {
   		    	  if(data['error']!=null){
   		    		  $("#errordiv").show();	  
          		       $("#error").html(data["error"]);
          		     setTimeout(function(){ $('#errordiv').hide(); }, 10000);
      		        }else{
      		        	$("#successdiv").show();
      		        	$("#success").html(data["success"]);
      		        	 setTimeout(function(){ $('#successdiv').hide(); }, 10000);
      		        }
   		      },
   		    complete: function(xhr, textStatus){
 		   		  btn.button('reset');
 		   		}
   		    });
   		    return false;
         
 });

     </script>