 
  <div class="content-wrapper " >
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Dashboard
          </h1>
          
        </section>

        <!-- Main content -->
        <section class="content ">
          <div class="introContent bg-red">
            <div class="small-box  bg-blackTrans moduleContent" style="padding:30px;cursor: auto;">
                <?php 
                /*$per=0;
                if($this->service_cnt<=0){
                	$per=30;
                }else {
                	$per=40;
                }*/
                //if($this->open_essay_cnt<=0 ){?>
                <div class="inner text-center responsiveText" >
                  <div class="inner text-center" >
                  <div class="bannerText">"UC personal statements are so stressful because it seems like everyone has something different to say about them. Having UCEazy's team of former UC students and professional editors review my essays not only made them much stronger, but also gave me the peace of mind that I was on the right track in regards to what the UCs are looking for." </div>
                  <p><i>-Sruthi (student in Sunnyvale, CA)</i></p>
                  
                </div>
                </div>
                <?php //}?>
                 <!--  for Paid user--> 
                <?php //if($this->open_essay_cnt>0){?>
                <!--<div class="inner text-center " >
                    <h3>Don't forget to submit your essay for review.</h3>
                  <h3 >Your essay is due by November 25th!</h3>
                  <div>
                      <a href="/buyservice/buyEssay" class="btn btn-danger btn-lg" style="margin-top:10px">Submit Essay for Review</a>
                    </div>
                </div>-->
              <?php //}?>
              </div>
          </div>
          <div class="row">
            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 col-lg-push-8">
              <div class="box box-default box-solid">
                    <div class="box-body">
                        <div class="embed-responsive embed-responsive-16by9">
                            <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/vdEonzAt1xs?showinfo=0&amp;"></iframe>
                        </div>
                    </div><!-- /.box-body -->
              </div>
          </div>

            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 col-lg-pull-4 ">
              <div class="small-box bg-green1 moduleContent">
                <div class="inner dashboardExPlanContainer">
                  <h3>Explore</h3>
                  <p class="paraDashboard" >Our Explore module will instantly create a Reach-Target-Safety list for you based upon your college selection criteria.
                  </p>
                </div>
                <div class="icon">
                  <i class="ion ion-android-compass"></i>
                </div>
                <a href="/search/advexplorer" class="small-box-footer">Create your college list  &nbsp;&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></a>
              </div>
            </div>
            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 col-lg-pull-4 ">
              <!-- small box -->
              <div class="small-box bg-blue moduleContent">
                <div class="inner dashboardExPlanContainer dashPlanContainer">
                  <h3>Plan</h3>
                  <p class="paraDashboard" >Our Plan module helps you calculate your UC/CSU GPA, report the best test scores, organize your Activities and Awards, write a compelling personal statement, and calculate college application and attendance costs.
                  </p>
                </div>
                <div class="icon">
                  <i class="ion ion-gear-b"></i>
                </div>
                <a href="/plan/index" class="small-box-footer">Organize, Prepare, Track &nbsp;&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></a>
              </div>
            </div>

            
          </div>
          <div class="clearfix"></div>
          
          <!-- social media -->
          <div class="row ">
              <div class="col-md-8">
                <p class="introText">If you run into any questions, check out our <a href="/index/faq" title="FAQ" >FAQ</a> or click on the social media link provided on every screen. We also welcome your feedback and have included a section for your input on the bottom right side of every screen.
            </p>
              </div>
              <div class="col-md-4 pull-right">
                <div class="box box-solid hidden-md hidden-sm hidden-xs " >
                    <div class="box-header">
                      <h3 class="box-title" style="color:#000 !important;"><i class="fa fa-share-alt"></i> Follow Us</h3>
                      <div class=" pull-right " >
                        <div  class="fixedBtn"><a href="https://www.facebook.com/askuceazy" class="bg-facebook" target="_blank" title="Facebook"><i class="fa fa-facebook"></i></a></div>
                        <div class="fixedBtn"><a href="https://twitter.com/Uaskuceazy?lang=en" class="bg-twitter" target="_blank" title="Twitter"><i class="fa fa-twitter"></i></a></div>
                         <div class="fixedBtn"><a href="https://www.linkedin.com/company/uceazy" class="bg-linkedin" target="_blank" title="Linkedin"><i class="fa fa-linkedin"></i></a></div>
                        <div  class="fixedBtn"><a href="https://instagram.com/uceazy/" class="bg-instagram" target="_blank"><i class="fa fa-instagram"></i></a>
                        </div>

                        <!-- <div class="fixedBtn"><a href="#" class="bg-google-plus"><i class="fa fa-google-plus"></i></a></div>
                        <div class="fixedBtn"><a href="#" class="bg-instagram"><i class="fa fa-instagram"></i></a></div>
                        <div class="fixedBtn"><a href="#" class="bg-pinterest"><i class="fa fa-pinterest"></i></a></div>-->
                      </div>  
                    </div>
                </div>
              </div>
        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->

    

    <!-- REQUIRED JS SCRIPTS -->

    <!-- jQuery 2.1.4 -->
    <script src="/plugins/jQuery/jQuery-2.1.4.min.js"></script>
    <!-- Bootstrap 3.3.2 JS -->
    <script src="/dist/js/bootstrap.min.js" type="text/javascript"></script>
    <!-- ChartJS 1.0.1 -->
    <script src="/plugins/chartjs/Chart.min.js" type="text/javascript"></script>

	<!-- Slimscroll -->
    <script src="/plugins/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <!-- FastClick -->
    <script src='/plugins/fastclick/fastclick.min.js'></script>
    <!-- AdminLTE App -->
    <script src="/dist/js/app.min.js" type="text/javascript"></script>
    <!-- Optionally, you can add Slimscroll and FastClick plugins.
          Both of these plugins are recommended to enhance the
          user experience. Slimscroll is required when using the
          fixed layout. -->

<script>
   /*$(".moduleContent").click(function(e){	   	  
       window.location = $(this).find("a:first").attr("href");
       return false;
   });*/
   </script>
<script>
      $('.targetDiv').hide();

      $(function(){
          
            $('.showSingle').click(function(){
              var index = $(this).parent().index(),
                  newTarget = $('.targetDiv').eq(index);
              $('.targetDiv').not(newTarget).fadeOut('fast');
              newTarget.delay('fast').fadeToggle('fast');
              return false;
            });
            $('.targetDiv').click(function(e){
              e.stopPropagation();
            });

        });
      $(function(){
        $(document).click(function(){
          var $el = $(".targetDiv");
          if($el.is(":visible")){
            $el.fadeOut(200);
          }
        });
      });

    </script>   
   <!-- Feedbackify -->
<script type="text/javascript">
var fby = fby || [];
fby.push(['showTab', {id: '9871', position: 'right', color: '#EB0000'}]);

(function () {
   var f = document.createElement('script'); f.type = 'text/javascript'; f.async = true;
   f.src = '//cdn.feedbackify.com/f.js';
   var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(f, s);
})();
</script>