<?php 

use Common\ActionForms\ExplorerForm;
use Common\Utilities\Constants;
use Zend\Session\SessionManager;
use Zend\Session\Container;
$session = new Container('user');

?>


<div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
           <h1>
            <i class="fa fa-user"></i> Update Profile
          </h1>
          <ol class="breadcrumb">
            <li><a href="/user/index"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li class="active">Update Profile</li>
          </ol>
        </section>
        <!-- Main content -->
        
        <form name="" method="post" action="">
          <section class="content">
            <div class="row">
              <div class="col-lg-10 col-lg-offset-1">
                <div class="box box-default box-solid">
                  
                  <div class="box-body">
                            <?php if($this->success){?>
                            <div id="advexpsuccessdiv" class="alert alert-success col-sm-12" >
                                  <div class="info-text-container-success ">
                                      <i class="fa fa-check "></i> 
                                      <span class="info-text" id="advexpsuccess"> Your information has been saved successfully
                                      </span>
                                   </div>
                                </div> 
                            <?php }?>

                    <div class="form-group">
                      <label for="currentState" class="col-sm-3 control-label">Email ID </label>
                      <div class="col-sm-5">
                        <input id="email" name="email" type="email"  value="<?php echo $session->username;?>" readonly="readonly" class="form-control" placeholder="Enter Email ID"> 
                      </div>
                    </div>
                    
                    <div class="clearfix"></div>
                    <div style="margin: 10px;"></div>
                    <div class="clearfix"></div>
                    <div class="form-group">
                      <label for="currentState" class="col-sm-3 control-label">Notification Preference </label>
                      <div class="col-sm-5">
                      
                       <label class="cbox btn btn-default" ><input type="checkbox" name="gennoti" id="general" value="general" <?php if($this->isgensub=="1"){?> checked="checked" <?php } ?> ><span class="st-radio-inline">General Notification</span></label>
                     <label class="cbox btn btn-default" ><input type="checkbox" name="usernoti" id="user" value="user" <?php if($this->isusersub=="1"){?> checked="checked" <?php } ?>><span class="st-radio-inline"> Organizer Notification</span></label>
                   
                      
                          </div>
                    </div>  
                    
                      
                    <div class="clearfix"></div>
                    <div class="form-group avatarContainer "  >
                      <label for="currentState" class="col-sm-3 control-label">Select Avatar</label>
                      <div class="col-sm-6" >
                        
                          <div class="avatarimg text-center" > 
                            <img src="/dist/img/avatar.png" alt="avatar" class="img-responsive" /><input type="radio" name="avatar" value="avatar.png">
                          </div>
                          <div class="avatarimg text-center">
                            <img src="/dist/img/avatar2.png" alt="avatar" class="img-responsive" /><input type="radio" name="avatar" value="avatar2.png">
                          </div>
                          <div class="avatarimg text-center">
                            <img src="/dist/img/avatar3.png" alt="avatar" class="img-responsive"/><input type="radio" name="avatar" value="avatar3.png">
                          </div>
                          <div class="avatarimg text-center" > 
                            <img src="/dist/img/avatar4.png" alt="avatar" class="img-responsive" /><input type="radio" name="avatar" value="avatar4.png">
                          </div>
                          <div class="avatarimg text-center">
                            <img src="/dist/img/avatar5.png" alt="avatar" class="img-responsive" />
                            <input type="radio" name="avatar" value="avatar5.png">
                          </div>
                          <div class="avatarimg text-center">
                            <img src="/dist/img/avatar6.png" alt="avatar" class="img-responsive"/>
                            <input type="radio" name="avatar" value="avatar6.png">
                          </div>
                        
                      </div>
                    </div>
                  </div> <!-- ./box body -->

                  <div class="box-footer text-center">
                    <button type="submit" class="btn btn-danger " >Update Profile</button>  
                  </div>



                </div> <!-- /box -->

              </div>
            </div>
          </section>
        </form>
      <!-- Main Footer -->
      
       <!-- jQuery 2.1.4 -->
    <script src="/plugins/jQuery/jQuery-2.1.4.min.js"></script>
    <!-- Bootstrap 3.3.2 JS -->
    <script src="/dist/js/bootstrap.min.js" type="text/javascript"></script>
    <!-- ChartJS 1.0.1 -->
    <script src="/plugins/chartjs/Chart.min.js" type="text/javascript"></script>

	<!-- Slimscroll -->
    <script src="/plugins/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <!-- FastClick -->
    <script src='/plugins/fastclick/fastclick.min.js'></script>
    <!-- AdminLTE App -->
    <script src="/dist/js/app.min.js" type="text/javascript"></script>
     