<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <link rel="icon" type="image/png" href="dist/img/favicon.ico">
    <title>UC and CSU Admissions Made Easy</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <meta name="description" content="UCEazy - UC and CSU Admissions Made Easy. An affordable software based solution for applying to public universities. UCEazy application is easy to use, understand and fit into a high school student's hectic lifestyle.  " />
    <meta name="keywords" content="UC admission, UC admissions, UC application, UC Essay, UC Personal Statement, Essay Review, UC admission help, UC admission advice, UC admission guidance, CSU admission, CSU admissions , CSU application, CSU admission help, CSU admission, advice, CSU admission guidance, GPA, GPA Calculator, UC GPA, CSU GPA, SAT to ACT conversion calculator, ACT to SAT conversion calculator , UC Activities and Awards, UC Resume, UC Cost of Attendance, UC Attendance Cost, CSU Cost of Attendance , CSU Attendance Cost, CSU application fee, CSU application cost, UC application fee, 
UC application cost,UC app costs, UC application costs, CSU app costs , CSU application costs, Explore, Plan, " />	
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <!-- Jquery UI -->
    <link href="/dist/css/jquery-ui.min.css" rel="stylesheet">
    <!-- Font Awesome Icons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!--<link href="dist/font-awesome-4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />-->
    <!-- Ionicons -->
    <!--<link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />-->
    <link href="/dist/ionicons-2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="/dist/css/AdminLTE.css" rel="stylesheet" type="text/css" />
    <link href="/dist/css/skins/skin-black.css" rel="stylesheet" type="text/css" />
    <!-- Custom style -->
    <link href="/dist/css/styles.css" rel="stylesheet" type="text/css" />
    <link href="/dist/css/adminstyle.css" rel="stylesheet" type="text/css" />
    <!-- Jquery Scroll bar style -->
    <link href="/dist/css/jquery.scrollbar.css" rel="stylesheet" type="text/css" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  
<?php
use Common\Utilities\Constants;
$allstates=explode(",",Constants::COUNTY);
$school_names = $this->result;


use Zend\Session\SessionManager;
use Zend\Session\Container;
use Common\Utilities;
use Common\Utilities\Languages;
$session = new Container('user');

?>
<style>

path{
  transition: 0.7s;
}
path:hover {
   -webkit-transform: scale(0.97);
    -moz-transform: scale(0.97);
    -o-transform: scale(0.97);
}

 </style>  
  
  
  <body  id="WSuceazy" class="abc skin-black fixed sidebar-collapse">
    <!-- Main Header -->
    
    <div  class="main-header " >
      <!-- Main Header -->
                <nav class="navbar navbar-static-top" role="navigation" >
        <!-- Logo -->
        <a href="/" class="logo logoHome">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <!-- <span class="logo-mini"><b>A</b>LT</span>-->          
          <!-- logo for regular state and mobile devices -->
          <img src="/dist/img/logo-uceazy1.png"  />
        </a>

        <!-- Header Navbar -->
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
             <span class="hidden-xs">MENU</span> <span class="sr-only">Toggle navigation</span>
          </a>
          <!-- Navbar Right Menu -->
          <!-- Navbar Right Menu -->
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <!-- language -->
              <!-- Signin -->
              <li>
                <!-- Menu toggle button -->
                <a href="https://uceazyblog.wordpress.com/" target="_blank" >
                  <i class="fa fa-rss-square"></i> Blog
                </a>
              </li>
              
              <?php 
              
              if(!isset($session->username)){
              ?>
              
              <li>
                <!-- Menu toggle button -->
                <a href="/user/signin" >
                  <i class="fa fa-sign-in"></i> Sign in
                </a>
              </li>
              <!-- Signup -->
              <li>
                <!-- Menu toggle button -->
                <a href="/user/signup" >
                  <i class="fa fa-pencil-square-o"></i> Sign up
                </a>
              </li>      
              <?php }else{?>
              
              <li>
                <!-- Menu toggle button -->
                <a href="/user/index" >
                  <i class="fa fa-sign-in"></i> Home
                </a>
              </li>
              <!-- Signup -->
              <li>
                <!-- Menu toggle button -->
                <a href="/user/logout" >
                  <i class="fa fa-pencil-square-o"></i>Log out
                </a>
              </li>  
              <?php }?>        
            </ul>
          </div>
          </div>
          <div class="clearfix"></div>
        </nav>

            
      <!-- Left side column. contains the logo and sidebar -->
      <aside class="main-sidebar">

        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
          <!-- Sidebar Menu -->
          <ul class="sidebar-menu">
            <li class="header">Menu</li>
            <li ><a href="/"><i class='fa fa-home'></i> <span>Home</span></a></li>       
            <li class="treeview"><a href="/#servicesmodule"><i class="fa fa-circle-o"></i> <span>UCEazy Services</span><i class="fa fa-angle-left pull-right"></i></a>
                <ul class="treeview-menu">
                  <li><a href="/#essayreview"><i class='fa fa-compass'></i> <span>Essay Review</span></a></li>
                </ul>
            </li>     
            <li class="treeview active"><a href="#modules"><i class="fa fa-circle-o"></i> <span>UCEazy Modules</span><i class="fa fa-angle-left pull-right"></i></a>
                <ul class="treeview-menu">
                  <li><a href="/#explore"><i class='fa fa-compass'></i> <span>Explore</span></a></li>
                  <li><a href="/#plan"><i class='fa fa-gear'></i> <span>Plan</span></a></li>
                </ul>
            </li>     
            <li><a href="/#story"><i class='fa fa-book'></i> <span>Our Story</span></a></li>
            <li><a href="/#team"><i class='fa fa-group'></i> <span>Our Team</span></a></li>
            <li><a href="/#expert"><i class='fa fa-user'></i> <span>For Educators</span></a></li>
            <li><a href="/#contact"><i class='fa fa-location-arrow'></i> <span>Contact Us</span></a></li>
          </ul>             
        </section>
        <!-- /.sidebar -->
      </aside>

      <!-- Content Wrapper. Contains page content -->
        <!-- Content Header (Page header) -->
        <section class="content-header">
           <h1>
            <i class="ion ion-android-compass"></i>Explore
            <small>Create your college list</small>
          </h1>
          
        </section>

        <!-- Main content -->
        <section class="content simpleExplore features">
        <!-- Explore Form -->
          <div class="row">
            
            <!-- Right side content -->
            <div class="col-lg-3 col-md-12 col-sm-12 col-xs-12 col-lg-push-9 rightSideContainer">
                <div class="box box-warning ">
                    <div class="box-header with-border">
                      <h3 class="box-title"><i class="fa fa-file-video-o"></i> Hear from An Expert</h3>
                    </div>
                  <div class="box-body" >
                    <!-- <div class="embed-responsive embed-responsive-16by9">
                      <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/sqpw3NynsTE"></iframe>
                    </div>-->
                    <div id="myCarousel" class="carousel slide" data-interval="false">
                      <!-- <ol class="carousel-indicators">
                        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                        <li data-target="#myCarousel" data-slide-to="1" class=""></li>
                      </ol>-->
                      <div class="carousel-inner">
                        <div class="item active">
                          <div class="embed-responsive embed-responsive-16by9">
                            <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/YcYn-XRfhck?showinfo=0&amp;" allowfullscreen></iframe>
                          </div>
                        </div>
                      </div>
                      <!-- <a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>
                      <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a>-->
                    </div>
                  
                  </div><!-- /.box-body -->
                </div><!-- /.box -->           

            </div>
            <!-- ./Right side content -->


            <div class="col-lg-9 col-md-12 col-sm-12 col-xs-12 col-lg-pull-3">
              <form class="form-horizontal" name="simpleexploreform" id="simpleexploreform">
                <div class="box box-default box-solid">
                <div class="box-header  bg-green1">
                  <h3 class="box-title">Please enter your information</h3>
                  </div><!-- /.box-header -->
                <!-- form start -->
                
                 <!-- Success -->  
                 <div id="simpleexpsuccessdiv" class="alert alert-success col-sm-12" style="display: none;">
                <div class="info-text-container-success ">
                    <i class="fa fa-check "></i> 
                    <span class="info-text" id="simpleexpsuccess">
                    </span>
                 </div>
              </div>
              <!-- Error -->
                <div id="simpleexperrordiv" class="alert alert-danger col-sm-12" style="display: none;">
                <div class="info-text-container-failure ">
                    <i class="fa fa-close "></i> 
                    <span class="info-text" id="simpleexperror">
                    </span>
                 </div>
              </div>
              
                  <div class="box-body">

                        <div class="form-group">
                          <label for="currentState" class="col-lg-3 col-md-3 col-sm-4 control-label">Current State <span class="mandatory">*</span></label>
                          <div class="col-lg-6 col-md-6 col-sm-7 col-xs-12">
                            <div class="radio" >
                                <label class="radio-inline" >
                                  <input type="radio" name="state"  value="CA" id="cal">
                                  California
                                </label>
                                <label class="radio-inline">
                                  <input type="radio" name="state" value="AUS" id="aus" >
                                  Another US State
                                </label>
                                <label class="radio-inline">
                                  <input type="radio" name="state" value="OUS" id="ous" >
                                  Outside US
                                </label>
                             </div>
                          </div>
                        </div>
                        
                        <div class="form-group">
                          <label for="californiaCounty" class="col-lg-3 col-md-3 col-sm-4 control-label">California County <span class="mandatory">*</span>
                          </label>
                          <span class="tooltipContent visible-xs-inline"> <a href="#" data-toggle="tooltip" data-html="true" class="tip-right" data-original-title="Which county do you currently live in?">
                            <i class="fa fa-info-circle "></i></a> 
                          </span>
                          <div class="col-lg-5 col-md-5 col-sm-5 col-xs-10">
                              <select name="county" id="county" class="form-control">
                                <option value="-1">Select</option>
                                   <?php foreach ($allstates as $val){?>
                                  <option value="<?php echo $val;?>" ><?php echo $val;?></option>
                                 <?php }?>
                                  
                              </select>
                          </div>
                          <div class="tooltipContent hidden-xs"> <a href="#" data-toggle="tooltip" data-html="true" class="tip-right" data-original-title="Which county do you currently live in?">
                            <i class="fa fa-info-circle "></i></a> 
                          </div>
                        </div>
                        
                        <div class="form-group" >
                          <div id="schoolName">
                            <label for="highSchoolName" class="col-lg-3 col-md-3 col-sm-4 control-label">Current School Name <span class="mandatory">*</span>
                            </label>
                            <span class="tooltipContent visible-xs-inline "> <a href="#" data-toggle="tooltip" class="tip-right" data-original-title="What high school are you currently attending?">
                              <i class="fa fa-info-circle "></i></a> 
                            </span>
                            <div class="col-lg-5 col-md-5 col-sm-5 col-xs-10">
                            
								<input id="school" name="school" type="text" class="form-control timepicker" placeholder="Enter School Name" >
								</div><!-- /.input group -->
                          
                            <div class="tooltipContent hidden-xs"> <a href="#" data-toggle="tooltip" class="tip-right" data-original-title="What high school are you currently attending?">
                              <i class="fa fa-info-circle "></i></a> 
                            </div>
                          </div>
                        </div>

                        <div class="form-group">
                          <label for="highSchoolName" class="col-lg-3 col-md-3 col-sm-4 control-label">Standardized Test(s) <span class="mandatory">*</span></label>
                          <span class="tooltipContent visible-xs-inline"> <a href="#" data-toggle="tooltip" data-html="true" class="tip-right" data-original-title="Enter your scores from either the <b>SAT/ACT</b>. If you have taken a test more than once, choose the one with the highest total score. Do not mix scores from multiple tests. A <b>PSAT</b> or sample scores will suffice if you do not have SAT/ACT scores yet.">
                              <i class="fa fa-info-circle "></i></a> 
                          </span>
                          <div class="col-sm-5 col-xs-12">
                              <label class="cbox btn btn-default " ><input type="radio" name="exam" id="act" value="act" ><span class="st-radio-inline"> ACT</span></label>
                              <label class="cbox btn btn-default" ><input type="radio" name="exam" id="sat" value="sat"><span class="st-radio-inline"> SAT</span></label>
                              <label class="cbox btn btn-default" ><input type="radio" name="exam" id="psat" value="psat"><span class="st-radio-inline"> PSAT</span></label>
                          </div>                        
                          <div class="tooltipContent hidden-xs"> <a href="#" data-toggle="tooltip" data-html="true" class="tip-right" data-original-title="Enter your scores from either the <b>SAT/ACT</b>. If you have taken a test more than once, choose the one with the highest total score. Do not mix scores from multiple tests. A <b>PSAT</b> or sample scores will suffice if you do not have SAT/ACT scores yet.">
                              <i class="fa fa-info-circle "></i></a> 
                          </div>
                        </div><!-- /Standardized Test(s) -->

                        <!-- hidden divs -->
                        <div class="act testsContainer" >
                          <div class="form-group ">
                            <label for="score" class="col-lg-3 col-md-3 col-sm-4 control-label">ACT Composite <span class="mandatory">*</span></label>
                            <div class="col-sm-5 col-xs-12">
                              <div class="sliderContainer">
                                <div class="slider col-lg-10 col-md-10 col-sm-9 col-xs-9" id="slider1" data-begin="1" data-end="36" data-step="1" maxlength="2" data-validate="yes" data-rules="type:numeric,max_length:2,min:1,max:36" ></div>
                                <input type="number" value="0" min="1" max="36" class="score ticker" name="act" id="slider1_score" />
                              </div>
                            </div>
                          </div>
                          <div class="form-group ">
                            <label for="score" class="col-lg-3 col-md-3 col-sm-4 control-label">ACT Combined English/Writing <span class="mandatory">*</span></label>
                            <div class="col-sm-5">
                              <div class="sliderContainer">
                                <div class="slider col-lg-10 col-md-10 col-sm-9 col-xs-9" id="slider2" data-begin="1" data-end="36" data-step="1"></div>
                                <input type="number" value="1" min="1" max="36" class="score ticker" name="actew" id="slider2_score" maxlength="2" data-validate="yes" data-rules="type:numeric,max_length:2,min:1,max:36" />
                              </div>
                            </div>
                          </div>                          
                        </div><!-- /ACT -->

                        <div class="sat testsContainer" >
                          <div class="form-group ">
                            <label for="score" class="col-lg-3 col-md-3 col-sm-4 control-label">Critical Reading <span class="mandatory">*</span></label>
                            <div class="col-sm-5">
                              <div class="sliderContainer">
                                <div class="slider col-lg-10 col-md-10 col-sm-9 col-xs-9" id="slider3" data-begin="200" data-end="800" data-step="10"></div>
                                <input type="number" value="200" min="200" max="800" step="10" class="score ticker" id="slider3_score" name="satread" maxlength="3" data-validate="yes" data-rules="type:numeric,max_length:3,min:200,max:800,divide_by:10"  />
                              </div>
                            </div>
                          </div>
                          <div class="form-group ">
                            <label for="score" class="col-lg-3 col-md-3 col-sm-4 control-label">Math <span class="mandatory">*</span></label>
                            <div class="col-sm-5">
                              <div class="sliderContainer">
                                <div class="slider col-lg-10 col-md-10 col-sm-9 col-xs-9" id="slider4" data-begin="200" data-end="800" data-step="10"></div>
                                <input type="number" value="200" min="200" max="800" step="10"  class="score ticker" id="slider4_score" name="satmath" maxlength="3" data-validate="yes" data-rules="type:numeric,max_length:3,min:200,max:800,divide_by:10"  />
                              </div>
                            </div>
                          </div>
                          <div class="form-group">
                           <label for="score" class="col-lg-3 col-md-3 col-sm-4 control-label">Writing <span class="mandatory">*</span></label>
                            <div class="col-sm-5">
                              <div class="sliderContainer">
                                <div class="slider col-lg-10 col-md-10 col-sm-9 col-xs-9" id="slider5" data-begin="200" data-end="800" data-step="10"></div>
                                <input type="number" value="200" min="200" max="800" step="10"  class="score ticker" id="slider5_score" name="satwrite" maxlength="3" data-validate="yes" data-rules="type:numeric,max_length:3,min:200,max:800,divide_by:10" />
                              </div>
                            </div>
                          </div>
                        </div><!-- /SAT -->

                        <div class="psat testsContainer" >
                          <div class="form-group ">
                            <label for="score" class="col-lg-3 col-md-3 col-sm-4 control-label">Critical Reading <span class="mandatory">*</span></label>
                            <div class="col-sm-5">
                              <div class="sliderContainer">
                                <div class="slider col-lg-10 col-md-10 col-sm-9 col-xs-9" id="slider6" data-begin="20" data-end="80" data-step="1"></div>
                                <input type="number" value="20" min="20" max="80" class="score ticker" id="slider6_score" name="psatread" maxlength="2" data-validate="yes" data-rules="type:numeric,max_length:2,min:20,max:80" />
                              </div>
                            </div>
                          </div>
                          <div class="form-group ">
                            <label for="score" class="col-lg-3 col-md-3 col-sm-4 control-label">Math <span class="mandatory">*</span></label>
                            <div class="col-sm-5">
                              <div class="sliderContainer">
                                <div class="slider col-lg-10 col-md-10 col-sm-9 col-xs-9" id="slider7" data-begin="20" data-end="80" data-step="1"></div>
                                <input type="number" value="20" min="20" max="80" class="score ticker" id="slider7_score" name="psatmath" maxlength="2" data-validate="yes" data-rules="type:numeric,max_length:2,min:20,max:80" />
                              </div>
                            </div>
                          </div>
                          <div class="form-group">
                           <label for="score" class="col-lg-3 col-md-3 col-sm-4 control-label">Writing <span class="mandatory">*</span></label>
                            <div class="col-sm-5">
                              <div class="sliderContainer">
                                <div class="slider col-lg-10 col-md-10 col-sm-9 col-xs-9" id="slider8" data-begin="20" data-end="80" data-step="1"></div>
                                <input type="number" value="20" min="20" max="80" class="score ticker" id="slider8_score" name="psatwrite" maxlength="2" data-validate="yes" data-rules="type:numeric,max_length:2,min:20,max:80" />
                              </div>
                            </div>
                          </div>
                        </div><!-- /PSAT -->
                        <!-- /hidden divs -->

                        <div class="form-group">
                          <label for="highSchoolName" class="col-lg-3 col-md-3 col-sm-4 control-label">Weighted GPA <span class="mandatory">*</span></label><span class="tooltipContent visible-xs-inline"> <a href="#" data-toggle="tooltip" data-html="true" class="tip-right" data-original-title="Enter your UC/CSU GPA. Another alternative is your 10-12th grade weighted GPA. GPA Calculator coming soon!">
                              <i class="fa fa-info-circle "></i></a> 
                          </span> 
                          <div class="col-sm-5">
                            <div class="sliderContainer">
                              <div class="slider col-lg-10 col-md-10 col-sm-9 col-xs-9" id="slider9" data-begin="1" data-end="5" data-step="0.01"></div>
                              <input type="number" value="1" min="1" max="5" class="score ticker" id="slider9_score"  name="gpa" step="0.01" maxlength="4" data-validate="yes" data-rules="type:decimal,max_length:4,min:1.00,max:5.00"/>
                            </div>
                          </div>  
                          <div class="tooltipContent hidden-xs"> <a href="#" data-toggle="tooltip" data-html="true" class="tip-right" data-original-title="Enter your UC/CSU GPA. Another alternative is your 10-12th grade weighted GPA. GPA Calculator coming soon!">
                              <i class="fa fa-info-circle "></i></a> 
                          </div>                  
                        </div><!-- /Weighted GPA -->

                    </div><!-- /.widget box -->

                  <div class="box-footer text-center">
                    <div class="col-lg-9">
                    <button type="button" id="btn-simpleexp" class="btn btn-danger btnInteractive" data-loading-text="Loading...." data-reset-text="Show Me My List">Show Me My List</button>
                    </div>
                    <div class="col-lg-3">&nbsp;</div>
                  </div><!-- /.box-footer -->
                </form>

              </div><!-- /.box -->

              <!-- Result -->
              <form id="shareresultform" action="" method="post">
              <div id="result" class="resultContainer">
                <div class="box box-default ">

                  <div class="box-header with-border text-center">
                    <h3 class="box-title">My List</h3>
                    <a href="#" data-toggle="tooltip" data-html="true" class="tip-right" data-original-title="<b>Reach</b>: A college whose average test scores/GPA are HIGHER than yours. It will be harder to get admitted to these colleges. <br /> <br /> <b>Target</b>: A college whose average test scores/GPA are CLOSE to yours. You will probably be admitted to these colleges. <br/><br/><b> Safety</b>: A college whose average test scores/GPA are BELOW yours. You will very likely be admitted to these colleges. <br/><br/> <b>COA</b> Cost of Attendance = Estimated Tuition, Fees, Room/Board, Books/Supplies, Transportation, Personal Expenses">
                                <i class="fa fa-info-circle "></i></a> 
                  </div><!-- /.box-header -->
                <!-- form start -->
                  <div class="box-body">
                    <div class="alert alert-info alert-dismissable text-center">
                      <h4>Freshmen Application Submission Deadline is November 30th</h4>                      
                    </div>
                    <div class="chart-holder col-lg-12  col-xs-12">
                      <div class="donut_chart text-center" id="donut">
                    </div>
                  </div>

                  <div class="box-footer text-center">
                    
                    <button id="semailbut" type="button" class="btn btn-danger" data-loading-text="Loading...." data-reset-text="Email My Result">Email My Result</button>
                  </div><!-- /.box-footer -->
                </div>
              </div>

              <div class="box box-default ">
                <div class="box-body">
                  <div class="row" id="semail" class="text-center"  class="sendMailContainer">
                      <div class="col-sm-6 col-sm-offset-2 label-title">
                        <input type="text" name="shareemail" class="form-control col-sm-6 " id="inputemail" placeholder="Email id">
                      </div>
                      <div class="col-sm-3 text-left">
                        <button type="submit"  name="sendmail"  value="sendmail" class="btn btn-danger" id="emailsendresult">Send</button>
                      </div>
                   </div>
                </div>
              </div>
              </div>
              </form>


            </div>
            
            

          </div><!-- /.row -->
        </section><!-- /.content -->
      
       <!-- Main Footer -->
       <footer class="main-footer">
        <!-- Default to the left -->
        <div class="copyRight col-lg-3 col-md-12 col-sm-12 col-xs-12">Copyright &copy; 2015 <a href="/">UCEazy</a>. All rights reserved.
        </div>
        <div class="text-center col-lg-6 col-md-12 col-sm-12 col-xs-12">
          This web application is best viewed on desktops and tablets. App for smartphones will be coming soon!
        </div>
        <!-- To the right -->
        <div class="footer-links col-lg-3 col-md-12 col-sm-12 col-xs-12">
          <ul>
            <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>
            <li><a href="/index/faq" title="FAQ" > FAQ</a></li>
            <li><a href="/index/terms" title="Terms of Use" > Terms of Use</a></li>
            <li><a href="/index/privacy" title="Privacy Policy" > Privacy Policy</a></li>
			       
          </ul>
        </div>
        <div class="followUs visible-xs text-center" >
            Follow us on: 
              <div  class="fixedBtn"><a href="https://www.facebook.com/askuceazy" class="bg-facebook" target="_blank"><i class="fa fa-facebook"></i></a></div>
              <div class="fixedBtn"><a href="https://twitter.com/Uaskuceazy?lang=en" class="bg-twitter" target="_blank"><i class="fa fa-twitter"></i></a></div>
              <div class="fixedBtn"><a href="https://www.linkedin.com/company/uceazy" class="bg-linkedin" target="_blank"><i class="fa fa-linkedin"></i></a></div>
			  <div class="fixedBtn"><a href="https://instagram.com/uceazy/" class="bg-instagram" target="_blank"><i class="fa fa-instagram"></i></a></div>
          </div>  
        <div class="clearfix"></div>
      </footer>

      <!-- Fixed sidebar -->
      <div id="fixedSidebar" class="fixedSidebar hidden-xs">
          <div class="btnContainer">
            <div  class="fixedBtn1"><a href="https://www.facebook.com/askuceazy" class="bg-facebook" target="_blank"><i class="fa fa-facebook"></i></a></div>
            <div class="fixedBtn1"><a href="https://twitter.com/Uaskuceazy?lang=en" class="bg-twitter" target="_blank"><i class="fa fa-twitter"></i></a></div>
            <div class="fixedBtn1"><a href="https://www.linkedin.com/company/uceazy" class="bg-linkedin" target="_blank"><i class="fa fa-linkedin"></i></a></div>
			<div class="fixedBtn1"><a href="https://instagram.com/uceazy/" class="bg-instagram" target="_blank"><i class="fa fa-instagram"></i></a></div>
          </div>
          
      </div>
      <!-- fixed side bar -->

      <!-- Fixed sidebar 
      <div id="fixedSidebar" class="fixedSidebar hidden-xs">
          <div class="btnContainer">
            <div  class="fixedBtn"><a href="#" class="bg-facebook"><i class="fa fa-facebook"></i></a></div>
            <div class="fixedBtn"><a href="#" class="bg-twitter"><i class="fa fa-twitter"></i></a></div>
            <div class="fixedBtn"><a href="#" class="bg-linkedin"><i class="fa fa-linkedin"></i></a></div>
            <div class="fixedBtn"><a href="#" class="bg-google-plus"><i class="fa fa-google-plus"></i></a></div>
            <div class="fixedBtn"><a href="#" class="bg-instagram"><i class="fa fa-instagram"></i></a></div>
            <div class="fixedBtn"><a href="#" class="bg-pinterest"><i class="fa fa-pinterest"></i></a></div>
          </div>
          
      </div>-->
      <!-- */fixed side bar -->

     <!-- popup -->
      <div class="modal fade" id="planpopup" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header btn-danger">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title " id="myModalLabel">Plan</h4>
            </div>
            <div class="modal-body">
              Thanks for trying Advanced EXPLORE! Stay tuned for PLAN, your personalized guide to achieving your college goals - coming soon to the App Store and Google Play!
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <!-- <button type="button" class="btn btn-primary">Save changes</button>-->
            </div>
          </div>
        </div>
      </div>
     <!-- /popup -->
    <!-- REQUIRED JS SCRIPTS -->

<!-- REQUIRED JS SCRIPTS -->

    <!-- d3 chart scripts -->
    <script src="/dist/js/d3/jquery2.min.js"></script>
    <script src="/dist/js/d3/d3.min.js"></script>
    <script src="/dist/js/d3/underscore-min.js"></script>

   <!-- jQuery 2.1.4 -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script>
    // Fallback to loading jQuery from a local path if the CDN is unavailable
    (window.jQuery || document.write('<script src="plugins/jQuery/jQuery-2.1.4.min.js"><\/script>'));
    </script>

    
    <!-- uislider -->
    <script src="/dist/js/jquery-ui.min.js"></script>

    <script src="/dist/js/jquery.ui.touch-punch.min.js"></script>
    <!-- Bootstrap 3.3.2 JS -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <script>
    // Fallback to loading jQuery from a local path if the CDN is unavailable
    ($.fn.modal || document.write('<script src="dist/js/bootstrap.min.js"><\/script>'));
    </script>
    
    <!-- Bootstrap css fallback -->
    <script>
      (function($) {
          $(function() {
              if ($('body').css('color') !== 'rgb(51, 51, 51)') {
                  $('head').prepend('<link rel="stylesheet" href="dist/css/bootstrap.min.css">');
              }
          });
      })(window.jQuery);
    </script>


 <script>
  $(function() {
    var availableTags = <?php echo $this->allschool; ?>;
    $( "#school" ).autocomplete({
    	 maxResults: 10,
    	    source: function(request, response) {
    	        var results = $.ui.autocomplete.filter(availableTags, request.term);
    	        
    	        response(results.slice(0, this.options.maxResults));
    	    }
     
    });
  });
  </script>



    <!-- Font awesome fallback -->
    <script>
        (function($){
            var $span = $('<span class="fa" style="display:none"></span>').appendTo('body');
            if ($span.css('fontFamily') !== 'FontAwesome' ) {
                // Fallback Link
                $('head').append('<link href="dist/font-awesome-4.3.0/css/font-awesome.min.css" rel="stylesheet">');
            }
            $span.remove();
        })(jQuery);
    </script>
    <!-- InputMask -->
    <script src="/plugins/input-mask/jquery.inputmask.js" type="text/javascript"></script>
    <script src="/plugins/input-mask/jquery.inputmask.date.extensions.js" type="text/javascript"></script>
    <script src="/plugins/input-mask/jquery.inputmask.extensions.js" type="text/javascript"></script>

    <!-- ChartJS 1.0.1 -->
    <script src="/plugins/chartjs/Chart.min.js" type="text/javascript"></script>

    <!-- Slimscroll -->
    <script src="/plugins/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <!-- FastClick -->
    <script src='/plugins/fastclick/fastclick.min.js'></script>
    <!-- AdminLTE App -->
    <script src="/dist/js/app.min.js" type="text/javascript"></script>
    <!-- Custom Script -->
    <script src="/dist/js/custom.js" type="text/javascript"></script>

    <!-- jquery scrollbar Script -->
    <script src="/dist/js/jquery.scrollbar.min.js" type="text/javascript"></script>
	 <!-- custom validation Script -->
	<script src="/dist/js/validation.js"></script>

    <script>
    // When the DOM is ready, run this function
      $(document).ready(function() {
          //tool tip
        $(function () {
        $('[data-toggle="tooltip"]').tooltip()
        });
      });
    </script>

<!-- Rande slider -->
<script>
    $(function () {
      $(".slider").each(function () {
        var begin = $(this).data("begin"),
            end = $(this).data("end");
        step = $(this).data("step");
        $(this).slider({
            range: "min",
            value: 1,
            min: begin,
            max: end,
            step: step,
            slide: function (event, ui) {
                //update text box quantity
                var sliderscore = ("#" + $(this).attr("id") + "_score");
                $(sliderscore).val(ui.value);
				$(sliderscore).trigger("keyup");

            }
        });

        //initialise text box quantity
        var sliderscore = ("#" + $(this).attr("id") + "_score");
        $(sliderscore).val($(this).slider("value"));
    });
    
    $('.score').change(function () {
         var value = this.value,
             selector = $("#" + this.id.split('_')[0]);
         selector.slider("value", value);
     });

    /* Show/Hide divs */
    $("#result").hide();
    $("#semail").hide();
    $(".sat").hide(), $(".act").hide(), $(".psat").hide();
    $('input[type="radio"]').click(function(){
        if($(this).attr("value")=="sat"){
            $(".sat").toggle();
            $(".sat .checked").css('background', 'red');
            $(".psat").hide();
            $(".act").hide();
            $("#result").hide();
        }
        if($(this).attr("value")=="act"){
            $(".act").toggle();
            $(".psat").hide();
            $(".sat").hide();
            $("#result").hide();
        }
        if($(this).attr("value")=="psat"){
            $(".psat").toggle();
            $(".act").hide();
            $(".sat").hide();
            $("#result").hide();
        
        }
    });
  });
</script>



<!-- Result - Chart -->
<script>

function drawChart(json){
    var input_data=JSON.parse(json);
    
  var all_arc_size = [];
  var def_gap_size = 0.5;
  var def_arc_size = 10;
  var color_dict = {};
  var group_size;
  var iter_count = 0
  var outer_dict_count = 0;
// outer arc
  var outer_arc_size = [];

  var width = 600,
      height = 600,
      radius = Math.min(width-50, height-50) / 2;

  var color = d3.scale.category20();

  var pie = d3.layout.pie()
      .sort(null);

  var arc = d3.svg.arc()
      .innerRadius(radius - 100)
      .outerRadius(radius - 20);

  var outer_arc = d3.svg.arc()
      .innerRadius(radius - 5)
      .outerRadius(radius - 15);

 var empty_content = {"Safety": ["Why is this empty?  ", "Your grades and/or test scores may be lower than ","what the UC and CSU colleges are looking for."],
  "Target": ["Why is this empty?  ","Your grades and/or test scores may not match exactly","what the UC and CSU colleges are looking for.  ","You might fall just below or just above their standards."],
  "Reach":["Why is this empty?  ","Your grades and/or test scores may be so strong ","that they exceed what the UC and CSU colleges are looking for."]
  }

    var signin_content = ["Want more personalized results?", "Try Advanced EXPLORE!"]

    rows()
  
 function rows() {
    //console.log(input_data);
    var key_value_lenth = {}
    var color_dict = _.object(_.keys(input_data),  ["#9adcfd", "#FFA500", "#00ff00"]);
    var outer_color_dict = _.object(_.keys(input_data),  ["#065EC8", "#CE8600", "#006a00"]);
    //var outer_color_dict = _.object(_.keys(input_data), ["#AE5CF0", "#0099FF", "#FF3399"]);
    _.each(_.keys(input_data), function(d){
      var i =0;
      _.each(_.values(input_data[d]), function(d){
        all_arc_size.push(def_arc_size);
        i++;
      });
      if (i >0)
      {
        outer_arc_size.push(i*10);
      }
      all_arc_size.push(def_gap_size);
      outer_arc_size.push(def_gap_size);
      key_value_lenth[d] = input_data[d].length;
    })

    var group_keys = _.keys(key_value_lenth);
    var group_lengths = _.values(key_value_lenth); // Gives me an array of lengths by group.
    group_size = group_lengths[0];
    var group_iter_count = -1
  // Outer SVG
    d3.ns.prefix.xmlns = "https://www.w3.org/1999/xlink"
    var svg = d3.select(".donut_chart").append("svg")
                .attr("id", "svg-circle")
                .attr("width", width)
                .attr ("height", height)
                .attr("xmlns:xlink", "https://www.w3.org/1999/xlink")
                .append("g")
                .attr("class", "donut_container");

    var outer_radius = 400
    var outer_arcs = svg.append("g").attr("transform", "translate(" + (radius + 20) + "," + (radius + 20) + ")")
                        .selectAll("path")
                        .data(pie(all_arc_size))
                        .enter()
                        .append("g")
                        .attr("class","arc");

        outer_arcs.append("path")
            .attr("fill", function(d, i) { return color_generator(d, i); })
            .attr("id", function(d,i){ return set_label_id(d, i); })
            .attr("d", outer_arc);
  var text1 = outer_arcs.append("text")
                        .attr("x", 100)
                        .attr("dy", -10);

      text1.append("textPath")
                  .attr("fill",function(d, i) { return color_generator_text(d, i); })
                  .attr("font-family", "sans-serif")
                  .attr("font-size", "23px")
				  .attr("font-weight", "bold")
                  //.attr("stroke-width", "0.5")
                  .attr("xlink:href",function(d,i){ return "#"+ set_label_id(d, i); })
                  .text(function(d, i) { return set_label_id(d,i); });

  function set_label_id(d, i) {
    if (i < group_size) {
      group_iter_count = group_iter_count + 1;
      if (group_iter_count === 0) {
        return group_keys[iter_count];
      }
    } else {
      update_counter();
    }
    return " ";
  }
  //==========================
  // Inner SVG
  //==========================
    var arcs = svg.append("g").attr("transform", "translate(" + (radius + 20) +"," + (radius + 20) +")").selectAll("path")
                  .data(pie(all_arc_size))
                  .enter()
                  .append("g")
                  .attr("class","arc")
                  //.attr("transform", "translate(" + radius + "," + radius + ")");
                  //.attr("transform", "translate(" + width / 2 + "," + height / 2 + ")")

        arcs.append("path")
            .attr("stroke","#FFF")
            .attr("id", function(d,i){ return set_pathId(d, i); })
            .attr("fill", function(d, i) { return color_generator(d, i); })
            .attr("d", arc)
            .on("mouseover", dynamic_info_display);

    // Add a text label.
    var text = arcs
    	//.append("a")
        //.attr("xlink:href", function(d, i) { return set_url(d,i); })
        //.attr("target", "_blank")
        .append("text")
        .attr("dx", 20)
        .attr("dy", 40);

        text.append("textPath")
            .attr("fill","black")
            .attr("font-family", "sans-serif")
            .attr("font-size", "16px")
            //.attr("stroke-width", "0.5")
            .attr("xlink:href",function(d,i){ return "#"+ set_pathId(d, i); })
            .text(function(d, i) { return display_label(d,i); });

    function set_pathId(d, i) {
      if (i < group_size) {
        group_iter_count = group_iter_count + 1;
        return group_keys[iter_count]+"_"+group_iter_count;
      } else {
        update_counter();
        return "seperator";
      }
    }
    function color_generator(d, i) {
      if (i < group_size) {
        return color_dict[group_keys[iter_count]];
      } else if(group_size === i) {
        update_counter();
        return '#FFF';
      } else{
        return '#000';
      }
    }
	
	function color_generator_text(d, i) {
      if (i < group_size) {
        return outer_color_dict[group_keys[iter_count]];
      } else if(group_size === i) {
        update_counter();
        return '#FFF';
      } else{
        return '#000';
      }
    }

    function set_url(d, i) {
      if (i < group_size) {
          group_iter_count = group_iter_count + 1;
          if (typeof input_data[group_keys[iter_count]][group_iter_count].url === 'undefined')
          {
            return "#"
          }
          else {
            return input_data[group_keys[iter_count]][group_iter_count].url;
          }
      } else {
          update_counter();
          return '#';
      }
    }

    function display_label(d, i) {
      if (i < group_size) {
          group_iter_count = group_iter_count + 1;
          if (typeof input_data[group_keys[iter_count]][group_iter_count].name === 'undefined')
          {
            return input_data[group_keys[iter_count]][group_iter_count];
          }
          else {
            return input_data[group_keys[iter_count]][group_iter_count].name;
          }
      } else {
          update_counter();
          return '';
      }
    }

    function update_counter(){
      group_iter_count = -1;
      iter_count = iter_count + 1;
      if (iter_count === group_lengths.length) {
        group_size = group_lengths[0];
        iter_count = 0
      } else {
        group_size = group_size + group_lengths[iter_count] + 1
      }
    }

    var info_display_cont = svg.append("g")
                            .attr("id", "info_container")
                            .attr("transform", "translate(" + (radius+20) + "," + (radius+20)+ ")");

        info_display_cont.append("circle")
                                      .attr("fill","#ddd")
                                      .attr("r", "190")

        info_display_cont.append("g")
                          .attr("id", "dynamic_content")
                          .append("text")
                          .attr("text-anchor", "middle")
                          //.attr("x", -50)
                          .attr("dy", -100)
                          .attr("fill","white")
                          .attr("fill","#000")
                          .attr("font-size","24px")
                          .text(function(d){ return static_info_display(signin_content) });

        info_display_cont.append("a").attr("id", "dynamic_content")
                          .attr("xlink:href", "/user/signin")
                          .attr("target", "_top")
                          .append("text")
                          .attr("dx", "-50").attr("dy", "80")
                          .attr("font-size", "30px")
                          .attr("font-weight", "bold")
                          .text("Sign In")


//<a href="http://ucsd.edu/" target="_blank"><text dx="20" dy="40"><textPath fill="black" font-family="sans-serif" font-size="16px" href="#target_0">UC San Diego</textPath></text></a>


    var display_content = '';
    function static_info_display(data){
    	//console.log(display_content);
        d3.selectAll("#dynamic_content").remove();

        d3.select("g#info_container").selectAll("#dynamic_content")
          .data(data)
          .enter()
          .append("g")
          .attr("id", "dynamic_content")
          .attr("transform", "translate(" + -100 + "," + -40 + ")")
          .append("text")
          .attr("x", function(d, i){
            if (display_content != "No College Found") {
              return (i==0) ? "-65" : "-25"
            } else {
              return (i==0) ? "5" : "-50"
            }           
       	  })
          .attr("dy",  function(d,i){ 
            if (display_content != "No College Found") {
              return (i==0) ? "5" : (26 * i) + 30 
            } else {
              return (i==0) ? "-10" : (26 * i) + 5 
            }          	
          })
          .attr("fill","#000")
		  .attr("font-size",function(d, i){
            if (display_content != "No College Found") {
              return "23px"
            } else {
              return (i==0) ? "23px":"12px"
            }
          })
          //.attr("font-size", "23px")
          .attr("font-weight", function(d, i){ return  "bold"} )
          .text(function(d){ return d });
    }

    function dynamic_info_display(){
    	//console.log(d)
    	var hover_id = d3.select(this).attr("id");
      	//console.log(hover_id);

      	if (hover_id !== "seperator") {
	        splitted_id = hover_id.split("_");
	        key = splitted_id[0];
	        value = splitted_id[1];
	        display_content = input_data[key][value];			
			//console.log(display_content);
	        
	        if (display_content == "No College Found"){
	          data = empty_content[key]
	        } else {
	          data = signin_content
	        }	        
			
			static_info_display(data);

			if (display_content != "No College Found"){
			  info_display_cont.append("a").attr("id", "dynamic_content")
			      .attr("xlink:href", "/user/signin")
			      .attr("target", "_top")
			      .append("text")
			      .attr("dx", "-50").attr("dy", "80")
			      .attr("font-size", "30px")
			      .attr("font-weight", "bold")
			      .text("Sign In")			
			}
      }
    }
  // var info_label_dict = {"name":"Name", "relativeCOA": "Relative Cost of Attendance", "onCampusCOA": "On Campus Cost of Attendance", "offCampusCOA":"Offcampus Cost of Attendance", "size":"Size", "universitySystem":"University System", "environment": "Environment"}
 //  var info_label_dict = {"name":"Name", "relativeCOA": "COA Staying with Relatives", "onCampusCOA": "COA On Campus", "offCampusCOA":"COA Off Campus", "size":"Size", "universitySystem":"University System", "environment": "Environment"}
   var info_label_dict = {"name":"", "universitySystem":"University System", "size":"Total student population", "onCampusCOA": "living on campus", "relativeCOA": "living with parents/relatives"}

    function dynamic_text_info(key_reference){
      // alert(key_reference);
      if(info_label_dict.hasOwnProperty(key_reference)){
            var labelname = info_label_dict[key_reference];
      } else if(key_reference == "Cost of Attendance"){
              return key_reference;
      } else {
        return ;
      }

      if(key_reference=='offCampusCOA'){
          return null;
      }
      else if(key_reference.indexOf("COA") > -1){
          label = labelname +":  $" + formatNumber(display_content[key_reference])
      } else if(key_reference=='name'){
          label = display_content[key_reference]
      }else if(key_reference=='size'){
          label = labelname +": " + formatNumber(display_content[key_reference])
      }
      else {
          label = labelname +": " + display_content[key_reference]
      }
      return label;
    }
  //var simple_info_label_dict = {"Name", "Date of application : 30-May-2015", "Date of admission : 05-Sep-2015"}
    function simple_dynamic_text_info(key_reference){
      if(simple_info_label_dict.hasOwnProperty(key_reference)){
        var labelname = simple_info_label_dict[key_reference];
      } else {
        var labelname = key_reference;
      }

      if(key_reference.indexOf("COA") > -1){
        label = labelname +":  $" + display_content[key_reference]
      } else {
        label = labelname +": " + display_content[key_reference]
      }
      return label;
    }
  }

  
  function formatNumber (num) {
    if( isNaN(num)){
      return num;
    }
    return num.toString().replace(/(\d)(?=(\d{3})+(?!\d))/g, "$1,");
  }
  }

  function formatNumber (num) {
    if( isNaN(num)){
      return num;
    }
    return num.toString().replace(/(\d)(?=(\d{3})+(?!\d))/g, "$1,");

}


  $('#btn-simpleexp').click(function(e){
	  var btn = $(this)
  	  btn.button('loading');
  	
	  var data = {
		      "action": "test"
		    };
	 	    data = $("#simpleexploreform").serialize() + "&" + $.param(data);

	 	  // $("#result").show();
	 	  // drawWheel();
	 	    
	 	   $("#simpleexperror").html("");
	 	  $("#simpleexpsuccess").html("");
	 	 $("#simpleexperrordiv").hide();
	 	 e.preventDefault();
	 	  $("#simpleexpsuccessdiv").hide();
		    $.ajax({
		      type: "POST",
		      dataType: "json",
		      url: "/search/simple", 
		      data: data,
		      success: function(data) {
		    	  if(data['error']!=null){
		    		  $("#simpleexperrordiv").show();
					  setTimeout(function(){ $('#simpleexperrordiv').hide(); }, 10000);
		    		  $(".donut_chart").html("");
		    		  $("#result").hide();
       		       $("#simpleexperror").html(data['error']);
   		        }else{
   		         $(".donut_chart").html("");
   		        	
   		         $("#result").show();
   		      drawChart(data['data']);
   		        	$("#simpleexpsuccessdiv").show();
					setTimeout(function(){ $('#simpleexpsuccessdiv').hide(); }, 10000);
   		         $("#simpleexpsuccess").html("Search Successful! Please scroll down to see your results.");
   		        }
		      },
		      error: function(xhr, textStatus, errorThrown){
		          alert('Whoops!  It looks like there was a problem submitting your request. Please try again. If the problem persists, please contact us.');
		       },
		       complete: function(xhr, textStatus){
			   		  btn.button('reset');
		   		}
		    });
		    return false;


		      
});

  $('#emailsendresult').click(function(e){
	  var btn = $(this)
  	  btn.button('loading');
  	 
	  var data = {
		      "action": "undefined"
		    };
	 	    data = $("#shareresultform").serialize() + "&" + $.param(data);

	 	  // $("#result").show();
	 	  // drawWheel();
	 	  $("#simpleexperrordiv").hide();
   	 	  $("#simpleexpsuccessdiv").show();
	 	  
	 	  $("#simpleexpsuccess").html('Result is being sent to given email address.');
	 	   $("html, body").animate({ scrollTop: 0 }, "slow");
	 	     e.preventDefault();
		    $.ajax({
		      type: "POST",
		      dataType: "json",
		      url: "/search/shareresult", 
		      data: data,
		      success: function(data) {
		    	  if(data['error']!=null){
		    		  $("#simpleexperrordiv").show();
					  setTimeout(function(){ $('#simpleexperrordiv').hide(); }, 10000);
		    		  $("#simpleexpsuccessdiv").hide();
		    		  $("#simpleexperror").html("");
		    	 	  $("#simpleexpsuccess").html("");
     		       $("#simpleexperror").html(data['error']);
    	        }else{
 		        	$("#simpleexperrordiv").hide();
		    		  $("#simpleexpsuccessdiv").show();
					  setTimeout(function(){ $('#simpleexpsuccessdiv').hide(); }, 10000);
 		        	$("#simpleexperror").html("");
 		 	 	  $("#simpleexpsuccess").html("");
 		          $("#simpleexpsuccess").html(data['success']);
 		        
 		        }
		      },
		      error: function(xhr, textStatus, errorThrown){
		          alert('Whoops!  It looks like there was a problem submitting your request. Please try again. If the problem persists, please contact us.');
		       },
		       complete: function(xhr, textStatus){
			   		  btn.button('reset');
			   		}
		    });
		    return false;
    
});
  
  
  $('#semailbut').click(function(){
    	$("#semail").toggle();
    });


$('#county').on('change input',function(){
	var inp=this.value;

	// call ajax call to get schools names 
	
	
	  var data = {
		      "county": inp
		    };

	  $.ajax({
	      type: "POST",
	      dataType: "json",
	      url: "/service/getschoolsByCounty", 
	      data: data,
	      success: function(data) {
	    	  if(data['schools']!=null){
	    		  
				
	    		  availableTags = JSON.parse(data['schools']);
	    		    $( "#school" ).autocomplete({
	    		    	 maxResults: 10,
	    		    	    source: function(request, response) {
	    		    	        var results = $.ui.autocomplete.filter(availableTags, request.term);
	    		    	        
	    		    	        response(results.slice(0, this.options.maxResults));
	    		    	    }
	    		     
	    		    });
	    		 
	        }else{
		        
		        
		        }
	      },
	      error: function(xhr, textStatus, errorThrown){
	          alert('Whoops!  It looks like there was a problem submitting your request. Please try again. If the problem persists, please contact us.');
	       },
	       complete: function(xhr, textStatus){
		   		  
		   		}
	    });
		
});
  
$('#aus').click(function(){
 	$("#county").prop("disabled", true);
  $("#school").attr("autocomplete","off");
$("#school").removeAttr("list");
 	restSlider();
 
 });

 $('#cal').click(function(){
 $("#school").attr("list","school_names");
 $("#school").attr("autocomplete","on");

 	$("#county").prop("disabled", false);
 	restSlider();
 });
 $('#ous').click(function(){
 	$("#county").prop("disabled", true);
  $("#school").attr("autocomplete","off");
  $("#school").removeAttr("list");
 	restSlider();
 });	
  
</script>
<!-- /chart -->

 <style>
/*#feedbackify .fby-tab-r{margin-left:0px !important;}*/
#feedbackify .fby-tab-r a{margin-left:0px !important; margin-top:1px !important;}
</style>

<script type="text/javascript">
var fby = fby || [];
fby.push(['showTab', {id: '9871', position: 'right', color: '#EB0000'}]);

(function () {
   var f = document.createElement('script'); f.type = 'text/javascript'; f.async = true;
   f.src = '//cdn.feedbackify.com/f.js';
   var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(f, s);
})();
</script>     


<script>$('#slide9').draggable();</script>

    <!-- Google Analytics -->
   <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-68102741-1', 'auto');
  ga('send', 'pageview');

</script>

</body>
</html>
